### ISSUE TITLE
HTTP Status Codes - e.g. ballerina/samples/echo/echoService.bal

### ISSUE THREAD

**Issue by FrankLeymann** [ballerinalang/ballerina#100]
Is the assumption, that "reply" in the echoService.bal automatically sets an HTTP 200 status code? I.e. is the default status code that is returned always a 200?

**Comment by pubudu91** [comment]
Now, `reply` has been replaced by `send()` and `forward()` functions bound to the response struct. The default status code that is returned is 200 in cases where the status code has not already been set **and** there weren't any errors in processing the request.

**Comment by anupama-pathirage** [comment]
Closing the issue according to the above comment
