### ISSUE TITLE
[Bug][Runtime] Provide meaningful error message when the connector declaration order is not correct

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#1004]
Sample program
`import ballerina.lang.message;
import ballerina.net.http;
import ballerina.lang.json;
import ballerina.lang.string;

@BasePath ("/echannel")
service EchannelService {

    @GET
    @Path ("/checkAvailability")
    resource availability (message m) {
	       message response;
	       json payload;
	       json jsonMsg;
	       string hospitalName;
	       hospitalName=json:getString(jsonMsg, "$.CheckAvailability.hospital");	 
               http:HTTPConnector nawalokaChannel = new http:HTTPConnector("http://localhost:9090");
               
	      if ( string:equalsIgnoreCase(hospitalName, "nawaloka") ) {
             		response = http:HTTPConnector.get(nawalokaChannel, "/nawalokaChannel/checkAvailability", m);
        		reply response;
              } else {
            		payload = `{"Status":"Not Found."}`;
              }          
   }
}
`

Here since the http connector declaration is done after the variable declaration below error occurs comes when trying to deploy the service

`hospitalService.bal:19:8: Invalid identifier 'http'`

Until the order problem of the declarations are addressed, please provide a meaningful error message to the user for better debugging purposes.

**Comment by SupunS** [comment]
Fixed in the latest version (v0.8.2)
