### ISSUE TITLE
[IDEA plugin for Ballerina] not supporting for old versions 

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/ballerina#1017]
Checked with intllij-idea versions and it seems supporting for 2016 version but not for older(14.1.3). It is good to support given older versions.
![bal_plugin](https://cloud.githubusercontent.com/assets/15671620/22278179/471dd450-e2e7-11e6-902f-25cf51a74818.jpeg)

**Comment by Shan1024** [comment]
Current ballerina plugins are compatible with IDEA version 2016.3 (which was released in August 2016) upwards.
