### ISSUE TITLE
[Idea plugin][Bug] Doesn't validate undeclared variable usage

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#1019]
Sample code
`function xmlToJsonConvertFunction(json jsonMsg) {
    xml payload;
    string convertedMessage;
    convertedMessage = json:toString(sample);
    system:println(convertedMessage);
    //return payload;
}`

In above the variable sample is undeclared and this does not get validated.

**Comment by Shan1024** [comment]
Validation for undeclared variables are not yet available in the plugin since plugin does not perform semantic analyzing yet. Created an issue to track this at plugin-intellij repo (https://github.com/ballerinalang/plugin-intellij/issues/426).
