### ISSUE TITLE
[Idea plugin] Doesn't validate duplicate variable declarations

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#1026]
Current Idea plugin does not validate duplicate variable declarations.

**Comment by Shan1024** [comment]
Inspection for duplicate variable declaration is not yet available in the plugin since plugin does not perform semantic analyzing yet. Created an issue to track this at plugin-intellij repo (https://github.com/ballerinalang/plugin-intellij/issues/427)
