### ISSUE TITLE
Cannot call a function which is inside another .bal file in the same package

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#1029]
**Main function in the colors.bal file:**

function main(string[] args) {
    string value;
    value = args[0];
    if (value == "red") {
        sayRed();
    } else {
        sayOrange();
        }
}

**sayOrange function in the orange.bal file which is in the same package.**

function sayOrange() {
    system:println("This is an Orange" );
}

Gets an error saying sayOrange function is undefined

**Comment by SupunS** [comment]
Closing the issue since this is fixed. Please reopen if the issue still persists.
