### ISSUE TITLE
[Idea Plugin] Description message for json type when used in json:getString (json json, string jsonPath) should change

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#1031]
Currently as shown in the image, the pop up is giving a message without much meaning to the user. It has to be changed to a meaningful message, that indicates the actual usage.

![bug_ideaplugin_1](https://cloud.githubusercontent.com/assets/15624590/22288818/a1ad2b3c-e31e-11e6-9676-e9ec971cde51.png)

**Comment by Shan1024** [comment]
This is due to using a Ballerina keyword as an variable name. Errors are thrown from ANTLR. So actual error might not be identified and shown in the intellij. Will check whether the error messages can be improved.
