### ISSUE TITLE
Hide internal java implementation details in case of an error message and Wrap them to give ballerina touch

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1033]
Steps:
1. Start the following service code and check the error message
2. Invoke the service

```
import ballerina.net.http;
import ballerina.lang.message;

@BasePath ("/echo")
service hiecho {

  @POST
  resource echo (message m) {
  string old;
  old = message:getStringPayload(m);
  reply old;
  }
}
```

Issue:
Error message shows internal java implementation details

^Casankav@asankav-ThinkPad-T540p:~/servers/bal/ballerina-0.8.0-SNAPSHOT/bin$ ./ballerinaserver /home/asankav/myarea/bal/echoedit.bal
Service deployed : hiecho with context /echo
Deployed ballerina file: echoedit.bal
Ballerina Server Started with Base Path : http://localhost:9090

Error while executing ballerina program. org.wso2.ballerina.core.model.values.BString cannot be cast to org.wso2.ballerina.core.model.values.BMessage
	 at echo(echoedit.bal:8)
	 at null:hiecho(echoedit.bal:5)

**Comment by SupunS** [comment]
Fixed in the latest release (v0.8.2)
