### ISSUE TITLE
Ballerina Server should't start when no ballerina service available to deploy.

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1034]
Steps:
1. Try to start ballerina server with bal file which has syntax issues.
Ex.
```
import ballerina.net.http;
import ballerina.lang.message;
import ballerina.net.http;
import ballerina.lang.message;

@BasePath ("/echo")
service hiecho {

  @POST
  resource echo (message m) {
  http:convertToResponse(m);
  reply m;
  }
}
```
Issue:
Due to syntax issues, service failed to deploy and no other service available to deploy on the server.
In this situation ballerina server should not start. But now user get a message as follows

`asankav@asankav-ThinkPad-T540p:~/servers/bal/ballerina-0.8.0-SNAPSHOT/bin$ ./ballerinaserver /home/asankav/myarea/bal/echoedit.bal
echoedit.bal: Duplicate import package declaration: ballerina.net.http in echoedit.bal:3
Warning: No Ballerina service to deploy.
Ballerina Server Started with Base Path : http://localhost:9090
`

**Comment by chanakaudaya** [comment]
Cannot reproduce in the latest ballerina 0.92 release. Now the behavior is ballerina compiler will throw semantic error and stop the execution.
