### ISSUE TITLE
[Idea plugin][Bug] - Cursor indentation when entered to mext line is misplaced

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#1044]
In an instance as below, when entered after { the cursor has to be placed correctly indented, around a. But with .bal files it's not happening. The indentation is actually misplaced which is actually placed around b.

test {
        a.                                 b.
}

**Comment by Shan1024** [comment]
This is already fixed by changing the ballerina grammar accordingly.

https://github.com/ballerinalang/plugin-intellij/blob/master/src/main/antlr/org/ballerinalang/plugins/idea/grammar/Ballerina.g4
