### ISSUE TITLE
Some Grammar Comments

### ISSUE THREAD

**Issue by FrankLeymann** [ballerinalang/ballerina#106]
The grammar still has the concept of "connection". It's my understanding that we want to drop it.
***
The following looks strange to me - why do we need the ellipsis?
```
lastFormalParameter
    :   variableModifier* typeType '...' variableDeclaratorId
    ;
```
***
Do resource parameters always include exactly one user defined type?
```
resourceParameters
    :   '(' userDefineType Identifier (',' formalParameterList)? ')'
    ;
```
***
The grammar for "ifElseStatement" allows an empty "if" path as well as an empty "else" path:
```
ifElseStatement
    :   'if' parExpression statement ('else' statement)?
    ;
```
The same is true for "whileStatement":
```
whileStatement
    :   'while' parExpression statement
    ;
```
....but the syntax summary document requires at least one statement in "while".

Since the grammar defines the empty statement ";" as statement the "while" body should also support an empty body too.  The same is true for "iterateStatement". 
***

**Comment by hasithaa** [comment]
Please find my comments inline, 

> 
> The grammar still has the concept of "connection". It's my understanding that we want to drop it.

Fixed. 
> 
> The following looks strange to me - why do we need the ellipsis?
> 
> lastFormalParameter
>     :   variableModifier* typeType '...' variableDeclaratorId
>     ;
Fixed in current grammar. 

> Do resource parameters always include exactly one user defined type?
> 
> resourceParameters
>     :   '(' userDefineType Identifier (',' formalParameterList)? ')'
>     ;

Fixed in current grammar. 

> The grammar for "ifElseStatement" allows an empty "if" path as well as an empty "else" path:
> 
> ifElseStatement
>     :   'if' parExpression statement ('else' statement)?
>     ;

Fixed in current grammar. 

> The same is true for "whileStatement":
> 
> whileStatement
>     :   'while' parExpression statement
>     ;

Fixed in current grammar. 

> ....but the syntax summary document requires at least one statement in "while".
> 
> Since the grammar defines the empty statement ";" as statement the "while" body should also support an empty body too. The same is true for "iterateStatement".

This is already addressed in current grammar.
