### ISSUE TITLE
"break" in "if"

### ISSUE THREAD

**Issue by FrankLeymann** [ballerinalang/ballerina#107]
Java allows "break" in "if". We exclude this explicitly in the syntax summary:
> A break statement allows one to terminate the immediately enclosing loop. This is only allowed  
> within the iterate or while constructs.

Why?

The grammar does not exclude a "break" in an "if".

**Comment by sameera-jayasoma** [comment]
Hi Frank,

Ballerina allows 'break' in 'if' if there exists an enclosing while loop. See the following example.

--------------
import ballerina.lang.system;

function main(string[] args) {

        int a = 1;
        while(a < 10) {
                if(lengthof args == 0) {
                        system:println("sameera");
                        break;
                }
                a = a +1;
        }

}
