### ISSUE TITLE
Sample Syntax of First Ballerina Program

### ISSUE THREAD

**Issue by FrankLeymann** [ballerinalang/ballerina#108]
The first Ballerina program defines the following action:
```
    action getTemperature(location) (int) { ...}
```
"location" is defined as
```
type location{
    int int lon;
}
```
But we invoke the action by
```
        float temperature = wc.getTemperature(new location(lat, lon));
``` 
Thus, the type definition of "location" must be fixed (or I don't get it).

**Comment by SupunS** [comment]
Hi Frank,

The grammar has evolved a bit more and the new syntaxes are a bit different now. You can find the latest samples from here:
https://github.com/ballerinalang/ballerina/tree/master/samples/getting_started

Closing the issue as the issue mentioned above is no longer there. Please do reopen if you came across any issues in the samples.
