### ISSUE TITLE
libsrc native function details are not matching with supported function details

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1084]
For Ex. ballerina support function  " http:convertToResponse(m)", But that function havent mention on the file https://github.com/gvasanka/ballerina/blob/e7d20d565d6094489a15704770d66c9a187d6f2e/libsrc/ballerina/net/http/utils.bal

Though some functions mention on the libsrc native function details file, Those functions haven't actually implemented yet.
Ex:message:setStatusCode(m,200);

**Comment by SupunS** [comment]
From v0.8.0, libsrc directory is removed from the distribution, and is auto-generated from the existing native constructs. Hence this issue no longer exists.
