### ISSUE TITLE
Syntax in ZipCodeService.bal

### ISSUE THREAD

**Issue by FrankLeymann** [ballerinalang/ballerina#109]
In ZipCodeService.bal we write

```
            message:setPayload(m, successMessage);
            message:setHeader(response, "Status", 200);
```
and
````
            message:setPayload(m, failedMessage);
            message:setHeader(response, "Status", 500);
````
We have to change "response" into "m".

**Comment by SupunS** [comment]
Hi Frank,

The grammar has evolved a bit more and the new syntaxes are a bit different now. You can find the latest samples from here:
https://github.com/ballerinalang/ballerina/tree/master/samples/getting_started

Closing the issue as the issue mentioned above is no longer there. Please do reopen if you came across any issues in the samples.
