### ISSUE TITLE
HTTP Form Data representation using a String or Byte[]

### ISSUE THREAD

**Issue by hasithaa** [ballerinalang/ballerina#110]
Scenario: 

HTTP form data may contain binary data such as files. There can be scenarios like where Ballerina developers need to access these form data individually and store in variables for later use. 

Will Ballerina require another primitive type called byte to represent these data ? or it is sufficient to use only string for this purpose. 

IMO using byte array will be more efficient because there is no character decoding step.

**Comment by SupunS** [comment]
Blob support is added with #2457, to represent binary data.
