### ISSUE TITLE
[Bug][Libsrc] addAttribute function defintion differs from the actual implementation

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#1104]
Currently the libsrc -> xml.bal defines the addAttribute function as follows
native function addAttribute(xml e, string xPath);

But the actual implementation (AddAttribute.java) takes in four arguments namely, xml, xpath, name and value

Same behavior for addElement method as well.

**Comment by SupunS** [comment]
From v0.8.0, libsrc directory is removed from the distribution, and is auto-generated from the existing native constructs. Hence this issue no longer exists.
