### ISSUE TITLE
Unable to iterate through the map and json array or object

### ISSUE THREAD

**Issue by keerthu** [ballerinalang/ballerina#1107]
Currently we are unable to iterate through the map and json array or object in ballerina.

**Comment by SupunS** [comment]
This is possible by getting the keys using `maps:getKeys(..)` and `jsons:getKeys(..)` and then iterating over the keys and obtaining the value associated to the key. Below is a sample:
```java
    json j = {"key1":"val1", "key2":"val2", "key3":"val3"};
    string[] keys = jsons:getKeys(j);

    int length = lengthof keys;
    int i = 0;
    while (i < length) {
      system:println(j[keys[i]]);
      i = i + 1;
    }
```

**Comment by JustinRong** [comment]
@SupunS why i can't use jsons? should i import jsons??
