### ISSUE TITLE
[Atom Plugin] ":" notation within XML and JSON payloads detect as a language construct

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1114]
It seems when we use ":" character on XML, JSON payloads, Plugin take them as a language construct. 

![selection_143](https://cloud.githubusercontent.com/assets/3368635/22369077/e8fccca8-e4af-11e6-92bf-1dc95c8a2d1b.png)

**Comment by SupunS** [comment]
Closing the issue since the atom plugin is no longer continued.
