### ISSUE TITLE
[Query] Can we define json, xml, message arrays?

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#1156]
Can we define json, xml, message type arrays? Found the following functions in the code. But, couldn't find any support to achieve this in the docs.

native function length (json[] array) (int);
native function length (xml[] array) (int);
native function length (message[] array) (int);

**Comment by SupunS** [comment]
JSON, XML, message arrays can be defined similar to any other array.
```
json[] j = [j1, j2, j3, ...];

XML[] x = [x1, x2, x3, ...];

message[] m = [m1, m2, m3, ... ];
```
 And the the length can now be obtained using `.length` notation.
