### ISSUE TITLE
Configuration Management For Ballerina Programs

### ISSUE THREAD

**Issue by sameera-jayasoma** [ballerinalang/ballerina#1171]
Users should be able to pass environment specific values to Ballerina programs.

E.g. URL shouldn't be hard-coded inside a Ballerina program. One option is to pass it as an environment variable.

**Comment by pubudu91** [comment]
Created #4185 and #4186 to track the improvements required in the config API since this does not have a concrete scope.

**Comment by lankavitharana** [comment]
progress tracked with https://github.com/ballerinalang/ballerina/issues/4185 and https://github.com/ballerinalang/ballerina/issues/4186

hence closing
