### ISSUE TITLE
Service deployement fails when xml and json type variable initilize with empty body

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1184]
Steps:
1. Initialize xml or json variable  as below and try start the service
Ex:
```
     xml payload1;
      json payload2;

      payload1=``;
      payload2=``;
```

Sample Code:
```
import ballerina.net.http;
import ballerina.lang.message;

@BasePath ("/httpStatusService")
service stockService {

    @GET
    resource stock (message m) {
      http:HTTPConnector myEP = new http:HTTPConnector("http://www.mocky.io");

      message reponse1;
      xml payload1;
      json payload2;

     // payload1=``;
      payload2=``;

       // message:setXmlPayload(m,payload1);
        message:setJsonPayload(m,payload2);
        message:setHeader(m, "Content-Type","text/xml;charset=UTF-8");
        message:addHeader(m, "Accept-Encoding","gzip,deflate");


        reponse1 = http:HTTPConnector.get(myEP, "/v2/58902c800f00005e15a3efe5",m);
        reply reponse1;
    }
}
```

Issue:
Getting following error when service started

> asankav@asankav-ThinkPad-T540p:~/servers/bal/ballerina-0.8.0-SNAPSHOT/bin$ ./ballerina service /home/asankav/myarea/bal/BallerinaTest/src/MockBackend/TestStatusCode.bal 
> error: fail to deploy service(s) in TestStatusCode.bal
> testStatusCode.bal:16:15: Mismatched input '`'. Expecting one of {'new', '(', '{', '[', '!', '+', '-', IntegerLiteral, FloatingPointLiteral, BooleanLiteral, QuotedStringLiteral, BacktickStringLiteral, 'null', Identifier}
> ballerina: started listener http-9090

**Comment by SupunS** [comment]
Backtick is no longer supported for XML/JSON initialization in ballerina.
Above error no longer exists with the new syntax `json j = {}`
