### ISSUE TITLE
Support of Empty CatchClause?

### ISSUE THREAD

**Issue by FrankLeymann** [ballerinalang/ballerina#121]
Java supports empty CatchClause. Ballerina does not support this:
````
// below tyeName is only 'exception'
catchClause
    :   'catch' '(' typeName Identifier ')' '{' statement+ '}'
    ;
````
Yes, empty catch clauses sound to be a bad practice.  I only want to point out the difference so that we can decide consciously.

**Comment by hasithaa** [comment]
This is supported in current Grammar.
