### ISSUE TITLE
Add support for bracedExpression, binaryPowExpression, binaryModExpression in Ballerina

### ISSUE THREAD

**Issue by sameera-jayasoma** [ballerinalang/ballerina#1243]
https://github.com/wso2/ballerina/blob/master/docs/grammar/Ballerina.g4#L408
https://github.com/wso2/ballerina/blob/master/docs/grammar/Ballerina.g4#L409
https://github.com/wso2/ballerina/blob/master/docs/grammar/Ballerina.g4#L412

**Comment by SupunS** [comment]
`binaryPowExpression` suggested here is not valid. Math library support `pow()` function.
`bracedExpression` and `binaryModExpression` is already supported.
(verified in v0.95.0)
