### ISSUE TITLE
Need Byte array / ByteBuffer support for Ballerina

### ISSUE THREAD

**Issue by irunika** [ballerinalang/ballerina#1262]
I'm currently working on WebSocket support for Ballerina and in WebSocket, we can directly receive a ByteBuffer / Byte Array from a client and the user should have the ability to process it directly as for the protocol [WebSocket Protocol -> data frames](https://tools.ietf.org/html/rfc6455#section-5.6).

**Comment by SupunS** [comment]
Blob support is added with #2457
