### ISSUE TITLE
[Idea Plugin] Wrong validation is given for while loop

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#1270]
I have tried the following with the latest available idea plugin. 

` while(i != (noOfChildElements-1)){
        index = string:valueOf(i+1);
    }`

As shown in the image, its showing a validation error but this gets deployed in runtime without an error.
![bug_ideaplugin_4](https://cloud.githubusercontent.com/assets/15624590/22545196/caebbad2-e95d-11e6-830e-f5ce31b245ff.png)

**Comment by lankavitharana** [comment]
created a issue in plugin-intellij repository, hence closing this issue

https://github.com/ballerinalang/plugin-intellij/issues/577
