### ISSUE TITLE
[Vim Plugin] [Imporvement] text blocks within double quotes inside json and xml payload, Shouldn't idenity as strings

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1324]
Currently, text resides within double quotes on a JSON or XML payload, identify and colored as a String blocks. 
Better to have separate color them for JSON and XML type messages.

Further IMO it's better to bring up separate color for functioninvocation blocks like Ex. message:getJsonPayload(m);
message:addHeader(mn, "SOAPAction","urn:getQuote");
So we can identify literals and function invocation logics separately.

![selection_159](https://cloud.githubusercontent.com/assets/3368635/22582222/814627e2-ea0b-11e6-9dd4-3d34fffb293d.png)

**Comment by SupunS** [comment]
Closing this issue, since the vim plugin is no longer continued.
