### ISSUE TITLE
Message 'reply' function should work for empty messages as well.

### ISSUE THREAD

**Issue by chaminda** [ballerinalang/ballerina#1341]
Here, I define a new message 'resp' and set the header and finally, reply the message. But rest client will not get any response from this service(just like the way that I have not put 'reply' in the resource). 
the empty message should send back. Isn't it?

@BasePath ("/modules")
service mytest{

@POST
@Path("/testpath")
resource testre(message m){
    message resp;
    resp = new message();
    message:addHeader(resp, "Content-Type","text/xml");
    reply resp;
 }
}

**Comment by SupunS** [comment]
Tested and verified on v0.87-SNAPSHOT.
