### ISSUE TITLE
[Bug][Runtime]: Greater than comparison is not supported for double

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#1355]
I tried comparing two double values using the greater than operator. But following exception occurred during run time

`greater than operation is not supported for type: double in ScatterAndGather.bal:58`

Ideally double value comparison with these operators should be supported.

**Comment by SupunS** [comment]
double type is no longer supported in ballerina.
However the type float, which is the replacement for double, works fine with the greater  than operator.
