### ISSUE TITLE
Dont have a way to Import all the members of a package.

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1362]
Right now when developing a service, We have to import all the lang package members like

import ballerina.lang.json;
import ballerina.lang.xml;
import ballerina.lang.message;
import ballerina.lang.string;
import ballerina.lang.system;

Can we get an option to import all the members of a package as java provides with import ballerina.lang.*;

**Comment by sameera-jayasoma** [comment]
Importing all is not a recommended approach even in other programming languages. This creates unwanted dependencies. You need clearly specify the set of packages you want to import.
