### ISSUE TITLE
When reply use with non returning function ballerina allow to deploy the service

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1370]
Steps:
1. Write service with below code block
`reply message:setJsonPayload(mn,etcdJSONResponse);`

2. Deploy the service
3. Invoke the service

Issue:
Getting following error

> "error in ballerina program: "

Here Dev. trying to return value from non returning function. Ideally, the interpreter should capture and handle this kind of situations and should give interpretation errors.

**Comment by SupunS** [comment]
This is fixed in v0.89
