### ISSUE TITLE
Connector action doesn't allow to invoke with reply 

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1372]
When try to do following, Interpreter reject to deploy the service with following interpreter message

Code block:
`reply etcdService:etcd.getValue(etcdConnector,symbol);`

Interpreter message:
```
error: fail to deploy service(s) in etcdConnectorUsageService.bal
etcdConnectorUsageService.bal:104: action invocation is not allowed in a reply statement
ballerina: started listener http-9090
```
Note: Complete code attached as a txt file
[etcdConnectorUsageService.txt](https://github.com/wso2/ballerina/files/750704/etcdConnectorUsageService.txt)

Issue:
Developer should allow invoking connector action with the reply. If not at least error message should correctly point to(to line number) actual error point.

Note: Following code working without an issue
  mn= etcdService:etcd.getValue(etcdConnector,symbol);
  reply mn;

**Comment by sameera-jayasoma** [comment]
We will not support this. Action invocations are only allowed with variable definition and assignment statements. Having action invocations complicates the graphical picture.
