### ISSUE TITLE
HTTP Connector post function doesn't time out when backend doesn't reply back

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1450]
Steps:
1. Start the SimpleStockQuote axis2 service
2. Start the following ballerina service

`import ballerina.net.http;
import ballerina.lang.message;
import ballerina.lang.system;

@BasePath ("/testService")
service stockService {

  @GET
  resource stock (message m) {
  http:HTTPConnector stockEP = new http:HTTPConnector("http://localhost:9000");
  message reponse;
  xml payload;

  payload=`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://services.samples" xmlns:xsd="http://services.samples/xsd">
  <soapenv:Header/>
  <soapenv:Body>
  <ser:getQuote>
  
  <ser:request>
  
  <xsd:symbol>IBM</xsd:symbol>
  </ser:request>
  </ser:getQuote>
  </soapenv:Body>
</soapenv:Envelope>`;

  message:setXmlPayload(m,payload);
  message:addHeader(m, "SOAPAction","urn:getQuote");
  message:setHeader(m, "Content-Type","text/xml;charset=UTF-8");
  message:addHeader(m, "Accept-Encoding","gzip,deflate");

  reponse = http:HTTPConnector.post(stockEP, "/services/SimpleStockQuoteService.SimpleStockQuoteServiceHttpSoap11Endpoint", m);
  reply reponse;
  }
}
`

3. Invoke the service using a client like curl, POSTMAN

Issue:
Client doesn't get any response and Hang until user down the ballerina service.

**Comment by SupunS** [comment]
Tested in v0.91. Post action times out with the following error:
```
error: ballerina.lang.errors:Error, message: failed to invoke 'post' action in ClientConnector. response was not received within sender timeout of 180 seconds
	at ballerina.net.http:ClientConnector.post(<native>:0)
	at .:main(mainFunction.bal:46)
```
