### ISSUE TITLE
Issue in resolving service/resource paths

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1475]
Steps:
1. Deploy the following code which builds the following REST hierarchy 
-testService/
  --resource a
  --b/resource b
  
2. Invoke the deployed service with below commands
curl http://localhost:9090/testService
curl http://localhost:9090/testService/a
curl http://localhost:9090/testService/b

Issue:
First curl request  should give WSO2 stock quote results
Second curl request  should give as path is invalid but still gives WSO2 stock quote results
Third  curl request should give IBM stock quote results but gives WSO2 stock quote results

Note:
When both resources have their own paths, Scenario works as expected

Code:

`import ballerina.net.http;
import ballerina.lang.message;

import ballerina.lang.system;

@BasePath ("/testService")
service stockService {

  // @Path("/a")
    @GET
    resource a (message m) {
      http:HTTPConnector stockEP = new http:HTTPConnector("http://localhost:9001");

      message _reponse;
      message ns;
      xml $payload;
      message a12;

      $payload=`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://services.samples" xmlns:xsd="http://services.samples/xsd">
       <soapenv:Header/>
       <soapenv:Body>
          <ser:getQuote>
             
             <ser:request>
                
                <xsd:symbol>WSO2</xsd:symbol>
             </ser:request>
          </ser:getQuote>
       </soapenv:Body>
    </soapenv:Envelope>`;

        message:setXmlPayload(ns,$payload);
        message:addHeader(ns, "SOAPAction","urn:getQuote");
        message:setHeader(ns, "Content-Type","text/xml;charset=UTF-8");
        message:addHeader(ns, "Accept-Encoding","gzip,deflate");

        _reponse = http:HTTPConnector.post(stockEP, "/services/SimpleStockQuoteService.SimpleStockQuoteServiceHttpSoap11Endpoint", ns);
        reply _reponse;
    }

    @Path("/b")
    @GET

    resource b (message m) {
      http:HTTPConnector stockEP = new http:HTTPConnector("http://localhost:9001");

      message _reponse;
      message ns;
      xml $payload;
      message a12;

      $payload=`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://services.samples" xmlns:xsd="http://services.samples/xsd">
       <soapenv:Header/>
       <soapenv:Body>
          <ser:getQuote>
             
             <ser:request>
                
                <xsd:symbol>IBM</xsd:symbol>
             </ser:request>
          </ser:getQuote>
       </soapenv:Body>
    </soapenv:Envelope>`;

        message:setXmlPayload(ns,$payload);
        message:addHeader(ns, "SOAPAction","urn:getQuote");
        message:setHeader(ns, "Content-Type","text/xml;charset=UTF-8");
        message:addHeader(ns, "Accept-Encoding","gzip,deflate");

        _reponse = http:HTTPConnector.post(stockEP, "/services/SimpleStockQuoteService.SimpleStockQuoteServiceHttpSoap11Endpoint", ns);
        reply _reponse;
    }
}
`

**Comment by shafreenAnfar** [comment]
This has been fixed to match the best match as explained in JAX-RS spec.
