### ISSUE TITLE
[Enhancement] Provide a thread sleep or similar 

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#1507]
Currently there is no method in delaying the execution of a step in ballerina. It will be good to have it since it will provide flexibility for ballerina developers.

**Comment by DSotnikov** [comment]
Any ETA on this? I really have a few scenarios blocked by the lack of sleep/delay function.

**Comment by sameera-jayasoma** [comment]
This is now available in the master branch and will be available in 0.92 release.
