### ISSUE TITLE
Incorrect type converter name is returned from the runtime model

### ISSUE THREAD

**Issue by TanyaM** [ballerinalang/ballerina#1525]
Following snippet returns _A->_B as the typeConverterName instead of myTypeConverter.

type A {
       string abe;

}
type B {
       string cde;

}

function foo(string x)(string){
 return x;
}

typeconvertor myTypeConverter (A y)( B) {
       B x = {};
       x.cde = foo(y.abe);
       return x;

}

**Comment by SupunS** [comment]
Type converter is no longer supported. Hence closing the issue.
