### ISSUE TITLE
Type conversions are not working in the type mapper

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#1549]
1. Add a structs and add values of below types
int, float, long, boolean
2. Add another struct and add values of below types
long, double
3. Add a type mapper and select first struct to the source and the other as the target
4. Try to map the following
boolean -> int/long/float/double
int -> long/float/double
long -> double
float -> double

Issue
All above conversions cannot be done from the type mapper

**Comment by SupunS** [comment]
Typemapper is no longer supported in ballerina. Hence closing the issue
