### ISSUE TITLE
function parameter values doesn't evaluate at the function invocation level

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1559]
[1] code block doesn't work while [2] code working

[1]
	map sample;
	string value;
	sample["key1"] = "Hello";
       value=sample["key"];
       system:println(sample["key"]);
//	system:println(value);

[2]
	map sample;
	string value;
	sample["key1"] = "Hello";
       value=sample["key"];
      // system:println(sample["key"]);
       system:println(value);

**Comment by SupunS** [comment]
Works in v0.89
