### ISSUE TITLE
Cannot start Ballerina on multiple transports

### ISSUE THREAD

**Issue by kasunbg** [ballerinalang/ballerina#1612]
Suppose I want to start Ballerina on both http and https. This is currently not possible. Ballerina only takes into account the very first listenerConfiguration in $BALLERINA_HOME/bre/conf/netty-transports.yml. 

See the thread - "[Ballerina] HTTPS protocol" for more info.

**Comment by lankavitharana** [comment]
Functionality added with pull https://github.com/ballerinalang/ballerina/pull/2912

sample service would be as follows

@http:configuration {
    basePath:"/hello",
    port:9094,
    httpsPort:9965,
    keyStoreFile:"${ballerina.home}/bre/security/wso2carbon.jks",
    keyStorePass:"wso2carbon",
    certPass:"wso2carbon"
}
service<http> helloWorld {
    @http:GET{}
    @http:Path{ value:"/abc"}
    resource sayHello (message m) {
        message response = {};
        messages:setStringPayload( response, "Hello, World!");
        reply response;
    }
}
