### ISSUE TITLE
Integer MIN_VALUE cannot be assigned

### ISSUE THREAD

**Issue by akalankapagoda** [ballerinalang/ballerina#1647]
The following statement of assigning the MIN_VALUE of an integer to a variable produces an error in the parse.

```
	int a = -2147483648;
```

This is due to the parser parsing the '-' value and '2147483648' separately and when parsing '2147483648' to an Integer it produces NumberFormatException since the MAX_VALUE for an Integer in java is 2147483647.

Need to address in the ballerina grammer to use 'SignedInteger' in these assignments.

**Comment by SupunS** [comment]
Fixed in v0.89
