### ISSUE TITLE
http connector is added to the wrong parent

### ISSUE THREAD

**Issue by roonyh** [ballerinalang/ballerina#1663]
1. Create a service
2. Add a http connector to the resource inside service
3. Drop another http connector on to the added http connector

The new connector is added to the outer service.

![screenshot from 2017-02-08 19-52-43](https://cloud.githubusercontent.com/assets/3872221/22741305/c31dd490-ee38-11e6-8a07-4cfc30ebaa71.png)
![screenshot from 2017-02-08 19-53-13](https://cloud.githubusercontent.com/assets/3872221/22741310/c7f2ad60-ee38-11e6-9a3a-6818b3238e08.png)

**Comment by SupunS** [comment]
Closing this issue and openned an issue in the correct repo: https://github.com/ballerinalang/composer/issues/372
