### ISSUE TITLE
Adding wildcard * to the middle of service path is not validated

### ISSUE THREAD

**Issue by akalankapagoda** [ballerinalang/ballerina#1678]
The following service implementation successfully gets deployed but fails to respond for any request path since the wildcard is in the middle of the path.

```
    @Path ("/test/{productId}/*/{productId}/?newId={newId}")
    resource echo (message m, @PathParam("productId") string prodId, @PathParam("newId") int newId) {
```

**Comment by shafreenAnfar** [comment]
This has been validated at the deployment time. One can only add the * at the end now.
