### ISSUE TITLE
There is no method to retrieve optional service query parameters

### ISSUE THREAD

**Issue by akalankapagoda** [ballerinalang/ballerina#1680]
In the following service implementation, optional query parameters are accepted using the wildcard.

```
    @Path ("/test/{productId}/*")
    resource echo (message m, @PathParam("productId") string prodId) {
```

However, there is not way to retrieve these optional query parameters inside the service method.

**Comment by shafreenAnfar** [comment]
This can be retrieved using getQueryFunction for more details see [1]. Hence, closing this issue.

[1] https://ballerinalang.org/docs/by-example/query-and-path-param
