### ISSUE TITLE
Value of a map element(ArrayMapAccessExpr) can be directly assign to any type

### ISSUE THREAD

**Issue by nuwanw** [ballerinalang/ballerina#1681]
In bellow sample, string value is assigned as int value without any error.

function main(string[] args) {

map cmd = {"key1":"val1", "key2":"val2"};
int i ;
//here string value is assigned to int variable
i = cmd["key1"];
}

**Comment by SupunS** [comment]
Fixed in v0.89. Now it has to be explicitly cast to int.
```
var i,_ = (int) cmd["key1"];
```
