### ISSUE TITLE
[Editor][Bug] Error is thrown for default imported package as unused

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#1700]
1. Create a bal file with a function to print hello world
2. Create another bal file with main method that invokes the above function. Here the lang.system is not used.

There following error is thrown in the backend when trying to run
"main.bal:2: unused import package "ballerina.lang.system"
"

It's wrong to throw exceptions as this for the default imported package as it was not a user action

**Comment by SupunS** [comment]
This is the correct behavior. Import should be mentioned in the same file where the package is used.
