### ISSUE TITLE
[Runtime] Interpreter should capture expressions after return and give interpreter errors

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1717]
Interpreter pass following code without giving any issues at interpreting level

function createArray(int a,int b,int c)(int x){
	 int [] myarray;
	 myarray=[a,b,c];
	 x=myarray[2];
         return ;
	 system:println(x);
 }

Note: At execution time expressions after "return" does not execute as expected.
Checked on M4

**Comment by SupunS** [comment]
Checked on v0.89. 
`system:println(x);` after return statement throws an error `unreachable statement`. This is a correct behavior.
Works without any issue, once the `system:println(x);` is removed/commented-out.
