### ISSUE TITLE
does ballerina string type variables suppose to accept null literal values, given that its provided as builtin primitive type

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1723]
Running the following program and getting below error message.
It seems student map returns null for a non-existing key and string variable takes that value.

Code:

import ballerina.lang.system;
import ballerina.lang.map;
import ballerina.lang.string;

function main(string [] args) {

map student={};
student={"1":"asanka","2":"saman","3":"kumara","4":"jane","5":"sam"};

map:remove(student,"2");

int i=0;

  while(map:length(student)>=i){
      string nd;
      nd=student[string:valueOf(i+1)];
        if(!string:equalsIgnoreCase(nd,"")){
          system:println(nd);
        }
      i=i+1;
  }
}

Error Message:

asankav@asankav-ThinkPad-T540p:~/servers/bal/ballerina-0.8.0-SNAPSHOT/bin$ ./ballerina run /home/asankav/myarea/bal/Test/maptest.bal 
asanka
error in ballerina program: argument 0 is null
	 at ballerina.lang.string:equalsIgnoreCase(maptest.bal:20)
	 at main(maptest.bal:6)

**Comment by SupunS** [comment]
Fixed in v0.87-SNAPSHOT.

```
map student = {"name":"supun"};
string subject = (string) student["subject"];
```
will throw the below error
```
error in ballerina program: cannot cast 'null' value to type 'string'
```
