### ISSUE TITLE
setting sub xml to a xml is not working with set function.

### ISSUE THREAD

**Issue by chaminda** [ballerinalang/ballerina#1728]
Sample:

function main (string[] args) {
xml parentXml = `<emp><name>Doe</name></emp>`;
xml newXml = `<age>45</age>`;
xml:set(parentXml,"/emp", newXml);
 system:println(xml:toString(parentXml));
}

Expected Result: `<emp><name>Doe</name><age>45</age></emp>`
Actual Result: `<emp><name>Doe</name></emp>`

Also when I put `<emp></emp>` as the parentXml, it is not adding sub xml.

**Comment by SupunS** [comment]
Closing the issue as this is not reproducible anymore. Please reopen if the issue still persists.
