### ISSUE TITLE
[Enhancement] Implement a mechanism to redirect messages

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#1734]
Currently ballerina does not have a message redirection mechanism. So $subject please either through a function or the http call (if we are supporting this, then we have to analyze the threat to security)

**Comment by arukshani** [comment]
Auto redirect support is already there for client connector. 

https://github.com/ballerinalang/ballerina/pull/3646/

**Comment by shafreenAnfar** [comment]
As this has been implemented on the client connector I am closing this issue. Anyways, if you meant something more than the current implementation please do reopen the issue.
