### ISSUE TITLE
Add support for controlling HTTP Transport level information from ballerina

### ISSUE THREAD

**Issue by isudana** [ballerinalang/ballerina#1736]
Support for control,
- chunking
- keep-alive
- HTTP 1.0 > 1.1

**Comment by anupama-pathirage** [comment]
Related https://github.com/ballerinalang/ballerina/issues/3952

**Comment by shafreenAnfar** [comment]
There were separate issues created for each requirement and the only thing left is configuring HTTP version. There is separate task for that. Hence closing this issue. 

https://github.com/ballerinalang/ballerina/issues/3953
