### ISSUE TITLE
Inherrit all the namespaces of source xml's to child xml with getXml

### ISSUE THREAD

**Issue by chaminda** [ballerinalang/ballerina#1741]
I am trying to get child xml[1] from source XML [2] and I am using getXml(xml,string,map) function. I am getting [3] as the output where all three(m0,m1,m3) namespaces are there. But only the m1 namespace is required here as in [1]. is there any other way to achieve this?

[1] `<m1:address xmlns:m1="http://wso2.com">
    <m1:no>4092</m1:no>
   <m1:city>Eastgate Drive, Orlando</m1:city>
   <m1:country>USA</m1:country>
</m1:address>`

[2] `<Employee xmlns:m0="http://services.samples" xmlns:m3="http://services.samples"><m0:name>Schendler Smith</m0:name><m1:address xmlns:m1="http://wso2.com">
    <m1:no>4092</m1:no><m1:city>Eastgate Drive, Orlando</m1:city><m1:country>USA</m1:country></m1:address><m3:contact>simthsc@gmail.com</m3:contact></Employee>`

[3] `<m1:address xmlns:m1="http://wso2.com" xmlns:m0="http://services.samples" xmlns:m3="http://services.samples">
    <m1:no>4092</m1:no>
   <m1:city>Eastgate Drive, Orlando</m1:city>
   <m1:country>USA</m1:country>
</m1:address>`

Sample Code is as below.
 xml xmlMulNps = `<Employee xmlns:m0="http://services.samples" xmlns:m3="http://test.samples"><m0:name>Schendler Smith</m0:name><m1:address xmlns:m1="http://wso2.com">
    <m1:no>4092</m1:no><m1:city>Eastgate Drive, Orlando</m1:city><m1:country>USA</m1:country></m1:address><m3:contact cat="email">simthsc@gmail.com</m3:contact></Employee>`;
  map multnamesps = {"m0":"http://services.samples","m1":"http://wso2.com"};
//getting child xml m1:address
    xml subMultNps = xml:getXml(xmlMulNps, "Employee/m1:address", multnamesps);
    system:println(xml:toString(subMultNps));

**Comment by SupunS** [comment]
This is the expected behaviour of XML according to the XML spec. Child elements inherit all the namespaces declared in the parent.
Hence closing the issue.
