### ISSUE TITLE
 lossless type coercions are not working within a struct

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1746]
It seems following lossless type coercions are not working within a struct

    boolean -> int/long/float/double with values 0 or 1 for false or true, respectively
    int -> long/float/double
    long -> double
    float -> double

Code:

```
import ballerina.lang.system;

function main(string [] args) {
  double n=2.2;
  system:println(n);

  Man me={name:"Asanka",age:130,bol:false,va: 2.2};
  system:println(me.name);
}

struct Man{
  string name;
  int age;
  boolean bol;
  double va;
}
```
Error:
Getting errors like below when change "va" variable value

asankav@asankav-ThinkPad-T540p:~/servers/bal/ballerina-0.8.0-SNAPSHOT/bin$ ./ballerina run  /home/asankav/myarea/bal/Test/lit.bal 
lit.bal:9: incompatible type: 'double' expected, found 'float'

asankav@asankav-ThinkPad-T540p:~/servers/bal/ballerina-0.8.0-SNAPSHOT/bin$ ./ballerina run  /home/asankav/myarea/bal/Test/lit.bal 
lit.bal:9: incompatible type: 'double' expected, found 'int'

asankav@asankav-ThinkPad-T540p:~/servers/bal/ballerina-0.8.0-SNAPSHOT/bin$ ./ballerina run  /home/asankav/myarea/bal/Test/lit.bal 
lit.bal:9: incompatible type: 'boolean' expected, found 'int

**Comment by SupunS** [comment]
With 0.89, need to cast explicitly for type coercions.
Above scenario works without an issue in v0.89 with type casting.
