### ISSUE TITLE
[Improvement] Detect all the unused imports at once and list them all on the error message

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1761]
Currently, error message list only the one unused import package on the error message.
 It's better to list all the unused import in the error message, hence developer can fix the issue in one attempt without trying again and again.

![selection_175](https://cloud.githubusercontent.com/assets/3368635/22851617/fb4f774e-f04d-11e6-8e51-daa7069a970a.png)

**Comment by lafernando** [comment]
Duplicated in #3698.
