### ISSUE TITLE
Can not have a parameter of which name is same as a function name.

### ISSUE THREAD

**Issue by chaminda** [ballerinalang/ballerina#1765]
When I run below sample[1], getting error [2]. Shouldn't this be a valid usage?

[1]
```
function main (string[] args) {
  //calling the function test123()
    test123();
 //declare and initialize a string param named test123
    string test123 = "test";

}
```
[2] redeclared symbol 'test123'

**Comment by lankavitharana** [comment]
We will not support this. with new function pointer implementation in PR https://github.com/ballerinalang/ballerina/pull/2945
we are referring functions as variables, example as follows

```
function test1()(int){
    function (int, int) returns (int) addFunction = func1;
    return addFunction(1, 2);
}

function func1 (int a, int b) (int c) {
    c = a + b;
    return;
}
```
hence won't be able to support this.
