### ISSUE TITLE
Ballerina fails to generate json message with hmac value in it body

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1767]
Following code [2] deploys successfully and when invoke with following URL [1] on PostMan.

Getting below error message [3] on runtim

[1]
http://localhost:9090/utilService/getHmac?text=asanka&key=mykey11&algorithm=SHA1

[2]

> import ballerina.lang.message;
> import ballerina.lang.system;
> import ballerina.lang.string;
> import ballerina.lang.json;
> import ballerina.util;
> 
> @BasePath ("/utilService")
> service utilService {
>     @GET
>     @Path ("/getHmac?text={textvalue}&key={keyvalue}&algorithm={algo}")
>       
>     resource macservice (message m, @QueryParam ("textvalue") string text,@QueryParam ("keyvalue") string key,@QueryParam ("algo") string algorithm) {
>         system:println("Hmac Needed Text:::::::::" + text);
>         system:println("Hmac Needed Key:::::::::" + key);
>         system:println("Hmac Needed algorithm:::::::::" + algorithm);
>        
>         string hmac=util:getHmac(text,key,algorithm);
>         system:println("Generated hmac value:::::::" + hmac);
> 
>         message response = {};
>         json responseJson;
> 
>         responseJson = `{"Text":${text}, "Key":${key}, "Algorithm":${algorithm}, "HMacValue":${hmac}}`;
>         system:println(json:toString(responseJson));
>         message:setJsonPayload(response, responseJson);
> 
>         if(!string:equalsIgnoreCase(text,hmac)){
>           reply response;
>         }
> 
>     }
> 
> }

[3]
Hmac Needed Text:::::::::asanka
Hmac Needed Key:::::::::mykey11
Hmac Needed algorithm:::::::::SHA1
Generated hmac value:::::::7lQ13jNZlg/0GCnAJ9OyKyMYhGM=
error in ballerina program: failed to create json: Unterminated object at line 1 column 73 path $.HMacValue
	 at macservice(utilService.bal:36)
	 at utilService(utilService.bal:8)

**Comment by SupunS** [comment]
Works in v0.89
