### ISSUE TITLE
Ballerina takes PathParam, QueryParam values even defined with invalid annotations

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1770]
Following service[1] with invalid annotation details deploys successfully. When invoked its gives intended results(What it supposed to give with correct PathParam, QueryParam annotations)  as well.

Invoked deployed service with below curl commands:
 curl -GET http://localhost:9090/encodeService/base64/asanka1 and 
 curl -GET "http://localhost:9090/encodeService/getHmac?text=asanka&key=myke44y11&algorithm=SHA1"

[1]

> Code:
> import ballerina.lang.message;
> import ballerina.lang.system;
> import ballerina.lang.string;
> import ballerina.lang.json;
> import ballerina.util;
> 
> @BasePath ("/encodeService")
> service utilService {
> 
>     @GET
>     @Path ("/base64/{value}")
>     resource base64serive (message m, @Anno1 ("value") string encodetext) {
> 
> 
>         system:println("Text Need to Encode:::::::::=" + encodetext);
>         string encodedText=util:base64encode(encodetext);
>         system:println("Encoded Text:::::::=" + encodedText);
> 
>         string decodedText=util:base64decode(encodedText);
>         system:println("Decoded Text:::::::=" + decodedText);
> 
>         message response = {};
> 
>         if(string:equalsIgnoreCase(encodetext,decodedText)){
>           message:setStringPayload(response, decodedText);
>           reply response;
>         }
> 
>     }
> 
> 
>     @GET
>     @Path ("/getHmac?text={textvalue}&key={keyvalue}&algorithm={algo}")
>       // @Path ("/getHmac/{textvalue}/{keyvalue}/{algo}")
> 
>     resource macservice (message m, @Anno2 ("textvalue") string text,@Anno3 ("keyvalue") string key,@Anno4 ("algo") string algorithm) {
> 
>   // resource macservice (message m, @PathParam ("textvalue") string text,@PathParam ("keyvalue") string key,@PathParam ("algo") string algorithm) {
>         system:println("Hmac Needed Text:::::::::" + text);
>         system:println("Hmac Needed Key:::::::::" + key);
>         system:println("Hmac Needed algorithm:::::::::" + algorithm);
> 
>         string hmac=util:getHmac(text,key,algorithm);
> 
>         system:println("Generated hmac value:::::::" + hmac);
> 
> 
>         message response = {};
>         json responseJson;
> 
>         responseJson = `{"Text":${text}, "Key":${key}, "Algorithm":${algorithm}, "HMacValue":${key}}`;
>         system:println(json:toString(responseJson));
>         message:setJsonPayload(response, responseJson);
> 
>         if(!string:equalsIgnoreCase(text,hmac)){
>           reply response;
>         }
> 
>     }
> 
> }

**Comment by chamil321** [comment]
The given path in the second resource is not applicable to the current HTTP API design. At first place, query params cannot be stated in the path and they are no longer used for the resource dispatching. But still, we do not restrict having user intended paths in the path attribute. But the request is not dispatched to the invalid paths as mentioned in the issue. 

Moved code to the newest API and tested with ballerina 0.95.0 version. It is working fine
Invoked deployed service with below curl commands:
curl -GET http://localhost:9090/encodeService/base64/asanka1 and
curl -GET "http://localhost:9090/encodeService/getHmac?text=asanka&key=myke44y11&algorithm=SHA1"


```ballerina
import ballerina.net.http;
import ballerina.util;

@http:configuration {basePath:"/encodeService"}
service<http> utilService {

    @http:resourceConfig {
        path:"/base64/{value}",
        methods:["GET"]
    }
    resource base64serive (http:Request req, http:Response res, string value) {
        println("Text Need to Encode:::::::::=" + value);
        string encodedText=util:base64encode(value);
        println("Encoded Text:::::::=" + encodedText);

        string decodedText=util:base64decode(encodedText);
        println("Decoded Text:::::::=" + decodedText);

        if(value.equalsIgnoreCase(decodedText)){
          res.setStringPayload(decodedText);
        }
        res.send();
    }

    @http:resourceConfig {
        path:"/getHmac",
        methods:["GET"]
    }
    resource macservice (http:Request req, http:Response res) {
        map params = req.getQueryParams();
        string textvalue;
        string keyvalue;
        string algo;
        textvalue,_ = (string)params.text;
        keyvalue,_ = (string)params.key;
        algo,_ = (string)params.algorithm;

        println("Hmac Needed Text:::::::::" + textvalue);
        println("Hmac Needed Key:::::::::" + keyvalue);
        println("Hmac Needed algorithm:::::::::" + algo);

        string hmac=util:getHmac(textvalue,keyvalue,algo);

        println("Generated hmac value:::::::" + hmac);

        json responseJson;
        responseJson = {Text:textvalue, Key:keyvalue, Algorithm:algo, HMacValue:hmac};
        println(responseJson);
        res.setJsonPayload(responseJson);

        if(!textvalue.equalsIgnoreCase(hmac)){
          res.send();
        }
    }
}
```

**Comment by anupama-pathirage** [comment]
The mentioned issue is not there in the latest release and working sample is shared above, hence resolving the issue.
