### ISSUE TITLE
Issue when converting json>>xml using type converters

### ISSUE THREAD

**Issue by chaminda** [ballerinalang/ballerina#1771]
consider json [1] which is a valid json and I am converting it to xml( and again to string. 
I am getting [2] as the result. It is always getting only the first element of the json when it doesn't have a root element. 

[1]
'{"para":"A meta-markup language, used to create markup languages such as DocBook.","GlossSeeAlso":["GML","XML"]}`

[2]`<para>A meta-markup language, used to create markup languages such as DocBook.</para>`

**Comment by SupunS** [comment]
Type converters are no longer supported. Hence closing the issue.
