### ISSUE TITLE
[Bug] Cannot obtain X-Forwarded-For header through ballerina

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#1772]
$subject please, sample code and error listed below

Sample code
`string headerValue = message:getHeader(incomingMsg, "X-Forwarded-For");
    system:println(headerValue);`

Error: 
error in ballerina program: header 'X-Forwarded-For' not present in the message
	 at ballerina.lang.message:getHeader(ControlBusService.bal:35)
	 at denyRuleForInvocation(ControlBusService.bal:17)
	 at bal.integration.ControlBus:controlBusResource(ControlBusService.bal:14)
	 at bal.integration.ControlBus:ControlBusService(ControlBusService.bal:10)

**Comment by shafreenAnfar** [comment]
Tried with the below sample and it works. Hence, closing the issue.

import ballerina.net.http;

@http:configuration {basePath:"/hello"}
service<http> helloWorld {

    @http:resourceConfig {
        methods:["GET"],
        path:"/"
    }
    resource sayHello (http:Request request, http:Response response) {
        string xHeader;
        xHeader, _ = request.getHeader("X-Forwarded-For");
        println(xHeader);
        response.setStringPayload("hiii");
        response.send();
    }
}
