### ISSUE TITLE
invalid operation: operator < not defined on 'double'

### ISSUE THREAD

**Issue by suhand** [ballerinalang/ballerina#1790]
Above error is thrown for  !=, <, >, >=, <=

Sample bal program.

```
import ballerina.lang.system;
function main(string[] args) {
    system:println(2.31d >= 2.3d);
}
```

**Comment by SupunS** [comment]
Duplicate as https://github.com/ballerinalang/ballerina/issues/1355.

Hence closing this one, and keeps the #1355 opened, for tracking.
