### ISSUE TITLE
Content type is changed to text/plain when invoking

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#1794]
I am trying to invoke [1] methods (e.g. put) although I send application/json as the content type when invoking, ballerina changes it to text/plain, so the invocation fails unless headers are specifically set

[1] https://docs.wso2.com/display/AS530/JAX-RS+Advanced

**Comment by SupunS** [comment]
Can you share the ballerina code you used?

**Comment by erandidesilva** [comment]
Tested with 0.8. Not reproducible.
