### ISSUE TITLE
[Worker] Update syntax to show worker accepts any type of parameter not only the message type

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1799]
Syntax available on [1] should be updated to give idea that worker block accepts any type of parameter

worker WorkerName (**message m**) {
    VariableDeclaration;*
    Statement;+
    [reply MessageName;]
}

[1] https://github.com/ballerinalang/ballerina/blob/master/docs/SyntaxSummary.md#defining--declaring-workers

**Comment by chanakaudaya** [comment]
worker syntax has been changed and it does not accept any variable in the new syntax. Hence closing as invalid issue for the 0.89 release.
