### ISSUE TITLE
[Worker] Many workers can be created with the same name within a resource or function blocks

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1800]
Can create workers as below.

import ballerina.lang.system;
import ballerina.lang.message;
// Global constants are visible to worker
const int index = 12;

function main(string[] args) {
  worker sampleWorker (message m)  {
    json j;
    j = `{"name":"chanaka"}`;
    message:setJsonPayload(m, j);
    system:println("constant value is " + index);
    reply m;
  }

  worker sampleWorker (int m)  {
    json j;
    j = `{"name":"chanaka"}`;
    message:setJsonPayload(m, j);
    system:println("constant value is " + index);
    reply m;
  }

  message result;
  message msg = {};
  msg -> sampleWorker;
  system:println(" worker");
 result <- sampleWorker;
 string s = message:getStringPayload(result);
  system:println(s);

}

**Comment by isudana** [comment]
Fixed with 
https://github.com/ballerinalang/ballerina/issues/1800
