### ISSUE TITLE
[Worker] Message getting passed to worker even when worker define to accept other data type params

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1809]
In following code[1], the worker has defined to accept boolean type param, But It accepts message type variable "msg". No issues observing at deploy or execution level.

[1] Code:

import ballerina.lang.system;
import ballerina.net.http;

@BasePath ("/passthrough")
service passthrough {

  @GET
    resource passthrough (message msg) {

      worker sampleWorker (boolean a)  {

          system:println("Hello in worker");
          system:println(a);
          xml payload=`<?xml version="1.0" encoding="UTF-8" ?>
      	   <name>chanaka</name>`;
          message mn={};
          http:ClientConnector stockEP = create http:ClientConnector("http://www.mocky.io/v2/");

          message reponse={};
          reponse = http:ClientConnector.post(stockEP, "589c7d22250000350a80560e", mn);
          reply reponse;
        }

        message result2={};

        // boolean mama=true;
        // mama ->  sampleWorker;

        msg -> sampleWorker;
        system:println("I am 1");

        result2 <- sampleWorker;
        system:println("I am 2");
        reply result2;
}
}

**Comment by chanakaudaya** [comment]
This code is not valid anymore. Worker syntax has been changed to not accept any parameters at the time of the definition.
