### ISSUE TITLE
[Worker]  return path worker expression doesn't validate worker name is accurate

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1812]
Following code[1] deploys successfully and fails at invocation level with error [2]

[1]

import ballerina.lang.system;
import ballerina.net.http;

@BasePath ("/passthrough")
service passthrough {

  @GET
    resource passthrough (message msg) {

      worker wadakaru1 (message a)  {
          system:println("Hello in worker");
          xml payload=`<?xml version="1.0" encoding="UTF-8" ?>
      	   <name>chanaka</name>`;
          message mn={};
          http:ClientConnector stockEP = create http:ClientConnector("http://www.mocky.io/v2/");

          message reponse={};
          reponse = http:ClientConnector.post(stockEP, "589c7d22250000350a80560e", mn);
          reply reponse;
        }

        message result2={};

        msg -> wadakaru1;
        system:println("I am 1");

        result2 <- wadakaru111;
        system:println("I am 2");
        reply result2;
}
}

[2]
Casankav@asankav-ThinkPad-T540p:~/servers/bal/worker/ballerina-0.8.0-SNAPSHOT/bin$ ./ballerina service /home/asankav/myarea/bal/Test/workerservice.bal 
Started listener http-9090
ballerina: deployed service(s) in workerservice.bal

Hello in worker
I am 1
error in ballerina program: 
	 at passthrough(workerservice.bal:10)
	 at passthrough(workerservice.bal:7)

**Comment by chanakaudaya** [comment]
Worker interaction syntax has been changed to have 2 statements for a given interaction. The worker who is sending the data (let's say W1) should use the following syntax.
var1, var2, var3 -> W2

In the receiving worker(W2), it should define the following syntax to accept the data.
var11, var22, var33 <- W1;
