### ISSUE TITLE
[Worker] Worker return path can be defined without having invocation path

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1814]
It seems "result2 <- wadakaru1;" can be added without having "msg -> wadakaru1;" expression.

Following code [1] deploy without any issues and when invoked getting below error[2]

[1]
Code:
import ballerina.lang.system;
import ballerina.net.http;

@BasePath ("/passthrough")
service passthrough {

  @GET
    resource passthrough (message msg) {

      worker wadakaru1 (message a)  {
          system:println("Hello in worker");
          xml payload=`<?xml version="1.0" encoding="UTF-8" ?>
      	   <name>chanaka</name>`;
          message mn={};
          http:ClientConnector stockEP = create http:ClientConnector("http://www.mocky.io/v2/");

          message reponse={};
          reponse = http:ClientConnector.post(stockEP, "589c7d22250000350a80560e", mn);
          reply reponse;
        }

        message result2={};

        // msg -> wadakaru1;
        system:println("I am 1");

        result2 <- wadakaru1;
        system:println("I am 2");
        reply result2;
}
}

[2]
asankav@asankav-ThinkPad-T540p:~/servers/bal/worker/ballerina-0.8.0-SNAPSHOT/bin$ ./ballerina service /home/asankav/myarea/bal/Test/workerservice.bal 
Started listener http-9090
ballerina: deployed service(s) in workerservice.bal
I am 1
error in ballerina program: 
	 at passthrough(workerservice.bal:10)
	 at passthrough(workerservice.bal:7)

**Comment by chanakaudaya** [comment]
This issue is no longer reproduced in the latest 0.92-SNAPSHOT. Please note that original code segment is not valid with the new syntax and similar code segment is added below to check.This code will give the correct symantic error related to invalid worker interaction.
```
import ballerina.net.http;
import ballerina.lang.system;

@http:configuration {basePath:"/passthrough"}
service<http> passthrough {

    @http:resourceConfig {
        methods:["POST"],
        path:"/test"
    }
    resource passthrough (message m) {

        message result2={};

        // msg -> wadakaru1;
        system:println("I am 1");

        result2 <- wadakaru1;
        system:println("I am 2");
        reply result2;
        worker wadakaru1 {
            system:println("Hello in worker");
            message mn={};
            http:ClientConnector stockEP = create http:ClientConnector("http://www.mocky.io/v2/");

            message reponse={};
            reponse = stockEP.post("589c7d22250000350a80560e", mn);
          }
    }

}
```
