### ISSUE TITLE
[Bug] http:setReasonPhrase is not working when used with http:acceptAndReturn

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#1820]
Tried with the following code
`http:acceptAndReturn(201);
http:setReasonPhrase(m, "CREATED");`

The response code returned to client looked as 201 Created (which is the default reason phrase for 201)

**Comment by chamil321** [comment]
http:acceptAndReturn(201) is not available in the current ballerina HTTP API. But tested the scenario with ballerina 0.95.0 as follows and working fine. Hence please close the issue. 
```ballerina
resource echo (http:Request req, http:Response res) {
        //.....
        res.setStatusCode(201);
        res.setReasonPhrase("Created");
        res.send();
    }
```

**Comment by shafreenAnfar** [comment]
As per the above comment, I am closing the issue.
