### ISSUE TITLE
[Worker] Service hangs when same message send to two workers

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1822]
Following code[1] deploys successfully, but when invoke hangs with the following output on the console [2].
Note: When uncomment the sout before the worker invocation, This service works as expected

[1] Code
import ballerina.lang.message;
import ballerina.lang.system;
import ballerina.net.http;

@BasePath ("/passthrough")
service passthrough {

  @GET
  resource passthrough (message msg) {

  worker wadakaru1 (message a) {

  system:println("Hello in wadakaru1");
  xml payload=`<?xml version="1.0" encoding="UTF-8" ?>
  	 <name>chanaka</name>`;
  message mn={};
  http:ClientConnector stockEP = create http:ClientConnector("http://www.mocky.io/v2/");

  message reponse={};
  reponse = http:ClientConnector.post(stockEP, "589c7d22250000350a80560e", mn);
  reply reponse;
  }

  worker wadakaru2 (message a) {

  system:println("Hello in wadakaru2");
  xml payload=`<?xml version="1.0" encoding="UTF-8" ?>
  <name>chanaka</name>`;
  message mn={};
  http:ClientConnector stockEP = create http:ClientConnector("http://www.mocky.io/v2/");

  message reponse={};
  reponse = http:ClientConnector.post(stockEP, "58a2a8b4130000560b4e07c8", mn);
  reply reponse;
  }

  message result1={};
  message result2={};
  message msgnew={};

  // system:println(message:getStringPayload(msg)+"1111");
  msg -> wadakaru1;
  msg -> wadakaru2;

  result1 <- wadakaru1;
  result2 <- wadakaru2;
  system:println(message:getStringPayload(result1));

  reply result1;
}
}

[2] OutPut:
asankav@asankav-ThinkPad-T540p:~/servers/bal/worker/ballerina-0.8.0-SNAPSHOT/bin$ ./ballerina service /home/asankav/myarea/bal/Test/workerservice.bal
Started listener http-9090
ballerina: deployed service(s) in workerservice.bal

I am 1
I am 2
Hello in wadakaru1

**Comment by chanakaudaya** [comment]
@gvasanka This should be fixed in 0.8.0 GA. Please check and reopen if it is still there.
