### ISSUE TITLE
[Worker] Improve the error message currently returning, when user use return inside worker block

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1823]
Improve the error message currently returning, when user use return inside worker block

Currently shows below error message:
error: fail to deploy service(s) in workerservice.bal
workerservice.bal:33: too many arguments to return

Improve as we do in resource block:
error: fail to deploy service(s) in workerservice.bal
workerservice.bal:57: return statement cannot be used in a resource definition

**Comment by SupunS** [comment]
Tested in v0.95.5. Gives the below error:
```
error: mainFunction.bal:6:9: return value is not expected
```
