### ISSUE TITLE
Fork-Join: Error occurred when there is no any variable declaration inside worker

### ISSUE THREAD

**Issue by chaminda** [ballerinalang/ballerina#1860]
At least 1 variable declaration should be there inside the worker of fork-join. Otherwise, it gives an error[1] which is not even meaningful.

[1]
```
error in ballerina program: 1
	 at testJoin(ValidateFork.bal:13)  // this is the line where I call the function testJoin()
	 at main(ValidateFork.bal:9)  // This is the start line of main function
```

**Comment by chanakaudaya** [comment]
This issue is fixed in the latest 0.89 release. Now workers can be declared empty. Following program executes without any issue.
```
function main(string[] args) {

int a = 1;

worker W1 {
}

}
```
