### ISSUE TITLE
comments can't be add within a Connector block and Connector action block

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1883]
Checking on 795811be9782a04a3e646b88fc34279144f0806c

Following code[1] gives interpretation level errors[2]

[1]
package sample.asanka;

import ballerina.lang.message;
import ballerina.lang.system;
import ballerina.net.string;
import ballerina.net.exception;

connector Calculator(string txt){
    //Add my comment here 1
    action add1(Calculator jcl, int a, int b) (message) {
//Add my comment here 2
      worker worker1(message m){
        //Add my comment here 3
        int response=100;
        system:println("In worker" );
        message:setStringPayload(m,string:valueOf(response));
        reply m;
      }
        message m={};
        message response={};
        m -> worker1;
        system:println("respose: Calculator" );

        response <- worker1;
        return response;
    }
    action substract1(Calculator jcl, int a, int b) (int) {
        int response=a-b;
        return response;
    }
}

function main(string[] args){
    message m;
    Calculator cal = create Calculator("text");
    m = Calculator.add1(cal, 1,2);
   system:println("respose: " + message:getStringPayload(m));

}

[2]
asankav@asankav-ThinkPad-T540p:~/servers/bal/ballerina-0.8.0-SNAPSHOT/bin$ ./ballerina run /home/asankav/myarea/bal/Test/just.bal 
just.bal:13:4: unwanted token '//Add my comment here 1'

**Comment by SupunS** [comment]
Comments within a connector block are not allowed by the grammar. To add some description about the connector-action, need to use the doc:Description{} annotation.

However, comments withing an action block is allowed. Tested with v0.89
