### ISSUE TITLE
Error message doesn't give a correct idea, When user use "new" keyword insted of "create"

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1886]
Running following code[1] and getting error [2]. It's not easy to figure out actual error from givenError message 

Code [1]:
import ballerina.net.http;
import ballerina.lang.message;
import ballerina.lang.xml;
import ballerina.lang.json;

@http:BasePath ("/stockQuoteRESTService")
service stockService {

    @http:POST
    resource stock (message m) {
      http:ClientConnector stockEP = new http:ClientConnector("http://localhost:9000");

      message reponse;
      message mn;
      json incomingJsonMessage;
      xml payload;
      string symbol;

      incomingJsonMessage= message:getJsonPayload(m);
      symbol=json:getString(incomingJsonMessage,"$.symbol");

  payload=`<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://services.samples" xmlns:xsd="http://services.samples/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:getQuote>
         
         <ser:request>
            
            <xsd:symbol>?</xsd:symbol>
         </ser:request>
      </ser:getQuote>
   </soapenv:Body>
</soapenv:Envelope>`;

        xml:set(payload,"/soapenv:Envelope/soapenv:Body/ser:getQuote/ser:request/xsd:symbol/text()",symbol,{"soapenv":"http://schemas.xmlsoap.org/soap/envelope/", "ser":"http://services.samples", "xsd":"http://services.samples/xsd"});

        message:setXmlPayload(mn,payload);
        message:addHeader(mn, "SOAPAction","urn:getQuote");
        message:setHeader(mn, "Content-Type","text/xml;charset=UTF-8");
        message:addHeader(mn, "Accept-Encoding","gzip,deflate");

        reponse = http:ClientConnector.post(stockEP, "/services/SimpleStockQuoteService.SimpleStockQuoteServiceHttpSoap11Endpoint", mn);
        reply reponse;
    }
}

Error [2]:
asankav@asankav-ThinkPad-T540p:~/servers/bal/ballerina-0.8.0-SNAPSHOT/bin$ ./ballerina service /home/asankav/svn/ballerina_test/services/artifacts/WrapSimpleStockQuoteAsREST/stockQuoteRESTService.bal 
error: fail to deploy service(s) in stockQuoteRESTService.bal
stockQuoteRESTService.bal:11:41: mismatched input 'http'. Expecting one of {';', '<', '>', '.', '+', '-', '^', '/', '*', '%', '<=', '>=', '==', '!=', '&&', '||'}

**Comment by lankavitharana** [comment]
This is a syntax error, hence the error message, I'm not sure whether we can improve this kind of error message.

**Comment by SupunS** [comment]
The related error is thrown from the parser itself, so it has no context about the reason. At the parser level, it can only tell that the token expected is different from what is found. This cannot be fixed.
We can see the same behaviour in other languages as well like java and etc.
