### ISSUE TITLE
It seems we cant add expressions before the worker block

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1888]
It seems we can't do  program as below, getting the below error [2]

Code Block [1]
connector Calculator(string txt){

    action add1(Calculator jcl, int a, int b) (message) {
      system:println("In worker 55555555" );

      worker worker1(message m){
        int response=100;
        system:println("In worker" );
        message:setStringPayload(m,string:valueOf(response));
        reply m;
      }
[conwe.txt](https://github.com/ballerinalang/ballerina/files/779817/conwe.txt)

Code Block [2]
@http:BasePath ("/test3")
service test3 {

    @http:POST
    @http:Path("/test2")
    resource test1(message m){
        message msg;
        string[] test;
        worker fork1(message m){
            string s = "tests";
            reply m;
        }
[chamiTest.txt](https://github.com/ballerinalang/ballerina/files/779829/chamiTest.txt)

Error [3]:
asankav@asankav-ThinkPad-T540p:~/servers/bal/ballerina-0.8.0-SNAPSHOT/bin$ ./ballerina run /home/asankav/myarea/bal/Test/conwe.bal 
conwe.bal:16:6: unwanted token 'worker'

**Comment by chanakaudaya** [comment]
Latest syntax documents have the correct information.
