### ISSUE TITLE
Variable declared outside the try block, is not visible inside.

### ISSUE THREAD

**Issue by chaminda** [ballerinalang/ballerina#1889]
**This issue can be reproduced when there is a worker or fork-join parallel to the try/catch block.**
below sample, I have declared msg outside the try block and going to initialize inside try block. But I am getting compilation error: `undefined symbol 'msg'`

sample code: 

@http:BasePath ("/test3")
service test3 {
    @http:POST
    @http:Path("/test2")
    resource test1(message m){
        worker fork1(message m){
            string s = "tests";
            reply m;
        }
        message msg;
        string[] test;
        try{
            msg = {};
        }catch(exception e){
            system:println("catch");
        }
        test=["test1","test2"];
        system:println("test");
        reply msg;
    }
}

**Comment by nuwanw** [comment]
Fixed in https://github.com/ballerinalang/ballerina/pull/2087
