### ISSUE TITLE
Error in XML converting to a String or a JSON

### ISSUE THREAD

**Issue by chaminda** [ballerinalang/ballerina#1897]
I am going to convert(using type converter) the attached XML which is a valid XML, to string/json type. But I am getting below error. 
[jiraIssue.txt](https://github.com/ballerinalang/ballerina/files/780485/jiraIssue.txt)

```
error in ballerina program: failed to get xml as string: ParseError at [row,col]:[27,7]
Message: The content of elements must consist of well-formed character data or markup.
```

**Comment by SupunS** [comment]
AS per the above discussion, the actual issue is in converting JSON to XML. This is tracked in [1]. Hence closing this issue.

[1] https://github.com/ballerinalang/ballerina/issues/2167
