### ISSUE TITLE
TravelManagerService mixed up

### ISSUE THREAD

**Issue by FrankLeymann** [ballerinalang/ballerina#192]
I think in `ballerina/samples/message_routing/content_based_routing/TravelManagerService.bal` 

instead of 

>   if (json:get(jsonMsg, "$.TravelpediaReservation.reservationType") == "CAR-RENTAL") {
              response = http:HttpConnector.sendPost(hotelEP, m);
          } else {
              response = http:HttpConnector.sendPost(carRentalEP, m);

it has to be

>   if (json:get(jsonMsg, "$.TravelpediaReservation.reservationType") == "CAR-RENTAL") {
              response = http:HttpConnector.sendPost(carRentalEP, m);
          } else {
              response = http:HttpConnector.sendPost(hotelEP, m);

i.e. carRentalEP and hotelEP need to be exchanged.

**Comment by SupunS** [comment]
Hi Frank,

The grammar has evolved a bit more and the new syntaxes are a bit different now. You can find the latest samples from here:
https://github.com/ballerinalang/ballerina/tree/master/samples/getting_started

Closing the issue as the issue mentioned above is no longer there. Please do reopen if you came across any issues in the samples.
