### ISSUE TITLE
Can not access service level variable concurrently inside resource

### ISSUE THREAD

**Issue by nuwanw** [ballerinalang/ballerina#1923]
When accessing the below resource concurrently, response value get corrupted. 

import ballerina.lang.message;

@http:BasePath("/productsservice")
service productmgt {

    xml payload = `<product>name</product>`;

    @http:GET
    resource product (message m) {

    message response = {};
    message:setXmlPayload(response, payload);

    reply response;
    }

}

**Comment by kasunbg** [comment]
Fix - https://github.com/ballerinalang/ballerina/pull/2101

**Comment by SupunS** [comment]
Relates to https://github.com/ballerinalang/ballerina/issues/1629

**Comment by SupunS** [comment]
Currently, by design, ballerina service level and connector level variables are not thread safe. Only map type is thread safe by default.
This is future improvement, and will be tracked via #1629. Hence closing this issue.
