### ISSUE TITLE
Error message not clear when invalid imports mention in the bal file.

### ISSUE THREAD

**Issue by wggihan** [ballerinalang/ballerina#1924]
Printed error message not clear if we use invalid or wrong import in the bal.

eg:- import ballerina**l**.lang.system;

Printed error message will be like as below.
ballerina: error reading from file: /ballerina-0.8.0-SNAPSHOT/bin reason: /ballerina-0.8.0-SNAPSHOT/bin/ballerinal/lang/system

**Comment by kasunbg** [comment]
Fix - https://github.com/ballerinalang/ballerina/pull/2102
