### ISSUE TITLE
[FileConnector][Bug] File reader doesn't include escape characters to differentiate lines etc...

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#1945]
Built on:118e02b84b24115145e07a8c74fcb31218b0655a
Given the attached content, the messages:getStringPayload(m) takes the entire content as a single line. 

**Sample**
`name,age,weight,height,emailRigel,43,53,173,mus.Aenean.eget@vehicula.eduRuby,69,93,165,mauris@atvelitPellentesque.netBeau,43,47,156,Aliquam.vulputate.ullamcorper@duiin.comNaomi,29,84,164,lacus.Etiam.bibendum@vel.orgLydia,51,82,155,et.magnis@duiFuscealiquam.comStephanie,6,53,180,Nunc.mauris@tempor.netRisa,89,96,180,dolor.Quisque.tincidunt@SedmolestieSed.comCarolyn,29,80,177,erat.nonummy.ultricies@ornaretortor.caNell,55,62,177,gravida@duilectus.co.ukNaomi,75,95,162,nec.eleifend.non@Phasellusfermentumconvallis.netEdan,51,50,177,eleifend.nec@Aeneaneuismod.netColin,51,68,169,at.risus.Nunc@nuncnulla.co.ukCalvin,36,72,159,ut.sem.Nulla@nec.eduKuame,83,93,154,mi@Duisvolutpat.eduTimon,7,82,177,eros@arcuSedeu.orgOrson,18,81,179,amet.orci@dapibusrutrum.eduKeane,16,90,154,erat@conguea.comLinus,80,90,170,elit.a@Proinvelnisl.orgHelen,57,91,161,risus@elementumsem.co.ukYolanda,50,91,168,felis.adipiscing.fringilla@atvelitPellentesque.co.ukLeah,73,51,167,adipiscing.lacus.Ut@quisdiam.co.ukFritz,41,83,173,Maecenas@necmollisvitae.co.ukLaurel,16,98,175,varius@nonbibendumsed.co.ukMona,11,84,180,convallis.in@Sed.co.ukCallum,89,93,173,blandit@risusa.netZorita,43,100,159,justo.nec@iaculis.netAaron,58,46,158,pellentesque@Nullasemper.co.ukKuame,2,96,167,vehicula.Pellentesque@enimmi.comDrew,7,56,157,nisi.sem.semper@Maurisblandit.comPrice,76,57,179,amet@magna.eduJustin,89,50,166,nec.leo.Morbi@aultricies.orgSopoline,27,89,179,Cras@lacinia.orgJamalia,30,99,172,quam.vel@viverraMaecenas.co.ukCalista,76,50,154,rhoncus.Nullam@duisemperet.orgKnox,75,52,161,sapien.cursus.in@cursus.caAimee,52,47,164,mollis.dui@arcuet.co.ukKenyon,73,92,171,Nulla.tincidunt@vel.co.ukDesirae,8,52,163,vulputate.dui.nec@Proinvelnisl.orgNathan,31,100,165,aptent@tinciduntnequevitae.co.ukMollie,20,60,150,arcu.vel.quam@sociisnatoquepenatibus.caLeo,66,80,159,non@Integer.caTad,90,59,151,Cum.sociis.natoque@Nullatinciduntneque.caDorian,35,51,180,dui.nec.urna@idliberoDonec.orgTanya,11,95,154,Cras.eu.tellus@laoreetlectusquis.orgNomlanga,9,84,162,habitant@ullamcorper.caCarolyn,87,62,167,turpis@massa.caYetta,38,55,173,Duis.sit@nonvestibulumnec.eduWyoming,11,84,169,augue@Quisquepurussapien.orgJulian,65,97,159,Proin.vel.arcu@rutrumurnanec.netKeaton,76,67,166,Morbi.vehicula.Pellentesque@id.netLani,23,97,174,tortor.nibh@Nulla.netInga,32,72,169,turpis@cursuspurus.co.ukAlexandra,7,45,155,ac@tellusnon.comDaniel,75,54,172,dolor.dolor.tempus@nisiMaurisnulla.netHilda,31,79,156,blandit@semperrutrumFusce.caGareth,84,76,156,Donec.dignissim@non.netLynn,76,81,154,consequat.auctor@at.orgDebra,64,53,152,nibh.Phasellus.nulla@turpisegestas.eduLeilani,89,84,157,rhoncus.Proin@sed.eduKim,34,71,157,eu.elit.Nulla@vitaevelitegestas.netLawrence,25,46,177,dolor.Quisque@elit.eduGavin,21,56,160,sem@semperduilectus.comHenry,59,80,150,arcu.Vestibulum.ut@mattisvelitjusto.eduJackson,52,63,159,diam.vel.arcu@Cras.netKato,35,54,166,nec.tellus@dolorquamelementum.co.ukAvram,56,56,157,varius.et.euismod@molestiepharetranibh.netRaven,62,64,179,Duis.ac@rutrumurnanec.netOlivia,26,81,154,ligula@Phasellusin.netPatrick,18,75,162,Etiam.bibendum.fermentum@sit.co.ukNaomi,84,86,153,congue@sedpede.caRogan,83,58,177,molestie.Sed.id@a.caKerry,15,97,164,posuere.enim.nisl@dictum.orgCade,23,87,175,montes@egestas.eduOmar,28,67,175,pharetra@eunibh.netGinger,12,59,166,Sed.diam.lorem@Aeneanegetmetus.co.ukAdara,43,81,166,egestas.ligula.Nullam@sapien.co.ukAlma,66,84,153,scelerisque.dui@Infaucibus.eduEliana,27,66,153,Quisque.ac.libero@Cumsociisnatoque.orgAmber,73,78,168,pede.et.risus@eget.eduJerry,82,94,174,id.ante@ametdiam.netXandra,46,90,168,posuere.vulputate@velitinaliquet.orgSopoline,47,78,163,vel.quam.dignissim@Praesentluctus.comDuncan,43,78,172,lacus@laoreetlectus.eduWilla,49,74,156,libero@auctornon.co.ukJada,1,52,161,massa.Integer@purusMaecenaslibero.caKiara,40,75,166,Cras.dolor@necimperdietnec.comKerry,63,99,171,natoque@commodoauctor.eduBeck,35,74,166,montes.nascetur@fringilla.co.ukRobin,2,76,178,interdum@musDonec.netMelanie,37,65,175,in@magnatellus.eduJulie,13,72,175,lacus.Etiam.bibendum@ornareInfaucibus.caKiara,90,45,172,Sed.nunc@erat.netAbbot,74,69,177,urna.convallis@euismodacfermentum.caCiara,80,88,169,Cum@uterosnon.co.ukTyler,18,52,176,amet.ante@tempordiamdictum.caZahir,49,87,153,mus.Proin@tristiqueaceleifend.eduCiaran,37,80,175,purus.mauris.a@Duisat.caBo,13,67,158,vitae.orci.Phasellus@Utnecurna.eduMelvin,11,99,176,viverra.Maecenas.iaculis@Aliquamauctor.comHector,60,94,169,interdum@maurisMorbinon.com`

In above there is no way to process this data as the escape characters are not read and recorded.

[largeFile.txt](https://github.com/ballerinalang/ballerina/files/783133/largeFile.txt)

**Comment by pubudu91** [comment]
As of v0.91, this issue is partially addressed. The File Connector is broken into 2 connectors: File System Server Connector and File Server Connector. The former is used to listen to a directory in the file system. If it detects a new file, the URL of the file is sent as the payload of the message. The file is not read. If one needs to read the file, one needs to use the URL given by the File System Server Connector with the File Server Connector. However, the File Server Connector is not yet there in Ballerina as of v0.92

**Comment by anupama-pathirage** [comment]
Created https://github.com/ballerinalang/connector-file/issues/5 to track this issue
