### ISSUE TITLE
ForkJoin: When we provide 'any 1' join option all specified workers are running until they done. 

### ISSUE THREAD

**Issue by chaminda** [ballerinalang/ballerina#1946]
Steps:
1. User define multiple workers with fork/join(worker1, woker2, and worker3; assume that worker2 and worker3 are slow processes)
2. Give the "any 1 of specific" option [join(any 1 worker1, worker2, worker3)]
3. worker1 completed processing and response will send to the client.
4. worker2 and worker3 are still running until complete their processes. 
when we specified the 'any 1' option, Do we need worker2/3 continuously running even once we dispatch the response to the client?

**Comment by lankavitharana** [comment]
In my opinion we should, for example it may be a scenario like worker2 and worker3 are doing db updates, so in my opinion, if we specify multiple workers inside a fork, they should all run even when join is waiting for a specific worker(if we don't need other workers to run, then there is no point specifying them within the fork right?)

**Comment by lafernando** [comment]
Yes, all workers specified should anyway run in the fork/join.
