### ISSUE TITLE
[FileConnector] Deletes the file after around 40s when using without file:acknowledge(m);

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#1947]
Takes around 30s to process even a small file like attached.
[test.txt](https://github.com/ballerinalang/ballerina/files/782759/test.txt)

**Comment by pubudu91** [comment]
As of v0.91, the connector to listen to a directory is named File System Server Connector. The new version has omitted the acknowledge() function and makes use of the 'reply' statement to send the acknowledgement. One can also specify the following post-process actions: move, delete, none.
