### ISSUE TITLE
[FileConnector][Bug] Does not sort descending manner when fileSortAttribute is set as Size and fileSortAscending is false

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#1949]
**Bal file**
`package com.bal.sample.first;

import ballerina.lang.messages;
import ballerina.lang.system;
import ballerina.net.file;

@Source (
protocol = "file",
  fileURI = "file:///home/erandi/ballerina/vfsLocation",
  pollingInterval = "20000",
  fileSortAttribute = "Size",
  fileSortAscending = "false"
  )
service orderProcessService {
    resource processOrder (message m) {
        system:println(messages:getStringPayload(m));
        file:acknowledge(m);
    }
}
`
**Expected behaviour**
The larger file in size should be processed first and the smaller file in size should be processed after that.

**Actual behaviour**
The smaller file in size is processed first

**Comment by pubudu91** [comment]
The File System Server Connector demonstrates the expected behaviour for the scenario explained above as of v0.91.
