### ISSUE TITLE
Line number should be notify when Array index out of range

### ISSUE THREAD

**Issue by chaminda** [ballerinalang/ballerina#1950]
Only the below error will get for 'Array Index out of range' issue. 
below mentioned line numbers: 1 of the service and another one of the resource. When there are several arrays in the code it will hard to capture the exact erroneous place. 

error in ballerina program: arrays index out of range: Index: 1, Size: 1
	 at testJoinAny(ValidateFork.bal:12)
	 at main(ValidateFork.bal:6)

**Comment by SupunS** [comment]
Fixed in v0.89
