### ISSUE TITLE
[FileConnector] Provide a acknowledgment timeout warning in console

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#1951]
Currently when acknowledgment timeout happens, no warning is shown in the console. Please provide a warning so that the user is aware of the timeout.

**Comment by dilini-muthumala** [comment]
The component which waits for acknowledgment prints a warn log, but it is not getting printed on the Ballerina console, as Ballerina hides those logs. 
This will be fixed in a later Ballerina release.

**Comment by anupama-pathirage** [comment]
Created https://github.com/ballerinalang/connector-file/issues/6 to track this
