### ISSUE TITLE
[File Connector] Non existing file location is not detected when polling

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#1952]
Currently, when a non existing directory is given as the file path, no error is given to indicate the polling failure. Ideally since its a non existent location since the polling is failing, it should be indicated to the user.

**Comment by dilini-muthumala** [comment]
The component which tries to find the file prints a log, but it is not getting printed on the Ballerina console, as Ballerina hides those logs. 
This will be fixed in a later Ballerina release.

**Comment by pubudu91** [comment]
As of v0.91, an error is shown on the console if the directory is non-existent or if it is a file.
