### ISSUE TITLE
Improve the error message, when user trying to use connector defined on same file with package name:connector name

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1961]
Steps:
1. Define connector as per below
```
package asanka.connectors;

import ballerina.net.http;
import ballerina.util;

connector etcd (string etcdURL, string username, string password, string apiVersion) {
```
2. Try to use the connector as below in a service define on the same file
```
@http:BasePath ("/etcdUsesample")
service stockService {

    @http:POST
    resource stock (message m) {
      http:ClientConnector stockEP = create http:ClientConnector("http://localhost:9000");
      connectors:etcd etcdConnector = create connectors:etcd("http://127.0.0.1:2379", "root", "test123", "v2");
```

3. Invoke the service as per blow.
![selection_187](https://cloud.githubusercontent.com/assets/3368635/23091021/3029e178-f5d2-11e6-86b9-30f1ebe287c7.png)

Issue:
Error message does not give clear idea on what is the issues

Note: Attached full code here 
[etcdConnectorUsageService.txt](https://github.com/ballerinalang/ballerina/files/784830/etcdConnectorUsageService.txt)

**Comment by SupunS** [comment]
Actually, the error message is correct since there are no imported packages `connectors`.
