### ISSUE TITLE
JMS service fails to consume JMS Byte Messages,Object Messages,Stream Message

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1977]
Steps:
1. Follow the steps mention in [1] and set up the MB and ballerina server
[1] https://github.com/gvasanka/ballerina/blob/458308db57a7cd9361e58ad4bf7e2e5ec235e594/samples/other_samples/jmsServiceWithMB/README.txt#L22-L22

2. Get the ballerina code available on https://github.com/gvasanka/ballerina/blob/master/samples/other_samples/jmsServiceWithMB/jmsWithMB.bal

3. Customize the ballerina code as in attached file
[mbballerina.txt](https://github.com/ballerinalang/ballerina/files/785073/mbballerina.txt)

4. Publish Byte Messages, Object Messages, Stream Messages

Issue:
Check the console and Message count on MB admin console.
Byte Messages, Object Messages, Stream Messages get stuck on the queue.

**Comment by Megala21** [comment]
We will provide complete support for different types of jms messages with 0.9 release.

**Comment by anupama-pathirage** [comment]
Created https://github.com/ballerinalang/connector-jms/issues/19 to track this
