### ISSUE TITLE
JDBC: showing a java exception when incorrect dataSourceClassName is used.

### ISSUE THREAD

**Issue by chaminda** [ballerinalang/ballerina#1978]
Following java java class cast exception is return from ballerina when I used incorrect dataSourceClassName for the sql connector
ballerina: java.lang.ClassCastException: Cannot cast com.mysql.jdbc.Driver to javax.sql.DataSource

**Comment by anupama-pathirage** [comment]
Fixed with PR https://github.com/ballerinalang/ballerina/pull/2001
