### ISSUE TITLE
Messages getting lost when use  jms:acknowledge(m,"ERROR");

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1982]
Steps:
1. Deploy the attached service
[myservice.txt](https://github.com/ballerinalang/ballerina/files/785178/myservice.txt)

2. Publish 100 messages to the queue "ballerina"
3. Check the console and Queue message count details on MB admin console

Issue:
Not all the messages getting received by the Queue consuming service and MB also doesn't show any messages remaining

**Console Out Put** 
^Casankav@asankav-ThinkPad-T540p:~/servers/bal/ballerina-0.8.0-SNAPSHOT/bin$ ./ballerina run service /home/asankav/myarea/bal/Test/my.bal 
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/asankav/servers/bal/ballerina-0.8.0-SNAPSHOT/bre/lib/slf4j-1.5.10.wso2v1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/asankav/servers/bal/ballerina-0.8.0-SNAPSHOT/bre/lib/slf4j-nop-1.7.22.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
ballerina: deploying service(s) in '/home/asankav/myarea/bal/Test/my.bal'

ballerina: started server connector http-9090
Received message In Queue :::::::::Message:::::3
Received message In Queue :::::::::Message:::::9
Received message In Queue :::::::::Message:::::4
Received message In Queue :::::::::Message:::::6
Received message In Queue :::::::::Message:::::5
Received message In Queue :::::::::Message:::::1
Received message In Queue :::::::::Message:::::8
Received message In Queue :::::::::Message:::::2
Received message In Queue :::::::::Message:::::7
Received message In Queue :::::::::Message:::::10
Received message In Queue :::::::::Message:::::11
Received message In Queue :::::::::Message:::::93
Received message In Queue :::::::::Message:::::92
Received message In Queue :::::::::Message:::::94
Received message In Topic  :::::: Message:::::5
Received message In Topic  :::::: Message:::::9
Received message In Topic  :::::: Message:::::1
Received message In Topic  :::::: Message:::::10
Received message In Topic  :::::: Message:::::7
Received message In Topic  :::::: Message:::::6
Received message In Topic  :::::: Message:::::3
Received message In Topic  :::::: Message:::::8
Received message In Topic  :::::: Message:::::11
Received message In Topic  :::::: Message:::::94
Received message In Topic  :::::: Message:::::4
Received message In Topic  :::::: Message:::::92
Received message In Topic  :::::: Message:::::93
Received message In Topic  :::::: Message:::::2

**Comment by Megala21** [comment]
This issue is related with WSO2 MB and not related with ballerina. Hence, I think we can close this issue.

**Comment by anupama-pathirage** [comment]
Created https://github.com/ballerinalang/connector-jms/issues/17 to track this
