### ISSUE TITLE
JDBC: java.lang.NumberFormatException when provide invalid values for dataSource.loginTimeout property

### ISSUE THREAD

**Issue by chaminda** [ballerinalang/ballerina#1988]
Once we provide string value for the dataSource.loginTimeout property of the sqlconnector , it gives java exception as below,

ballerina: java.lang.NumberFormatException: For input string: "io"

**Comment by anupama-pathirage** [comment]
Fixed with PR https://github.com/ballerinalang/ballerina/pull/2001
