### ISSUE TITLE
Improve the error message

### ISSUE THREAD

**Issue by kavithasub** [ballerinalang/ballerina#1995]
Error shown for the bal file[1] is not descriptive, and it doesn't tell me which line has error code.

Error: 
ballerina: org.ballerinalang.model.types.BXMLType cannot be cast to org.ballerinalang.model.VariableDef 

[1] attached testXml.txt
[testXml.txt](https://github.com/ballerinalang/ballerina/files/785678/testXml.txt)

**Comment by nuwanw** [comment]
tried with given sample testXml.txt file by replacing xmlutils with xmls because of package refactoring. could not reproduce above mentioned error.

**Comment by SupunS** [comment]
This is fixed with PR: https://github.com/ballerinalang/ballerina/pull/2013
