### ISSUE TITLE
Error when generating API docs pointing the ballerina runtime as the source

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#2059]
1. Run the below command pointing to the ballerina runtime as the source package
./ballerina doc <ballerina_source_root dir>

Issue
Below error is logged and cannot generate the API docs.

Docerina: API documentation generation failed for /home/dilinig/ballerina/: modules/editor/services/workspace-service/target/test-classes/samples/service/ServiceSample.bal:3: unused import package '"ballerina.connectors.twitter"'

**Comment by SupunS** [comment]
Seems you have pointed the source of ballerina composer to docerina. It is expected to get such errors, as the composer contains invalid ballerina files used for nefative test-cases.
To generate docs, you need to pass valid ballerina files.
