### ISSUE TITLE
[RC1] The help option does not clearly state how instructions for run can be obtained

### ISSUE THREAD

**Issue by shavantha** [ballerinalang/ballerina#2061]
[RC1] The help option does not clearly state how instructions for run can be obtained

[1]The objective is for the user to identify what options exist under run however if we give the  command as ./ballerina --help the details that show are as below. It is better to include details about how to get help for run such as to get the below command running./ballerina run --help

[1] The output when we run ./ballerina --help
=====================================
Ballerina is a flexible, powerful and beautiful programming language designed for integration.

* Find more information at http://ballerinalang.org

Usage:
  ballerina [command] [options]

Available Commands:
  run       run Ballerina main/service programs
  build     create Ballerina program archives
  docker    Dockerize Ballerina programs
  doc       generates API documentation for Ballerina packages
  test      test Ballerina program

Flags:
  --help, -h    for more information

Use "ballerina help [command]" for more information about a command.

**Comment by sameera-jayasoma** [comment]
Hi Shavantha, 

You can get the help of a command in following ways,

ballerina help run
ballerina run -h 
ballerina run service -h

**Comment by SupunS** [comment]
Closing the issue since the information can be obtained using the above-mentioned method.
