### ISSUE TITLE
[User Guide] Update screen shots and icon graphics 

### ISSUE THREAD

**Issue by appellj** [ballerinalang/ballerina#2074]
- Update screen shots to reflect latest UI. 
- Take smaller screen shots of the icons to replace the large PNGs

**Comment by appellj** [comment]
Please assign this to me

**Comment by isudana** [comment]
@appellj, 
Are you going to do the source change into ballerinalang/ballerina repository ?

**Comment by appellj** [comment]
I'll do the changes in my fork and of ballerinalang/ballerina and then issue a pull request.

**Comment by appellj** [comment]
Fixed in https://github.com/ballerinalang/ballerina/pull/2149
