### ISSUE TITLE
Return XML array with xmls:getXML(..) 

### ISSUE THREAD

**Issue by pamod** [ballerinalang/ballerina#2078]
When an XPath is evaluated, there could be a set of values which needs to be returned. Specifically for splitting purposes. 

Currently the getXML(..) returns XML object.

`xml response = xmls:getXml(xml , string , map );`

Could we have the method return an xml [] ?

**Comment by SupunS** [comment]
XPaths are no longer supported. Hence closing the issue.
In the new implementation, 'xml-sequence' serves the above requirement.
