### ISSUE TITLE
Cannot create basepath with more than one '/'

### ISSUE THREAD

**Issue by chamilaadhi** [ballerinalang/ballerina#2090]
Tried creating @http:BasePath("/hello/world") and invoke http://localhost:9090/hello/world but it does not work. It seems like only one "/" can be used. swagger does not limit the base path to single '/'.

**Comment by vinok88** [comment]
The issue seems to be in [1]. Only the first part of the URL is considered as the basepath.

[1] - https://github.com/ballerinalang/ballerina/blob/master/modules/ballerina-core/src/main/java/org/ballerinalang/services/dispatchers/http/HTTPServiceDispatcher.java#L61

**Comment by shafreenAnfar** [comment]
This has been fixed in 0.88 release.
