### ISSUE TITLE
Automatically create a queue/topic when publishing or subscribing to a queue/topic

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#2097]
Tried with MB

When we publish or subscribe to a queue/topic using a client like jmeter, the queue/topic will be automatically created in the MB.
But with ballerina, the queue/topic should be already created manually prior to publishing or subscribing to the queue/topic.

**Expected**
Create a queue/topic automatically when publishing or subscribing to a queue/topic or come up with a native method to create a queue/topic.

**Comment by Megala21** [comment]
@dilinisg - Is this similar to the https://github.com/ballerinalang/ballerina/issues/2044 ? In that case, when subscribing to queue/topic, it automatically creates the queue/topic, but fails when publishing. Can you confirm that behaviour?

**Comment by dilinisg** [comment]
Yes it is same. My bad. It works for subscribing to topics and queues. Hence, closing the issue
