### ISSUE TITLE
JMS Server only supports to retrieve string values of maps

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#2112]
1. Define a map message as follows in the JMS Client side
```
map dataMap = {"country":"US", "currency":"Dollar", "states":50};
map mapMessage = {"MapData":dataMap};
```
2. In the JMS server side try to retrieve the value of states
`system:println("Message received - " + messages:getStringValue(m,"states"));`

**Issue**
Gives an error message as integers and other types apart from string cannot be retrieved by the available method
```
error in ballerina program: given property states is not found in the Map message
at ballerina.lang.messages:getStringValue(jmsService.bal:17)
at onMessage(jmsService.bal:15)
at jmsWSO2MBQueueService(jmsService.bal:13)
```

**Expected**
Need support to retrieve other types as well

**Comment by Megala21** [comment]
@dilinisg - This works fine when we send the relevant message using a java client. GetStringValue is capable of returning values of other other types of map properties. This works fine when we send a message using java client. There is a issue in map message creation of jms client side. @amjadhifthikar - Can you have a look at this?
