### ISSUE TITLE
Cannot run a program if comments are added outside a function/struct

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#2127]
1. Comment out an entire function/struct of a program

```
//struct Location {
  //      string city;
    //    string country;
   //     int number;
//}
```

2. Run the program

Issue
unwanted token '//struct Location {'  error is logged and cannot run a program

**Comment by SupunS** [comment]
This is the expected behavior. Comments are not allowed outside of a block statement.

Please refer https://github.com/ballerinalang/ballerina/blob/master/docs/specification/docsandcomments.md for more details regarding comments in ballerina.
