### ISSUE TITLE
ballerina shell script is ignoring BALLERINA_HOME var if its set

### ISSUE THREAD

**Issue by sanjiva** [ballerinalang/ballerina#2137]
The code does this:

```
# set BALLERINA_HOME
BALLERINA_HOME=`cd "$PRGDIR/.." ; pwd`
```

It needs to check whether it exists first.

**Comment by nuwanw** [comment]
That check was removed because of other ballerina servers in same machine also refer the same BALLERINA_HOME location instead of their home location. Then all refer the common location for their logs, etc and sometime server failed to start as well.

**Comment by sameera-jayasoma** [comment]
That is correct. We need to ignore the value of the existing value.
