### ISSUE TITLE
ballerina build main|service command is not clear

### ISSUE THREAD

**Issue by imesh** [ballerinalang/ballerina#2139]
As it seems like ```ballerina build main and service``` commands expect the package name to be in the format of "org/foo/bar" instead of its actual form "org.foo.bar". This might be confusing for users as the language expect to use dot as the package name separator. Thanks!

```
$ ./ballerina build main --help
create main program archive

Usage:
  ballerina build main  <packagename> [-o filename]

Flags:
  -o    output filename
```

```
$ ./ballerina build service --help
create service program archive

Usage:
  ballerina build service <packagename>... [-o filename]

Flags:
  -o    output filename
```

**Comment by lafernando** [comment]
Now we only have one option, which is just the "build" command. This will build both services and main programs by automatically detecting the type. 

Fixed in master.
