### ISSUE TITLE
Improve JMS Server Connector documentation

### ISSUE THREAD

**Issue by Kishanthan** [ballerinalang/ballerina#2153]
Few suggestions I see on - http://ballerinalang.org/docs/user-guide/0.8/server-connectors/jms-server/

1. Need to include the documentation for ActiveMQ as well. Currently the doc has WSO2 MB only.
2. How to run from anywhere for the MB related jms sample and add documentation on how jndi.properties file is configured using the annotation. (is it relative path?)

**Comment by anupama-pathirage** [comment]
Created https://github.com/ballerinalang/connector-jms/issues/13 to track this
