### ISSUE TITLE
Current ballerina methods doesn't support implicit parameter casting

### ISSUE THREAD

**Issue by lankavitharana** [ballerinalang/ballerina#2163]
The current ballerina implementation doesn't support implicit casting for parameters, that is if there is a function signature as [1], we cannot invoke that function with an integer parameter, this happens because the function stored in symbolMap with a key which includes parameter types as well. So for example, function [1] is defined in symbol map with key "abc.float" so it is not visible when searched for a function which can accept integer (abc.int) parameter.

With current implementation, you can't define a variable name same as a function name if that function has no parameters because in that case symbolMap key will be same for both

[1] - function abc(float b)

**Comment by sanjiva** [comment]
BTW we don't have long any more .. just int and float. But your issue applies for that case too.

**Comment by lankavitharana** [comment]
fixed with pull - https://github.com/ballerinalang/ballerina/pull/2173

**Comment by lankavitharana** [comment]
pull request merged, hence resolving
