### ISSUE TITLE
JSON to XML casting causes exception

### ISSUE THREAD

**Issue by mynecker** [ballerinalang/ballerina#2167]
Sending this payload: 
```
{   "propertyA" : "test",
	"arrayB": [
		"a1","value1",
		"a2","value2",
		"a3","value3"
		],
	"@arrayC": [
		"a1","value1",
		"a2","value2",
		"a3","value3"
		]
} 
```
and trying to cast to XML 
```
@http:POST
	@http:Path("/echo")
	resource echo(message m) {
	    json jsonPayload = messages:getJsonPayload(m);
		http:convertToResponse(m);
		xml xmlPayload = (xml )jsonPayload;
		system:println(xmlPayload);
		reply m;
		
	}
```

ends in an exception _error in ballerina program: expected attribute value_

The prefix of _@_ followed by an array is causing this issue.

**Comment by hasithaa** [comment]
Hi @mynecker, 
What is the expected XML for above JSON ? 

Error is coming from underline JSON->XML lib. @arrayC is an array and which is equivalent to xml attribute array ?

**Comment by mynecker** [comment]
HI @hasithaa , 

in general: what to do with "illegal"-XML-Tag characters that appear in JSON as property-names? 

There are two options I'm aware of:
Option quoting: Some quoting should do the job - but we have to be careful to keep XML -> JSON and JSON -> XML bijective. Are you aware of any standardised quoting / transforming rules?

Option fault / exception: reject the transformation (like the status quo) and state clearly in the error message: can't map to character "@" to an tag 

With the fault / exception option in place, we should have some convenience function around, to sanitise on purpose JSON payloads before casting them (e.g. "replace '@' with 'XYZ'). 

With the quoting option in place we could end up with ambiguous results and that might be even worse than the fault / exception option. 

I have the impression, the current implementation uses '@'-prefix in JSON as indicator for an XML-Attribute. This implicit rule is dangerous as there are JSON-Payloads that just use '@' for whatever reason as property prefix and some arbitrary complex value. 

From my perspective: without a standardised quoting rule in place we should follow the fault / exception option in combination with a sanitising function one can use optionally.

**Comment by SupunS** [comment]
With the new JSON to XML conversion, we can configure the prefix uses to identify an attribute.
eg:
```
    jsons:Options opts = {attributePrefix:"#"};
    var x = jsons:toXML(j, opts);
```
With this we can convert the above XML to JSON.
However, the resulting XML will have a tag with a name starting with '@' which is invalid. This needs to be validated during the conversion.
