### ISSUE TITLE
fork/join "unexpected error occurred" when timeout is missing

### ISSUE THREAD

**Issue by jpvadell** [ballerinalang/ballerina#2171]
If you don't put the **timeout** part of the fork/join you can execute but receive this message. **ballerina: unexpected error occurred**

Correct:

import ballerina.lang.messages;
import ballerina.lang.system;

function main(string[] args) {
    system:println(args[0]);
    message m = {};        
    json error;
    fork (m) {
        worker one (message m) {
            json payload = `{"name":"one"}`;
            messages:setJsonPayload(m, payload);
            reply m;
        }
        worker two (message m) {
            json payload = `{"name":"two"}`;
            messages:setJsonPayload(m, payload);
            reply m;
        }
    } join (all) (message[] airlineResponses) {
        system:println(messages:getStringPayload(airlineResponses[0]));
        system:println(messages:getStringPayload(airlineResponses[1]));
    **} timeout (30000) (message[] airlineResponses) {
        system:println("error occurred");**
    }
}

Incorrect:
import ballerina.lang.messages;
import ballerina.lang.system;

function main(string[] args) {
    system:println(args[0]);
    message m = {};        
    json error;
    fork (m) {
        worker one (message m) {
            json payload = `{"name":"one"}`;
            messages:setJsonPayload(m, payload);
            reply m;
        }
        worker two (message m) {
            json payload = `{"name":"two"}`;
            messages:setJsonPayload(m, payload);
            reply m;
        }
    } join (all) (message[] airlineResponses) {
        system:println(messages:getStringPayload(airlineResponses[0]));
        system:println(messages:getStringPayload(airlineResponses[1]));
    }
}

**Comment by chanakaudaya** [comment]
Issue cannot be reproduced in the latest 0.92 version.
