### ISSUE TITLE
How to getInt from XML

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/ballerina#2181]
Is a similar functionality to 
`string name = jsons:getInt(obj, "name")` supported in XML?

**Comment by SupunS** [comment]
All the values in xml are stored as string. Hence theres no method to get an 'int' in particular, and everything is returnd as either an another xml element ( `getXml(xml x, string xPath)` ) or a string (`getString(xml x, string xPath) `).

But you can get the string and explitcitly cast it to an int like below:

```
    xml x = `<age>20</age>`;
    int age = (int) xmls:getString(x, "/age/text()");
```
