### ISSUE TITLE
Better error message when calling a function that doesn't have a return type set

### ISSUE THREAD

**Issue by nuwanbando** [ballerinalang/ballerina#2199]
my code is 

```
function main (string[] args) {
  system:println(getEmployees());
}

function getEmployees() {
  .....
  json employees = messages:getJsonPayload(response);
  return employees;
}
```

for this I get the error message

`foo.bal:6: undefined function 'system:println`

which is not that descriptive.

**Comment by SupunS** [comment]
in v0.89 above program throws the bellow error:
```
ballerina: unexpected error occurred
```

**Comment by anupama-pathirage** [comment]
Tested with below code with 0.95.0 version and it is having descriptive error message.
```ballerina
function main (string[] args) {
  println(getEmployees());
}

function getEmployees() {
  json employees = {name:"apple"};
  return employees;
}
```
Error message:
`
error: ../samples/testissue.bal:2:11: assignment count mismatch: expected 1 values, but found 0
error: ../samples/testissue.bal:7:3: return value is not expected
`
