### ISSUE TITLE
Implement default value support for structs

### ISSUE THREAD

**Issue by sameera-jayasoma** [ballerinalang/ballerina#2209]
Here is a sample struct.  You can only provide a default value to struct fields with the type value type.

struct Person {
    int a;
    string c = "hello";
    int k = 5;
}

**Comment by SupunS** [comment]
Reopening this issue since the PR #2252 was reverted.

**Comment by SupunS** [comment]
Added with https://github.com/ballerinalang/ballerina/pull/2265
