### ISSUE TITLE
Improve "any" type to support array related operations(ex - any to array cast)

### ISSUE THREAD

**Issue by lankavitharana** [ballerinalang/ballerina#2234]
The current implementation does not support casting array in "any" type variable back to an array reference. improve the implementation to support such operations.

**Comment by SupunS** [comment]
Supported in v0.91.

Sample:
```go
function main (string[] args) {
  int [] intArray = [1,2,3];
  any a = intArray;
  var i, e = (int[]) a;
  system:println(i); 
}
```

Output:
```
[1, 2, 3]
```
