### ISSUE TITLE
reply can't reply using an array of messages

### ISSUE THREAD

**Issue by geekaholic** [ballerinalang/ballerina#2269]
Usecase: In the fork and join example (https://github.com/ballerinalang/ballerina/blob/007127a62c20e69eb9707c19cd82fbec8056a04a/modules/ballerina-native/src/test/resources/samples/fork-join-in-function.bal), it returns an array of messages which currently can't be returned together.

Also it is unclear how to combine two messages to form a message.

**Comment by SupunS** [comment]
Array of messages can be returned from a function as in the sample.

There is no concept of combining messages. Messages contain payloads of JSON/XML/String. Different payload types can be combined by their respective operations (such as XML concat, String concat, etc) .
