### ISSUE TITLE
bug: reply can't use an element from an array of messages

### ISSUE THREAD

**Issue by geekaholic** [ballerinalang/ballerina#2270]
This seems to be a bug with language parser as it doesn't make sense why this wouldn't work.

messages[] responses;
message response;
response = responses[0];
reply responses[0]; // fails
reply response; // succeeds

**Comment by sanjiva** [comment]
You haven't allocated the array first of all .. and then haven't put anything to it. I tried similar code in a main:

import ballerina.lang.system;

function main (string[] args) {
  message[] responses = [];
  message response = {};
  response = responses[0];
  system:println (response);
//reply responses[0]; // fails
//reply response; // succeeds
}

Without the "= []" I get this error:
$ ballerina run main arrays.bal
error in ballerina program: variable 'responses' is null
	 at main(arrays.bal:3)

With that I get:
$ ballerina run main arrays.bal
error in ballerina program: arrays index out of range: Index: 0, Size: 0
	 at main(arrays.bal:3)

All correct behavior. Also you've declared the array as "messages" .. that's wrong of course.

If you see an error still please send a broken program to check.
