### ISSUE TITLE
Package use should not be mandatory

### ISSUE THREAD

**Issue by DSotnikov** [ballerinalang/ballerina#2286]
I am working on my app and at some point stopped using the XML package in my code. This made the app start failing with the following error:

> Running tweetSheets.bal application.
> tweetSheets.bal:5: unused import package '"ballerina.lang.xmls"'
> Execution Ended.

This is incorrect behavior. If I stop using some package (but still have it imported) this should not be considered a critical error. A warning would be a more appropriate way to handle that.

**Comment by lankavitharana** [comment]
If we are going to relax this rule, it can be fixed with pull https://github.com/ballerinalang/ballerina/pull/2318/files

**Comment by lafernando** [comment]
Fixed in master.
