### ISSUE TITLE
Tracemode

### ISSUE THREAD

**Issue by DSotnikov** [ballerinalang/ballerina#2290]
I am looking for an automated way to turn on and off logging of all messages. 

Not critical right now (there is an easy workaround in adding the logging lines manually and then commenting them out) but will be really nice in the cloud-hosting scenario because I would be able to enable/disable tracing without having to change the code.

**Comment by pubudu91** [comment]
As of Ballerina 0.90, you can turn off/change log levels using the `<BALLERINA_HOME>/bre/conf/logging.properties` file.

**Comment by pubudu91** [comment]
With the introduction of the config API and Ballerina config file, we can change the log levels using either CLI params or a config file. As of v0.95.0, the user can turn on/off logging for the entire program or the user can configure logging levels per package.

**Comment by anupama-pathirage** [comment]
Provided the answer, hence closing this
