### ISSUE TITLE
Unable to create a ballerina native package inside another package.

### ISSUE THREAD

**Issue by hemikak** [ballerinalang/ballerina#2310]
Currently we have a ballerina.net.http package defined at https://github.com/ballerinalang/ballerina/tree/master/modules/ballerina-native/src/main/ballerina/ballerina/net/http . But I am unable to create a package named as ballerina.net.http.swagger meaning a new folder inside the http folder.

<img width="221" alt="screen shot 2017-04-27 at 12 12 19 pm" src="https://cloud.githubusercontent.com/assets/4398820/25471037/caf509c6-2b42-11e7-9dcd-77011a8d4ce3.png">

`[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.1.1:java (default) on project ballerina-native: An exception occured while executing the Java class. null: InvocationTargetException: ballerina/net/http/swagger:1:10: unwanted token '.' -> [Help 1]`

**Comment by lankavitharana** [comment]
The issue here is built in package repository takes folders as .bal files as well. Fixed it with pull [1]

[1] - https://github.com/ballerinalang/ballerina/pull/2320/files

**Comment by lankavitharana** [comment]
pull request [1] merged, hence resolving

[1] - https://github.com/ballerinalang/ballerina/pull/2320/files
