### ISSUE TITLE
Date format is not yet support properly in sql

### ISSUE THREAD

**Issue by hariss63** [ballerinalang/ballerina#2312]
import ballerina.lang.system;
import ballerina.data.sql;

function main (string[] args) {
    map propertiesMap = {"jdbcUrl":"jdbc:mysql://localhost:3306/order_db",
                        "username":"root", "password":"root", "maximumPoolSize":1};

    string dateTime = "2017-01-30T13:27:00-08:00";

    sql:Parameter para1 = {sqlType:"timestamp", value:dateTime, direction:0};
    sql:ClientConnector dbConnector = create sql:ClientConnector(propertiesMap);
    sql:Parameter[] parameters = [para1];

    string query = "INSERT INTO orderDetails (dates) VALUES(?)";

    int updatedCount = sql:ClientConnector.update (dbConnector, query, parameters);
    string status = updatedCount + " record(s) inserted.\n";
    system:println(status);
}

error got as,

error in ballerina program: invalid value for long: 2017-01-30T13:27:00-08:00
	 at ballerina.data.sql:update(dbInsertTest.bal:15)
	 at main(dbInsertTest.bal:4)

**Comment by anupama-pathirage** [comment]
Added with #2342
