### ISSUE TITLE
Issue in String grammar

### ISSUE THREAD

**Issue by Shan1024** [ballerinalang/ballerina#2331]
Accordin to the current grammar, any string ending with `\` (even it is escaped), will not be identified as a valid string.
Eg: `string s = "\\";`

To be a valid string, there should be a character between `\` and ending `"`.
Eg: `string s = "\\a";`

![selection_101](https://cloud.githubusercontent.com/assets/4003115/25983907/291e3130-3705-11e7-8e40-cc051ddb9095.png)

**Comment by SupunS** [comment]
Works fine in v 0.91.

See below:
![screenshot from 2017-08-11 21 43 11](https://user-images.githubusercontent.com/7834839/29221968-498c5c6e-7ede-11e7-961c-b5ddf2e29196.png)
