### ISSUE TITLE
[Improvement] it would be better if jsons:getString method can create a string representation if a collection is returned. 

### ISSUE THREAD

**Issue by handakumbura** [ballerinalang/ballerina#2332]
In a situation where a json path such as "$..*" is used with jsons:getString() in balllerina 0.8, following error is observed,

`org.ballerinalang.util.exceptions.BallerinaException: Failed to get string from json. Error while executing jsonpath: The element matching path: $..* is not a String.
	at org.ballerinalang.nativeimpl.lang.utils.ErrorHandler.handleJsonPathException(ErrorHandler.java:64)
	at org.ballerinalang.nativeimpl.lang.jsons.GetString.execute(GetString.java:94)`

It would be better if jsons:getString() method can create a string representation if a collection is returned from evaluating json expression, as this would be the expected behavior according the API doc[1] and what someone comming from a loosly typed programming langauage would expect. 

[1] - http://ballerinalang.org/docs/api/0.8/ballerina.lang.jsons.html

**Comment by SupunS** [comment]
jsonpath are no longer supported in ballerina. The existing method toString() returns the string representation of the JSON. hence closing the issue.

sample:
```go
function main (string[] args) {
    json j = {"foo":"bar"};
    string s = jsons:toString(j);
    system:println(s);
}
```
Output:
```
{"foo":"bar"}
```
