### ISSUE TITLE
Error message is misleading when json:set is used with a map 

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#2337]
E.g. jsons:set(payload, "$.spreadsheetId",requiredDetails["spreadSheetId"]);

The above returns an error as "jdbcGoogleSpreadsheet/GoogleAPIExecutor.bal:10: undefined function 'jsons:set'". 

Please provide an error that actually describes the problem of using the type any here.

**Comment by SupunS** [comment]
Fixed in PR: https://github.com/ballerinalang/ballerina/pull/2325

With the new syntax ` payload["spreadsheetId"] = requiredDetails["spreadSheetId"];` following error is thrown:
```
mainFunction.bal:7: incompatible types: 'any' cannot be converted to 'json'
```
