### ISSUE TITLE
Service BasePath cannot be "/"

### ISSUE THREAD

**Issue by pubudu91** [ballerinalang/ballerina#2361]
When the base path for a service is set to the root context, the following error is given: 
`error in ballerina program: no resource found to handle the request to Service: time : no matching resource found for Path : / , Method : GET`

Omitting the base path as follows resulted in the same error. 
`@http:BasePath {}`

Given below is the program which results in the above error, when a GET request is made to http://localhost:9090/time

```import ballerina.net.http;
import ballerina.lang.messages;
import ballerina.lang.system;

@http:BasePath {value:"/"}
service time {

    @http:GET {}
    @http:Path {value:"/time"}
    resource echo (message m) {
      http:ClientConnector jsontest = create http:ClientConnector("http://date.jsontest.com/");
      message time = http:ClientConnector.get(jsontest, "/", m);
      system:println(messages:getJsonPayload (time));
      reply time;
    }
}
```

**Comment by shafreenAnfar** [comment]
This has been fixed in the .88 release.
