### ISSUE TITLE
map<any> shows unsuitable error message

### ISSUE THREAD

**Issue by chamil321** [ballerinalang/ballerina#2366]
When compiling following program with map<any>, gives "not enough arguments to return" error message for the return location of function testReturnString(). 

import ballerina.lang.system; 

struct Person {
    string name = "person";
    string lname = "default lname";    
    int age = 999;
    map adrs;
}

function main(string[] args){	
	map<any> address = {country:"US A","state":"CA"};
	Person p = {name:"Jack", age:(int)25.5,adrs:address};		
        system:println(p.name);	
}

function testReturnString () (string) {	
    string me = "this is returned";
    return me;
}

**Comment by lankavitharana** [comment]
this works fine in latest master branch, (with small changes for casting)

```
import ballerina.lang.system;

struct Person {
    string name = "person";
    string lname = "default lname";
    int age = 999;
    map adrs;
}

function main(string[] args){
    map address = {country:"US A","state":"CA"};
    Person p = {name:"Jack", age:25,adrs:address};
    system:println(p.name);
}

function testReturnString () (string) {
    string me = "this is returned";
    return me;
}
```
