### ISSUE TITLE
Global variables are not supported with testarina

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#2377]
**Steps**
1. Write some test functions as below
```
string tweetId;

function testinit()() {
     tweetId = "test";
     
}

function testTweet() {
        system:println("Print tweetId " + tweetId);
}
```
2. Execute the tests as ./ballerina test <bal file>

**Issue**
"test 'testTweet' has an error: null" is logged. The print statement will not be executed.

**Comment by lankavitharana** [comment]
this works in ballerina 0.92 release as well as the current master branch
