### ISSUE TITLE
Error when query param order is changed

### ISSUE THREAD

**Issue by mefarazath** [ballerinalang/ballerina#2384]
```
import ballerina.net.http;
import ballerina.lang.messages;
import ballerina.net.uri;

@http:BasePath {value:"/proxy"}
service OAuthProxy {

    @http:GET{} @http:Path {value:"/login?spaName={spaName}&code={code}"}
    resource login (message m) {
        // read query params
        string spaName = uri:getQueryParam(m, "spaName");
        string code = uri:getQueryParam(m, "code");

        json j = `{ "spaName" : ${spaName}, "code" : ${code} }`;
        message response = {};
        messages:setJsonPayload(m, j);
        reply m;
    }
}

```

I got the expected results when I sent a request as below in a browser,
http://localhost:9090/proxy/login?spaName=mySPA&code=hds7447676437643

Changing the query param order as below gives an error.
http://localhost:9090/proxy/login?code=hds7447676437643&spaName=mySPA

`error in ballerina program: no resource found to handle the request to Service: OAuthProxy : no matching resource found for Path : /login , Method : GET`

I also noticed that once I add the annotation @http:Path {value:"/login?spaName={spaName}&code={code}"} sending the query params become mandatory.

**Comment by shafreenAnfar** [comment]
This has been fixed in the latest pack. We no longer consider query params to uniquely identify a resource as they are optional.
