### ISSUE TITLE
Util methods for building URLs

### ISSUE THREAD

**Issue by mefarazath** [ballerinalang/ballerina#2385]
```
       // redirect to authorization server
        string authz_url = "https://localhost:9443/oauth2/authorize";
        string client_id = "4wQQHtLrn6LvWowfrpdGQc3Alpwa";
        string scope = "openid";
        string callback = "http://localhost:9090/proxy/callback";

        string redirectUri = authz_url + "?response_type=code&client_id=" + client_id + "&redirect_uri=" + callback + "&scope=" + scope;
``` 
Right now if I am to build a URL with a set of key-value pairs I have (query params) I have to do a string concatenation. It would be handy if we have a util to build a URL by may be giving a basePath and map of key-value pairs and get the URL string with query params appended.

**Comment by SupunS** [comment]
You can write a ballerina function for this purpose, and reuse it.
