### ISSUE TITLE
Empty String Check for Properties retrieved from Message

### ISSUE THREAD

**Issue by sambaheerathan** [ballerinalang/ballerina#2388]
Getting  the following error when trying to check if the string is empty
error in ballerina program: 

error in ballerina program: 
at Resource1(empty_string_check.bal:8)
at .:Service1(empty_string_check.bal:6)

Sample Program

```
import ballerina.net.http;
import ballerina.lang.messages;
import ballerina.lang.system;

@http:BasePath{value: "/test"}
service Service1 {

    @http:POST{}
    resource Resource1(message m) {
        
        //messages:setProperty(m, "user","sam");
        string user = messages:getProperty(m, "user");

        if (user == "") {
            system:println("Invalid User");
        } else {
            system:println("Valid User");
        }
        reply m;
    }
}
```

**Comment by SupunS** [comment]
Tested in v0.91.1-SNAPSHOT (master), and couldn't reproduce. Hence closing the issue.

Please reopen if the issue is encountered again.
