### ISSUE TITLE
Handle empty payloads in messages:setStringPayload() method

### ISSUE THREAD

**Issue by mefarazath** [ballerinalang/ballerina#2392]
Here's my simple ballerina service,
```

import ballerina.net.http;
import ballerina.lang.messages;

@http:BasePath {value: "/hello"}
service hello {

    @http:GET {}
    @http:Path {value: "/foo"}
    resource foo(message m) {
        message response = {};
        messages:setStringPayload(response, "hello");
        reply response;
    }
}
```

it works fine when I invoke using 
curl -k -v http://localhost:9090/hello/foo
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9090 (#0)
> GET /hello/foo HTTP/1.1
> Host: localhost:9090
> User-Agent: curl/7.50.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Content-Length: 2
< 
* Connection #0 to host localhost left intact
ss%     

I changed my service to return an empty payload as below,
```
import ballerina.net.http;
import ballerina.lang.messages;

@http:BasePath {value: "/hello"}
service hello {

    @http:GET {}
    @http:Path {value: "/foo"}
    resource foo(message m) {
        message response = {};
        messages:setStringPayload(response, "");
        reply response;
    }
}

```
When I invoke using it sort of hangs,

curl -k -v http://localhost:9090/hello/foo
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9090 (#0)
> GET /hello/foo HTTP/1.1
> Host: localhost:9090
> User-Agent: curl/7.50.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/plain
* no chunk, no close, no size. Assume close to signal end
< 

I understood this was due to missing Content-Length header. So modified my service as below,
```

import ballerina.net.http;
import ballerina.lang.messages;

@http:BasePath {value: "/hello"}
service hello {

    @http:GET {}
    @http:Path {value: "/foo"}
    resource foo(message m) {
        message response = {};
        messages:setStringPayload(response, "");
        http:setContentLength(response, 0);
        reply response;
    }
}
```

Then everything works fine.

But shouldn't the Content-Length for an empty payload be handled automatically without the user having to explicitly set it to 0?

**Comment by shafreenAnfar** [comment]
Tried with the below and it works. Hence, closing the issue.

import ballerina.net.http;

@http:configuration {basePath:"/hello"}
service<http> helloWorld {

    @http:resourceConfig {
        methods:["GET"],
        path:"/"
    }
    resource sayHello (http:Request request, http:Response response) {
        response.setStringPayload("");
        response.send();
    }
}

**Comment by mefarazath** [comment]
What is the ballerina version that includes this fix? (or the version you tested with)

**Comment by shafreenAnfar** [comment]
Sorry forgot to mention, it is Ballerina 0.95.1.

**Comment by mefarazath** [comment]
Thanks @shafreenAnfar :+1:
