### ISSUE TITLE
Worker invocation fails with error "failed to invoke 'post' action in ClientConnector. Failed to prepare request. null"

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#2418]
**Example code**
`package scenario1;

import ballerina.lang.messages;
import ballerina.net.http;
import ballerina.lang.system;

@http:BasePath {value:"/centralService"}
service centralBankService {
    http:ClientConnector connectorInstance = create http:ClientConnector("http://localhost:9090");

    @http:POST {}
    resource getQuoteDetails (message m) {

        message ntfsResponse = {};
        message bdrtResponse = {};
        ntfsResponse <- ntfs;
        bdrtResponse <- bdrt;
        system:println(messages:getStringPayload(ntfsResponse));
        system:println(messages:getStringPayload(bdrtResponse));
        //reply m;

        worker ntfs{
            message response1;
            response1 = http:ClientConnector.post(connectorInstance, "/ntfs", m);
            response1 -> default;
        }

        worker bdrt{
           message response2;
           response2 = http:ClientConnector.post(connectorInstance, "/bdrt", m);
           response2 -> default;
        }

    }

}`

**Acutal Result**
`exception in workerntfs : error in ballerina program: failed to invoke 'post' action in ClientConnector. Failed to prepare request. null
	 at ballerina.net.http:post(scenario1/IntegratorService.bal:24)

exception in workerbdrt : error in ballerina program: failed to invoke 'post' action in ClientConnector. Failed to prepare request. null
	 at ballerina.net.http:post(scenario1/IntegratorService.bal:30)
`

**Comment by hasithaa** [comment]
tested following 0.94. The issue is resolved. 

```
import ballerina.lang.system;
import ballerina.net.http;

function main(string[] arg){
    http:ClientConnector c = create http:ClientConnector("http://example.com", {});
    worker default {
        http:Response ntfsResponse = {};
        http:Response bdrtResponse = {};
        ntfsResponse <- ntfs;
        bdrtResponse <- bdrt;
        system:println(ntfsResponse.getStringPayload());
        system:println(bdrtResponse.getStringPayload());
    }

    worker ntfs{
        http:Request req = {};
        http:Response res = c.get("/", req);
        res -> default;
    }

    worker bdrt{
        http:Request req = {};
        http:Response res = c.get("/", req);
        res -> default;
    }
}
```
