### ISSUE TITLE
Transaction aborted not working for oracle insertion: ORA error given

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#2422]
When insert operation done on Oracle database table, the aborted section is not invoked as expected, rather following oracle exception occurs

"error in ballerina program: uncaught error: Error{ msg : execute update failed: ORA-00904: "ID": invalid identifier
}"

Please find the attached code and the payload details
[scenario1.zip](https://github.com/ballerinalang/ballerina/files/1037553/scenario1.zip)

**Comment by anupama-pathirage** [comment]
In this scenario the aborted section is executed without any issue. But the cause for the abort is an exception occurred in the update action. So that exception should be caught somewhere within the execution flow. Otherwise it will thrown as uncaught error as observed
