### ISSUE TITLE
[Blocker] Global variable not identified in functions even when the function  and the variable is defined in the same file

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#2429]
Please refer the sample code attached. With regarding to BackEndUpdateFunctions.bal following error is thrown when trying to deploy
`scenario1/BackEndUpdateFunctions.bal:18: undefined symbol 'scenario1:i'
[scenario1.zip](https://github.com/ballerinalang/ballerina/files/1040327/scenario1.zip)
`
**Example 2: Sample code**

```
package scenario1;

import ballerina.data.sql;
import ballerina.lang.system;

string jdbcUrl = system:getEnv("JDBC_URL");
string jdbcUsername = system:getEnv("JDBC_USERNAME");
string jdbcPassword = system:getEnv("JDBC_PASSWORD");

function init () (sql:ClientConnector connection){
    map dbProperties1 = {"jdbcUrl":jdbcUrl, "username":jdbcUsername, "password":jdbcPassword};
    connection = create sql:ClientConnector (dbProperties1);
    return;
}

function close(sql:ClientConnector connection){
    sql:ClientConnector.close(connection);
}
```
Example 2: Actual Result
`scenario1/ConnectionInitializer.bal:11: undefined symbol 'scenario1:jdbcUrl'`

**Comment by djkevincr** [comment]
This is fixed by PR https://github.com/ballerinalang/ballerina/pull/2401

**Comment by SupunS** [comment]
Tested on 0.95.1. Seems this is fixed. Hence closing.
