### ISSUE TITLE
I cannot change the HTTP method type in Design View of the Composer

### ISSUE THREAD

**Issue by muthulee** [ballerinalang/ballerina#2437]
I created a service, change it's name.
I dragged a resource and automatically http:GET resource is created. It doesn't allow me to change it via the design view of the composer.

Build date - 27th may, master branch build

**Comment by nadeeshaan** [comment]
@muthulee , currently those annotations cannot be edited at the design view, this feature will be available from our next release on wards (v0.88)

**Comment by chanakaudaya** [comment]
This is fixed in latest composer 0.92
