### ISSUE TITLE
Content-Length header is ommited when the length is 0 for an incoming message

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#2469]
**Steps**
1. Create a mock back end that sends a empty payload and a Content-Length header as 0.
2. Invoke the mock back end through Ballerina service.

**Actual result**
1. When the back end is directly invoked, the Content Length header is included with the value 0 as indicated in the attached image1
2. When the back end is invoked through ballerina, the content-length header is ommited.

**Image 1**
![image1](https://cloud.githubusercontent.com/assets/15624590/26777229/126dacec-49fa-11e7-916c-937276e823b0.png)

**Image 2**
![iamge2](https://cloud.githubusercontent.com/assets/15624590/26777230/126f51fa-49fa-11e7-95bd-d66b1c1ce4ba.png)

**Comment by shafreenAnfar** [comment]
That is okay Erandi. The reason being content length header has no meaning if there is no payload. Hence striping off is fine.
