### ISSUE TITLE
The echoService Websocket client is not working on Firefox

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#2471]
Can be found here:
https://github.com/ballerinalang/ballerina/blob/master/samples/getting_started/websocket/echoServer/client/index.html

**Comment by irunika** [comment]
@dilinisg 
This is already reported and will be fixed in the next release.
https://github.com/ballerinalang/ballerina/issues/2431
Thanks

**Comment by irunika** [comment]
This issue is already fixed by [https://github.com/wso2/carbon-transports/pull/291](url) in carbon-trasports

**Comment by djkevincr** [comment]
PR https://github.com/wso2/carbon-transports/pull/291 addresses the issue, hence closing.
