### ISSUE TITLE
Different behavior for 3xx redirection when location header is present

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#2472]
**Steps**
1. Call a back end that sends http 301 with a location header -> Currently ballerina redirects to the specified location header.

2. Call a back end that sends http 305 with a location header -> no redirection happens

Same behaviour as in above 1, for 307 and 308

This is two different behaviours when the location header is present. Ideally there should only be one behaviour that is unified to all http 3xx status codes with location header present.

**Comment by shafreenAnfar** [comment]
Hi Erandi,

Redirection was not there at the time this issue was created. Hence, must have been the client tool's behaviour. This feature is now implemented and with test-cases in the transport repo to validate each redirection scenario. 

Thanks,
Shafreen
