### ISSUE TITLE
Process multipart-form data type message

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#2475]
Currently in ballerina $subject seems to be unachievable as there's no mechanism to process the data and convert it to a readable form. The attached screenshot shows how the data is handled through ballerina. (image 1). This is not usable as this data needs to be converted to a usable manner.
![multipartformdata](https://cloud.githubusercontent.com/assets/15624590/26795984/560defde-4a45-11e7-99bd-66b9e90494fc.png)

**Comment by shafreenAnfar** [comment]
Hi Erandi,

Yeah, you are right and at the moment we cannot handle multipart. There is a separate task created for this requirement [1] and the discussion can be found it google dev group. Hence, I am closing this issue.

[1] https://github.com/ballerinalang/ballerina/issues/3752
