### ISSUE TITLE
[Websocket] If a connection is removed from a group, it will be idling and not receive any message

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#2482]
**Steps**
1. Add a connection to a group
2. Send a message to the group. The clients who are connected to the group will receive the message
3. Remove the connection from the group

**Issue**
The client will not be disconnected when the connection is removed from the group. So, the client connection will be idling without receiving any messages until the client disconnects.

Note: If the connection is stored globally, one to one messages can be sent.

**Comment by irunika** [comment]
@dilinisg 
This is now addressed by the closeConnection() function. Removing and closing connections are two different things now. Even though the connection is removed the connection will not be closed. If someone needs to close the connection user has to call closeConnection() function.
If this addresses your issue can you please close the issue or we can come to a better solution?

**Comment by dilinisg** [comment]
Closing the issue as the design has been changed
