### ISSUE TITLE
[Websocket] Support for sending/receiving any type of data in addition to strings

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#2484]
Currently, we support only the following functions for strings. Instead, support any type of data in addition to strings

ws:pushTextToConnection(connectionName, text)
ws:pushTextToGroup(groupName, text)

**Comment by irunika** [comment]
@dilinisg 
We are on the process of removing these functions and adding ws:Connection functionality to deal with supported data types. Once it is done this PR can be closed.
