### ISSUE TITLE
[Websocket] Inconsistent behaviour when multiple clients are connected using the Jmeter client 

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#2488]
Jmeter client - https://github.com/maciejzaleski/JMeter-WebSocketSampler

**Steps**
1. Write a websocket server as below
```
import ballerina.lang.system;
import ballerina.net.ws;
import ballerina.net.http;
import ballerina.lang.messages;
import ballerina.lang.jsons;

@http:BasePath {value:"/test"}
@ws:WebSocketUpgradePath {value:"/websocket"}
service myService {

    @ws:OnOpen {}
    resource onOpenMessage (message m) {
        system:println("New client connected to the server.");
    }
    @ws:OnTextMessage {}
    resource onTextMessage3 (message m) {
        json replyMsg = {name: "Dilini", "city": "Colombo"};
        system:println("Message : " + jsons:toString(replyMsg));
        ws:broadcastText(jsons:toString(replyMsg));
        system:println("Done===============");

    }
    @ws:OnClose {}
    resource onCloseMessage (message m) {
        ws:removeStoredConnection("CON1");
        system:println("client left the server.\n");
    }
}
```
2. Create two websocket samplers from jmeter, one with a payload (sampler1) and the other without a payload (sampler2). The order of the requests are sampler2 then sampler1.
3. Execute the jmeter script with 2 threads.

**Issue**
The order of the samplers are not guaranteed, but can be following.
sampler 2
sampler 2
sampler 1
sampler 1

Here, all the last 3 clients receive the message, except the first client.

**Comment by irunika** [comment]
We tried connecting to a WebSocket server with 100 concurrent clients with 1000 frames for passthrough scenario and that is working consistently now but not with JMeter client since there are no standard clients for JMeter for this scenario. We used our own client too for this check.
