### ISSUE TITLE
[Blocker] Workers are not working in the ballerina-virtual-machine branch

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#2490]
**Steps**
1. Write a service with a worker in the resource
eg: https://github.com/ballerinalang/ballerina/blob/master/modules/ballerina-native/src/test/resources/samples/worker-in-resource.bal 
(with updated syntax)
2. Run the service
3. Invoke the service

**Issue**
The following error will be returned if the resource does not have a path 
`no resource found to handle the request to Service: passthrough : null`

If the path is set, the request will timeout

**Comment by chanakaudaya** [comment]
Fixed in 0.89 release.
