### ISSUE TITLE
Validate base path when an empty string is given

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#2499]
**Sample code**
```
import ballerina.net.http;
import ballerina.lang.messages;

@http:BasePath {value:""}
service EchoService {

    resource echoResource (message m) {
        json payload = {"name":"ballerina", "age":"1"};
        message response;
        messages:setJsonPayload(response, payload);
        reply response;
    }
}
```
In an instance as above the BasePath configuration should be validated before deploying as it's a wrong configuration

**Comment by shafreenAnfar** [comment]
Tested with the below code and it works. Hence closing the issue. If you set empty it defaults to "/".

import ballerina.net.http;

@http:configuration {basePath:""}
service<http> helloWorld {

    @http:resourceConfig {
        methods:["GET"],
        path:"/"
    }
    resource sayHello (http:Request request, http:Response response) {
        response.setStringPayload("test-payload");
        response.send();
    }
}
