### ISSUE TITLE
[Dispatcher] When query parameter is used with commas the relevant parameter is taken as null

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#2511]
**Sample code**
```
   @http:GET {}
    @http:POST {}
    @http:Path {value:"/api/v1/magazines.json"}
    resource echoTwoResource (message m, @http:QueryParam {value:"name"} string name, @http:QueryParam {value:"age"} string age) {
        message response = {};
        system:println("Printing age:" + age);
        string payload = "This is a test 4 ..............." + name + ":" + age;
        messages:setStringPayload(response, payload);
        reply response;
    }

```
**Sample URI:** `http://localhost:9090/test//api/v1/magazines.json?name=jane,age=25,30`
**Response:** `This is a test 4 ...............erandi,age=25,30:null`
The value of age when printed shows as null.

**Comment by sanjiva** [comment]
It looks like this is not in the URI spec and hence we should not support it.

If a person wants to read a string and split it at "," our regex functions should certainly support that.

**Comment by sanjiva** [comment]
Not standard; not implementing.
