### ISSUE TITLE
running ballerina packages doesn't work on windows

### ISSUE THREAD

**Issue by pahans** [ballerinalang/ballerina#2535]
I have following .bal file with package defined as `foo.bar`. 
```
package foo.bar;
import ballerina.lang.messages;
import ballerina.net.http;

@http:BasePath{value: "/hello"}
service helloWorld {

    @http:POST{}
    resource sayHello(message m) {
        message response = {};
        messages:setStringPayload(response,"Hello, World!");

        reply response;
    }
}

```
when used `ballerina run main foo\bar` to run this file. on Windows I get following error. 
![selection_035](https://user-images.githubusercontent.com/1552869/26963416-16ba9c16-4d0a-11e7-9d55-6389a38d48d5.png)

**Comment by SupunS** [comment]
Tested on v0.95.0. This is fixed.
![cmd](https://user-images.githubusercontent.com/7834839/32721896-1240bee0-c88e-11e7-8e70-0ade7f3e8100.png)
