### ISSUE TITLE
Printing java related messages when errors occurred in Ballerina

### ISSUE THREAD

**Issue by irunika** [ballerinalang/ballerina#2536]
When running the sample in https://github.com/ballerinalang/ballerina/issues/2521 the error log is printed in the console and it included some java related messages. 

**ballerina.lang.errors:Error { msg : "Failed to get xml payload: failed to create xml: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Premature end of file." }
    at :getXmlPayload(<native>:0)**

**Comment by SupunS** [comment]
Tested in v0.91.1-SNAPSHOT. Couldn't reproduce the issue.
