### ISSUE TITLE
Cannot access path param value if a query param and path param have the same name

### ISSUE THREAD

**Issue by Shan1024** [ballerinalang/ballerina#2549]
If the query param and path param have the same name, path param value cannot be retrieved. Even with attaching annotations.

Sample code - 

```
import ballerina.net.http;
import ballerina.lang.messages;

@http:BasePath {value:"/hello"}
service HelloService {

    @http:Path {value:"/{version}"}
    @http:GET {}
    resource sayHello (message m, @http:PathParam {value:"version"} string pathParam,
                       @http:QueryParam {value:"version"} string queryParam) {
        message response = {};
        messages:setStringPayload(response, "PathParam: " + pathParam + " , QueryParam: " + queryParam);
        reply response;
    }
}
```

Request - `http://localhost:9090/hello/1.0?version=2.0`
Response - `PathParam: 2.0 , QueryParam: 2.0`

**Comment by shafreenAnfar** [comment]
This functionality is no longer supported. We cannot specify query params in the resource signature anymore. Hence closing this issue as this is not valid anymore.
