### ISSUE TITLE
[Blocker][JMS] Cannot set and get jms properties

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#2585]
**Issue 1**
The properties set from the publisher is not reflected in the message. Refer the below screen shot. The first text message is sent from Jmeter client.

![jmsprops](https://user-images.githubusercontent.com/1845370/27020818-c9d85afa-4f61-11e7-8380-6e7d8c41d859.png)

Publisher :

```
messages:setProperty(queueMessage,"name","value");
messages:setProperty(queueMessage,"id","1");
```

**Issue 2**
Also, the server can't retrieve the properties.

Subscriber :
```
string stringProp = messages:getProperty(m, "name");
int intProp;
errors:TypeConversionError err;
intProp, err= <int>messages:getProperty(m, "id");
```

**Comment by hasithaa** [comment]
@dilinisg, PR is merged Can you verify this?

**Comment by hasithaa** [comment]
tested in 0.93-SNAPSHOT on 23/08. It is working.
