### ISSUE TITLE
Inconsistant UX when editing annotations

### ISSUE THREAD

**Issue by muthulee** [ballerinalang/ballerina#2591]
When I usually add names in Ballerina I have to do in place editions.  But when it comes to annotation editing I can see a tiny drop down type of a box.[
<img width="374" alt="screen shot 2017-06-13 at 2 07 31 pm" src="https://user-images.githubusercontent.com/3336644/27073604-02e5e50c-5042-11e7-9ea5-ccab3c4aaef9.png">
](url)

**Comment by SupunS** [comment]
Created https://github.com/ballerinalang/composer/issues/3921 on the composer repo to track this issue.
