### ISSUE TITLE
Composer : On a brand new assignment operator box hitting enter after entering details causes it to reset

### ISSUE THREAD

**Issue by muthulee** [ballerinalang/ballerina#2592]
<img width="357" alt="screen shot 2017-06-13 at 2 21 43 pm" src="https://user-images.githubusercontent.com/3336644/27074235-27440fb2-5044-11e7-95eb-06ffb35a8ea4.png">

Now I hit enter and here is what it become.
<img width="220" alt="screen shot 2017-06-13 at 2 21 50 pm" src="https://user-images.githubusercontent.com/3336644/27074268-3a6a8990-5044-11e7-854f-51411daea031.png">

**Comment by chanakaudaya** [comment]
This issue should be created in the ballerina composer repo. Hence closing the issue.
