### ISSUE TITLE
[Blocker][JMS] Cannot set and get JMS headers

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#2596]
Tried setting and getting JMS header types as follows.

set headers:
messages:setHeader(queueMessage,"JMSType", "AAA");

get headers:
string jmsType = messages:getHeader(m,"JMSType");

**Issue**
```
ballerina.lang.errors:Error, message: header 'JMSDestination ' not present in the message
        at getHeader(<native>:0)
        at jmsService.onMessage(QueueSubscriber.bal:29)
```

**Comment by hasithaa** [comment]
@dilinisg, PR is merged Can you verify this?

**Comment by hasithaa** [comment]
Issue still presents in 0.93-SNAPSHOT. Tested on 23/08

**Comment by Asitha** [comment]
There are ten JMS Headers. We are only supporting those headers with this fix. "AAA" is not a standard JMS header. Need to use JMS properties to set custom values.

Supported JMS headers and the supported actions (set or get) is mentioned in the wiki. [1]

[1] https://github.com/ballerinalang/ballerina/blob/master/docs/server-connectors/jms-server.md#ballerina-native-functions

**Comment by hasithaa** [comment]
Thanks, @Asitha  for the explanation. I tested with given headers. It is working.
