### ISSUE TITLE
messages:getJsonPayload() gives errors when payload is empty

### ISSUE THREAD

**Issue by madhawa-gunasekara** [ballerinalang/ballerina#2607]
ballerina.lang.errors:Error, message: failed to get json payload: failed to create json: No content to map due to end-of-input
 at [Source: org.wso2.carbon.messaging.CarbonMessage$ByteBufferInputStream@2093fd42; line: 1, column: 0]
	at getJsonPayload(<native>:0)
	at SimpleSelect.getProductsQuery(i.bal:15)

**Comment by pubudu91** [comment]
Tested this with v0.93.1-SNAPSHOT with the following code sample and a `500` error is returned to the user. 

```BALLERINA
import ballerina.net.http;
import ballerina.lang.system;

service<http> helloWorld {
    resource sayHello (http:Request req, http:Response res) {
        json j = req.getJsonPayload();
        system:println(j);
        res.send();
    }
}
```

**Comment by pubudu91** [comment]
In the type of programs such as above, the function should return the error so the user can handle it. This issue can be closed since there is a separate issue created (#2607) to track the addition of returning errors in functions in the HTTP library.

**Comment by shafreenAnfar** [comment]
As per the above comment, I am closing this issue.
