### ISSUE TITLE
Making debug option in CLI visible in command help.  

### ISSUE THREAD

**Issue by hevayo** [ballerinalang/ballerina#2608]
Currently the debug option in ballerina command is hidden in help text. It will be helpful to the user if we can show it in command help. 

Also it will make sense to rename --ballerina-debug to --debug and give a different name to current --debug option which will allow to debug  run-time.

**Comment by dakshika** [comment]
Even in composer UI we asked to use like this.

`ballerina run helloWorld.bal --ballerina.debug 5006`

 Users may get confused by seen multiple ballerina terms within single CLI option.
