### ISSUE TITLE
Request to make PID creation optional

### ISSUE THREAD

**Issue by imesh** [ballerinalang/ballerina#2616]
Currently, Ballerina creates a PID file for both services and main functions. This becomes an issue when running a BAL function on a serverless environment where there is no write access to the execution folder. The only workaround is to copy the entire BRE to the /tmp folder and run.

**Comment by sameera-jayasoma** [comment]
With 0.91 release of Ballerina, we stopped creating the PID for main functions. We only create for services. But we can even stop that until we find a proper solution. This is only required for Ballerina server use case.
