### ISSUE TITLE
[workers] "unexpected error occurred" when there is an idling worker

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#2622]
**Steps**
1. Create a service with worker1 and worker2
2. Send and receive few variables to/from worker1, but do not use the worker2
2. Run the service

**Issue**
"ballerina: unexpected error occurred" is logged and the service will not be deployed

**Comment by lafernando** [comment]
Ballerina v0.94.

Now we can't send and receive values to himself. For example, the following scenario will not work.


function main (string[] args) {
 
  worker w1 {
    int a = 5;
    int b;
    a -> w1;
    b <- w1;
  }

}

If you have another scenario, please put a concrete sample and re-open the issue.
