### ISSUE TITLE
[JMS] Cannot use the relative path of the jndi.properties file when running a package

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#2627]
**Steps**
1. Create a publisher and a subscriber in the package jms.automation
2. Add the relative path of the jndi.properties file 
3. Run the package
./ballerina run service jms/automation

**Issue**
`"ballerina: error when starting to listen to the queue/topic while jmsQueueSubscriberService deployment" `error is logged and the services will not be started

**Comment by Asitha** [comment]
This work if you set the relative path from the directory you are executing the ballerina code. Not the relative path from the location of the ballerina file.

**Comment by SupunS** [comment]
This is tracked at: https://github.com/ballerinalang/connector-jms/issues/12
