### ISSUE TITLE
[JMS][Improvement] Connection close/session close operations are not supported 

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#2628]
When a JMS Server is started, it starts listening to the queue/topic and when the service is stopped, the JMS server stops.

1. Can't we write the JMS server in a way that we have to invoke the service to start the server?
2. Can't we have separate methods to close the connection of the server without stopping the service?

**Note**: In Java, there are methods for connection close, session close etc.

**Comment by SupunS** [comment]
This is tracked at: https://github.com/ballerinalang/connector-jms/issues/11
