### ISSUE TITLE
Casting error when using 'getStringWithNamespace' 

### ISSUE THREAD

**Issue by sashikamw** [ballerinalang/ballerina#2630]
Environment - Ballerina 0.89 Snapshot (19/06/2017)

Casting error observed when extracting the value from a xpath with namespaces

Sample:
```
map namespace = {"ser":"http://services.samples","xsd":"http://services.samples/xsd"};
        string stock = xmls:getStringWithNamespace(incomingPayload, "//ser:getQuote/ser:request/xsd:symbol/text()", namespace);
```

Error :
`ballerina.lang.errors:Error, message: failed to get string from xml: java.lang.String cannot be cast to org.ballerinalang.model.values.BString
	at getStringWithNamespace(<native>:0)
	at xpathNameSpacefilter.XPathNameSpaceResource(MessageRouting/MessageFiltering/XPathNameSpaceFilter.bal:18)
`

**Comment by SupunS** [comment]
Fixed in v0.89
