### ISSUE TITLE
[Transactions] abort statement inside the aborted section gives an unexpected error

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#2632]
When the abort statement is placed inside the aborted section, it gives an error as below

`ballerina: unexpected error occurred`

This should be handled properly and a meaningful error message should be given to the user.

**Comment by hasithaa** [comment]
is your program like this. 
```
transaction {
 ...
} aborted {
 if(true){
   abort;
 }
}
```

If so, this validation should done at semantic analysis phase.
