### ISSUE TITLE
unused imports validation needs to be improved to bring in usability

### ISSUE THREAD

**Issue by shavantha** [ballerinalang/ballerina#2640]
unused imports validation needs to be improved to bring in usability

when we comment multiple lines of code within a function and start a ballerina service, ballerina does not allow to start the service until all the unused imports are removed. However, users are only informed one at a time and for a new user into Ballerina, it may take 3 to 4 attempts of starting the ballerina service until all unused imports are removed.

I suggest that details of all unused imports are listed in one go rather than one at a time this will help improve user friendliness.

**Comment by lankavitharana** [comment]
same issue is reported in https://github.com/ballerinalang/ballerina/issues/2286

**Comment by lafernando** [comment]
Fixed in master.
