### ISSUE TITLE
Remove deprecated typemapper implementation

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/ballerina#2648]
TypeMapper implementation is deprecated now and hence, must be deleted from the Grammar and core. The API documentation also includes a typemapper package that must be removed.

[1] http://ballerinalang.org/docs/api/0.8/ballerina.lang.typemappers.html

**Comment by tedneward** [comment]
TypeMappers are also mentioned in the documentation (in typesandvar.md), and there's typemappers defined in ballerina.lang.btype. If they are deprecated, these should all be removed.
