### ISSUE TITLE
"Failed to get json payload" error when invoking wrong http method

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/ballerina#2651]
```
import ballerina.net.http;
import ballerina.lang.messages;

@http:BasePath {value:"/hospital"}
service HospitalService {

    @http:POST {}
    @http:Path {value:"/reserve"}
    resource reserveAppointmentNew (message m) {
        json jsonRequest = messages:getJsonPayload(m);
        http:ClientConnector grandOaksEp = create http:ClientConnector("http://10.100.7.10:8080/grandoaks/categories/ent/reserve");
        m = http:ClientConnector.get(grandOaksEp, "/", m);
        json responseJson = messages:getJsonPayload(m);
        reply m;
    }
}
```

When invoking the above service, getting the following error. The error is not clear and has a Java exception class.

```
Running HospitalService.bal service.
ballerina: deploying service(s) in '/Users/maheeka/ESB_WORK/BALLERINA/HospitalService/wso2/hospital/sample/HospitalService.bal'
ballerina: started server connector http-9090
ballerina.lang.errors:Error, message: failed to get json payload: failed to create json: Unexpected character ('/' (code 47)): maybe a (non-standard) comment? (not recognized as one since Feature 'ALLOW_COMMENTS' not enabled for parser)
at [**Source: java.util.zip.GZIPInputStream@6ec23550**; line: 1, column: 2]
at getJsonPayload(<native>:0)
at HospitalService.reserveAppointmentNew(HospitalService.bal:14)
```

The error occurred when invoking the get method by mistake, where as the correct is a post method. Can we make the error more descriptive?

**Comment by anupama-pathirage** [comment]
Tested the below code with 0.95.0 release

```ballerina
import ballerina.net.http;

@http:configuration {basePath:"/hospital"}
service<http> HospitalService {

    @http:resourceConfig {
        methods:["POST"],
        path:"/reserve"
    }
    resource reserveAppointmentNew (http:Request req, http:Response res) {
                endpoint<http:HttpClient> grandOaksEp {
                        create http:HttpClient("http://10.100.7.10:8080/grandoaks/categories/ent/reserve", {});
        }
        json jsonRequest = req.getJsonPayload();
        http:Response clientResponse = {};
        clientResponse,_ = grandOaksEp.get("/", req);
        json responseJson = clientResponse.getJsonPayload();
        res.forward(clientResponse);
    }
}
```

When we execute GET for http://localhost:9090/hospital/reserve it gives below error.
`
Method not allowed
`'
So it seems the original issue is fixed.

But when we execute POST for the same url without json payload in the body it gives below error message which expose java netty transport level details in the error message. We need to fix that.

`
error, message: error while retrieving json payload from message: failed to create json: No content to map due to end-of-input
 at [Source: org.wso2.carbon.transport.http.netty.message.HttpMessageDataStreamer$ByteBufferInputStream@15e468d4; line: 1, column: 1]
	at ballerina.net.http:ballerina.net.http:Request.getJsonPayload(<native>:0)
	at .:HospitalService.reserveAppointmentNew(../samples/test3.bal:14)
`

**Comment by pubudu91** [comment]
Issue related to the new issue at hand: #3740

**Comment by pubudu91** [comment]
Since the issue @anupama-pathirage mentioned is not related to the original issue, I created a new issue (#4026) to track it. This issue can be closed.

**Comment by shafreenAnfar** [comment]
As per the above comment, I am closing the issue.
