### ISSUE TITLE
If a resource do not have a reply statement when you run the service you would get "ballerina: -1"

### ISSUE THREAD

**Issue by hevayo** [ballerinalang/ballerina#2654]
Checked on 0.88 release. Please try to run the following service. 

`package wso2.hospital.sample;`
`import ballerina.net.http;`

`service Service1 {`
`    @http:GET {}`
`    @http:Path { value: "/dest" }`
`    resource Resource1 (message m) {`
`    }`
`}`

It will give you "ballerina: -1" as the command output. Instead of -1 it will be helpful to get a meaningful error message.

**Comment by chanakaudaya** [comment]
cannot reproduced in the latest 0.92-SNAPSHOT version. Hence closing the issue.
