### ISSUE TITLE
[Debugger] Unsetting all debug points

### ISSUE THREAD

**Issue by Shan1024** [ballerinalang/ballerina#2672]
In IDEA, we can mute debug points. But currently there is no way to unset all of the debug points in the debug server. So IDEA continues to show debug hit since it continues to receive all the debug hits from the server. We might be able to do something like unsetting all debug points if there are no line details available in the request to fix this issue.

**Comment by lankavitharana** [comment]
fixed with pull https://github.com/ballerinalang/ballerina/pull/2883
