### ISSUE TITLE
Use of a multi-return function in a multi return statement results in an error

### ISSUE THREAD

**Issue by pubudu91** [ballerinalang/ballerina#2675]
The following code results in a `not enough arguments to return` error. 

```
function getInts() (int, int) {
    return 2, 3;
}

function functionCallInReturn() (int, int, int) {
    return getInts(), 5;
}
```

**Comment by sameera-jayasoma** [comment]
This is not an issue. This is the expected behavior.  You can't combine multi=return functions with other expressions.
