### ISSUE TITLE
Constants do not get initialized properly

### ISSUE THREAD

**Issue by sameera-jayasoma** [ballerinalang/ballerina#2702]
import ballerina.lang.system;
import ballerina.doc;

@doc:Description {value: "A const declaration can appear only as a top-level construct in Ballerina."}
const int PI = 3.14159;

function main (string[] args) {
    float circumference = 10.4;
    float diameter = circumference / PI;
    system:println("Diameter of the circle: " + diameter);
}

----------
error: ballerina.lang.errors:Error, message:  / by zero
	at main(constants.bal:9)

**Comment by lankavitharana** [comment]
Pull request merged, hence closing
