### ISSUE TITLE
Failed to execute Fork Join with http:ClientConnector

### ISSUE THREAD

**Issue by sashikamw** [ballerinalang/ballerina#2715]
Environment - Ballerina0.89 Snapshot (25/06/2017)

Issue - When invoking the given .bal file by defining the http client connector inside the service, fork-join function did not work.

[test.bal.zip](https://github.com/ballerinalang/ballerina/files/1102117/test.bal.zip)
Sample Payload to invoke the service - `<Customer><id>102</id></Customer>`

**Comment by lafernando** [comment]
This is fixed in v0.94. The above same sample will not work, due to other API changes.
