### ISSUE TITLE
Couldn't cast json string into json

### ISSUE THREAD

**Issue by tharindu1st** [ballerinalang/ballerina#2730]
json endpoint= {"count":1,"list":[{"id":"4c010346-b710-46cc-929e-2acf64468c7e","name":"endpoint1","endpointConfig":"{\"serviceUrl\":\"http://localhost\"}","security":"{\"enabled\":false,\"type\":null,\"username\":null,\"password\":null}","type":"http"}]};

get endpointConfig value

json endpointConfig = (json)endpoint.endpointConfig;
system:println(endpointConfig.serviceUrl);
error: ballerina.lang.errors:Error, message: cannot get value from 'serviceUrl': expected a 'json-object', but found 'string'

**Comment by SupunS** [comment]
Here you have defined the fields `endpointConfig` and `security` as string (within quotes). Hence it is treated as a string.

You need to define it without quotes to be treated as a JSON. Below is the correct way to define the JSON literal.

```
json endpoint= {"count":1,"list":[{"id":"4c010346-b710-46cc-929e-2acf64468c7e","name":"endpoint1","endpointConfig": {"serviceUrl":"http://localhost"},"security":{"enabled":false,"type":null,"username":null,"password":null} ,"type":"http"}]};
json endpointConfig = (json)endpoint.list[0].endpointConfig;
system:println(endpointConfig.serviceUrl);
```
