### ISSUE TITLE
Comments cannot be added within the service block

### ISSUE THREAD

**Issue by handakumbura** [ballerinalang/ballerina#2744]
Comments added to the service block fail with an unwanted token message at compile time.

```
@http:BasePath { value: "test"}
service Service1 {
//test
    @http:GET {}
    @http:Path { value: "/"}
    resource Resource1 (message m) {
        reply m;
    }
}
```

**Comment by SupunS** [comment]
This is the expected behavior. To add a description to a resource, need to use `doc:Description{}` annotation.
