### ISSUE TITLE
Cannot run a main when a service is in the same package

### ISSUE THREAD

**Issue by Shan1024** [ballerinalang/ballerina#2773]
```
org
 |- test
     |- main.bal
     |- service.bal
```
When we have a main in the main.bal and a service in the service.bal, when we run the main using `ballerina run main org/test` command, we get the following error.

```
server connector does not exist for the package 'ballerina.net.http'
```

**Comment by SupunS** [comment]
Fixed with commit https://github.com/ballerinalang/ballerina/commit/88719679aea8c9b561802beacc5d1b227af76147
