### ISSUE TITLE
Unsupported datatype error when inserting a year to YEAR sql type column

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#2795]
Add a year to the YEAR sql type column. The following error will be thrown

`unsupported datatype as parameter: year(4) index:4`

**Comment by anupama-pathirage** [comment]
SQL type is the column type mapping for a given parameter. Currently we are supporting below sql types which are standard sql types. Ideally any db specific column type should be mapped into any of the following types. YEAR is also a DB specific type where the value can be mapped into INTEGER or VARCHAR. It is not practical to add all DB specific types here as they can correctly map into standard types and those custom types may vary/expand. But there are some edge cases where some DB specific types does not map into any of the standard types like oracle ref cursors. Support for those  special types will be added in a future release.

- VARCHAR
- CHAR
- LONGVARCHAR
- NCHAR
- LONGNVARCHAR 
- NVARCHAR
- NUMERIC
- DECIMAL
- BIT
- BOOLEAN
- TINYINT
- SMALLINT 
- INTEGER
- BIGINT
- REAL
- FLOAT
- DOUBLE
- BINARY
- BLOB
- LONGVARBINARY
- VARBINARY
- CLOB
- NCLOB
- DATE 
- TIME
- DATETIME
- TIMESTAMP
- ARRAY
- STRUCT

**Comment by anupama-pathirage** [comment]
Example which successfully insert YEAR types is as follows.

SQL Table:
```ruby
CREATE TABLE TestTypes (
 id INT(6),
 yeartest YEAR
) 

```


```ruby
function testYearTypePara () (int count, string value) {

    map props = {"jdbcUrl":"jdbc:mysql://localhost:3306/testdb","username":"root", "password":"root"};
    sql:ClientConnector testDB = create sql:ClientConnector(props);

    sql:Parameter para1 = {sqlType:type, value:1, direction:0};
    sql:Parameter para2 = {sqlType:"integer", value:1980, direction:0}; //sqlType can be either varchar or integer

    sql:Parameter[] parameters = [para1,para2];
    count = sql:ClientConnector.update (testDB, "Insert into TestTypes (id, yeartest) values (?,?)", parameters);

    sql:Parameter[] emptyParam = [];
    datatable dt = sql:ClientConnector.select(testDB, "SELECT yeartest  from TestTypes where id = 187", emptyParam);
    testYear rs;
    while (datatables:hasNext(dt)) {
        any dataStruct = datatables:next(dt);
        rs, _ = (testYear)dataStruct;
        value = rs.yeartest;
        system:println("YEAR:" + value); //This will prints 1980-01-01+05:30
    }

    sql:ClientConnector.close (testDB);
    return;
}
```
