### ISSUE TITLE
Support for looping through JSON array

### ISSUE THREAD

**Issue by R-Rajkumar** [ballerinalang/ballerina#2811]
There is no way to loop through a JSON array at the moment.

**Comment by sameera-jayasoma** [comment]
Hi Raj,

This is a limitation in the current implementation.  But for the moment, you can use the following workaround until we fix this properly.

    // JSON array in an object literal.
    json p = {fname:"John", lname:"Stallone",
                 family:[{fname:"Peter", lname:"Stallone"},
                         {fname:"Emma", lname:"Stallone"},
                         {fname:"Jena", lname:"Stallone"},
                         {fname:"Paul", lname:"Stallone"}]};
    p.family[2].fname = "Alisha";
    system:println(p);

    int i = 0;
    try {
        json family = p.family;
        while (true) {
            json e = family[i];
            system:println(e);
            i = i + 1;
        }
    } catch (errors:Error e) {
        string msg = e.msg;
        if (!strings:contains(msg, "array index out of range")) {
            system:println(msg);
            throw e;
        } else {
            system:println("length of array: " + i);
            // Ignore the error.
        }
    }

**Comment by a5anka** [comment]
Another option is getting the json array length and iterate using that number
```
// JSON array in an object literal.
json p = {fname:"John", lname:"Stallone",
             family:[{fname:"Peter", lname:"Stallone"},
                     {fname:"Emma", lname:"Stallone"},
                     {fname:"Jena", lname:"Stallone"},
                     {fname:"Paul", lname:"Stallone"}]};


int arrayLength = jsons:getInt(p, "$.family.length()");
int i = 0;

json family = p.family;
while (i < arrayLength) {
    json e = family[i];
    system:println(e);
    i = i + 1;
}
```

**Comment by SupunS** [comment]
Supported in the release v0.90
```java
json j = [7,8,9];
int l = lengthof j;
system:println("length of array: " + l);

int i = 0;
while (i < l) {
    system:println(j[i]);
    i = i + 1;
}
```
