### ISSUE TITLE
Cannot check if a query param is null

### ISSUE THREAD

**Issue by a5anka** [ballerinalang/ballerina#2820]
Following code throw an error when the query param is not provided.

```
import ballerina.net.http;
import ballerina.lang.messages;
import ballerina.lang.jsons;
import ballerina.lang.errors;

@http:config { basePath: "/myecho"}
service<http> myEchoService {

    @http:POST {}
    resource myEchoResource (message m, @http:QueryParam {value:"q"} string query) {
        if (query == null) {
            query = "default";
        }

        message response = {};
        reply response;
    }
}
```

The error message is

```
invalid operation: incompatible types 'string' and 'null'
```

**Comment by SupunS** [comment]
string is a value type, hence the zero-value for a string variable is the empty string (""), but not null.
So you can check for an empty string to validate the query parameter.
 ```
if (query == "") {
    query = "default";
}
```

**Comment by christian-morin** [comment]
Hi,

no, this isn't working. If there's no value specified in query the error message is (when checking for ""):
`ballerina.lang.errors:Error, message: unknown error occurred`

Also, I would assume the value "q" should be the default value for the parameter if it isn't supplied? But this doesn't seem to be working either as the parameter is 'null' if no value is provided from the request.
