### ISSUE TITLE
[Logging] Have to map java.util.logging.Level instead of the Ballerina log API in the logging.properties

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#2834]
**Issues**
1. Have to map java.util.logging.Level instead of the levels supported from the Ballerina log API in the logging.properties which is wrong

eg: org.ballerinalang.logging.handlers.DefaultLogFileHandler.level=FINE/FINER

2. Need to add an additional attribute for the above to work
.level=FINE

**Comment by pubudu91** [comment]
This was fixed with PR #3896

**Comment by anupama-pathirage** [comment]
Fixed with #3896
