### ISSUE TITLE
Ballerina composer doesn't render "var" keyword properly

### ISSUE THREAD

**Issue by amalhub** [ballerinalang/ballerina#2837]
https://github.com/ballerinalang/ballerina/blob/ballerina-by-example-src/samples/ballerina-by-example/examples/sql-connector/sql-connector.bal#L54

in Ballerina latest release 0.89

Type below code in source view
     **var jsonRes,err = <json>dt;**
Go back to UI view and click on that element, then go back to source view.
The line has changed to 
     **jsonRes,err = <json>dt;**

**Comment by hevayo** [comment]
Issue moved to composer repo see #2666
