### ISSUE TITLE
Format json/struct/map toString() output.

### ISSUE THREAD

**Issue by sameera-jayasoma** [ballerinalang/ballerina#2845]
Consider the following program. It prints this.
{id:5,name:"sameera"}

It should be properly formatted to:
{id:5, name:"sameera"}

Space was missing in origin output.
-----------------------------
import ballerina.lang.system;
function main(string[] args) {
        Person p = {};
        system:println(p);
        system:println(j);
}

struct Person {
        int id = 5;
        string name= "sameera";
}

**Comment by SupunS** [comment]
PR #2852 will improve the output for structs, maps and arrays. However, JSON string representation is handled by the underlying Jackson library, hence it is out of our control.
