### ISSUE TITLE
No error is thrown for annotation repetition in services

### ISSUE THREAD

**Issue by chamil321** [ballerinalang/ballerina#2871]
@http:POST{}
    @http:Path{value:"/test1"}
    @http:Path{value:"/test2"}
    resource echo (message m) {
    	//...........
    }

Currently we don't get any error for same annotation repetition. This should be handled at semantic level.

**Comment by dilinisg** [comment]
Same behaviour when the http server connector configs are repeated. Need a meaningful error message.

**Case 1:** The whole @http:config {} is duplicated
**Case 2:** When one of the properties in the @http:config {} is repeated.

@http:config {
    basePath:"/counter",
    **scheme:"https",
    scheme:"http",**
    port:8678,
    host:"is.wso2.com"
}
