### ISSUE TITLE
Garbage values are returned for errors

### ISSUE THREAD

**Issue by SupunS** [ballerinalang/ballerina#2887]
eg:
```
import ballerina.lang.errors;

function testJsonToJsonArrayCasting() (json[], errors:TypeCastError){
    json j1 = [[7]];
    var j2, e = (json[]) j1;
    
    return j2, e;
}
```
Here the value returned for 'e' is 7. It should be null, since there are no runtime errors.

**Comment by SupunS** [comment]
This garbage-value issue for this particular scenario is fixed with #2888.

However, we need to check for other places where this could occur and fix them as well.

**Comment by erandidesilva** [comment]
This issue occurs in the following instance

**Sample code**
```
function getAllAttributesWithDifferentNamespacePrefixes(xml value)(string attributeValue, errors:TypeCastError error){
    xmlns "http://example.com/ServiceName/sample/test" as ns0;
    xml firstLevelChildren = xmls:children(value);
    xml specificChild = xmls:select(firstLevelChildren, "{http://example.com/ServiceName}CNTROLAREA");
    xml secondLevelSpecificChild = xmls:selectChildren(specificChild, "{http://example.com/ServiceName/sample/test}DATETIME");
    map attributes = <map> secondLevelSpecificChild@;
    attributeValue, error = (string)attributes[ns0:qualifier];
    system:println(attributeValue);
    return;
}
```

Here attributeValue is returned, hence error should be null.

**Comment by erandidesilva** [comment]
Another sample incident

`
var firstname, err = (string)dataset.batchOne[i].firstname;
`

**Comment by SupunS** [comment]
Checked all scenarios in v0.94.0. Seems they are all fixed. Hence closing the issue.

**Comment by sameera-jayasoma** [comment]
I am reopening this issue. I can see this behaviour with 0.95.0 as well. 

function main (string[] args) {
    json j1 = "Apple";
    var s,err = (string)j1;
    if(err != null) {
        println( err);
    }
    println(s);
}
