### ISSUE TITLE
Error While Retrieving a Property from Mesaage

### ISSUE THREAD

**Issue by sambaheerathan** [ballerinalang/ballerina#2900]
In Ballerina 0.89 When I'm trying to retrieve the property **RESOURCE_ARGS** using the following code
`any obj = messages:getProperty(m,"RESOURCE_ARGS");`

But I'm getting the following error
ballerina.lang.errors:Error, message: property value is of unknown type : java.util.HashMap

**Comment by shafreenAnfar** [comment]
This is actually an internal property and not really expected to use by the ballerina user. As a matter of fact, we are planning to remove getProperty function from the request/response structs. 

All the necessary values are included as fields of the request/response structs. Hence, I am closing this issue as the need has been addressed in the latest released version.
