### ISSUE TITLE
Boolean query-parameter not working

### ISSUE THREAD

**Issue by christian-morin** [ballerinalang/ballerina#2907]
Trying to create an API resource with a boolean query paramater

`resource resource1 (message m, string id, boolean includeDepartures)`

When invoking the resource with includeDepartures=true, I get this error:

`Unsupported parameter type for parameter true`

**Comment by chamil321** [comment]
Tested scenarios regarding this issue and it is well fixed.

**Comment by shafreenAnfar** [comment]
Closing the issue as it has been fixed.
