### ISSUE TITLE
Provide a method to remove elements or attributes from a given xml payload

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#2910]
Currently there is no method to remove an element or an attribute from a given xml payload. It's an essential part in message transformation.

**Function to remove element/elements**
Since the xml sequence is immutable, we can ask the developer to select the children that needs to be removed, and then create a new sequence without the specified children using a function. There can be some orphaned namespaces in this case.

**Function to remove attribute/s**
This is to remove attributes as specified.

**Comment by SupunS** [comment]
Removing attributes from an XML is supported with v0.94.1.
Following is the sample API:
```ballerina
x.removeAttribute("foo");
```

**Comment by SupunS** [comment]
Created a separate issue to track remove() function: https://github.com/ballerinalang/ballerina/issues/4149
Thus closing this issue

**Comment by SupunS** [comment]
Created a separate issue to track remove() function: https://github.com/ballerinalang/ballerina/issues/4149
Thus closing this issue
