### ISSUE TITLE
 The user hasn't authorized

### ISSUE THREAD

**Issue by gihan1994** [ballerinalang/ballerina#2913]
# {"error":{"message":"(#200) The user hasn't authorized the application to perform this action","type":"OAuthException","code":200,"fbtrace_id":"F2+nGYsbU2v"}}

When I try to access Facebook API through the Facebook Connector in Ballerina. this error will occur.
what is happen? How can this error be fixed?

**Comment by anupama-pathirage** [comment]
Created https://github.com/ballerinalang/connectors/issues/190 to track this. Hence closing this in ballerina repo
