### ISSUE TITLE
Copy "configuration" service annotation to ballerina.net.ws package as well

### ISSUE THREAD

**Issue by lankavitharana** [ballerinalang/ballerina#2918]
In PR [1], it will add "configuration" annotation [2] to ballerina.net.http package. As explained in the PR description, we have to add ```service<ws>``` attachment point. Hence comes a import package ballerina.net.ws.

But it seems like a cyclic dependency (ballerina.net.http to ballerina.net.ws and wise versa) hence it is better to simply copy a configuration annotation to ballerina.net.ws and use it. So once web socket will have it's own Dispatcher and registry, copy "configuration" annotation to ballerina.net.ws package

[1] - https://github.com/ballerinalang/ballerina/pull/2912
[2] - annotation configuration attach service<>, ```service<ws>``` {
    string host;
    int port;
    int httpsPort;
    string basePath;
    string keyStoreFile;
    string keyStorePass;
    string certPass;
}

**Comment by irunika** [comment]
This is done in v0.94 release.
