### ISSUE TITLE
When there is no error, a wrong value is printed

### ISSUE THREAD

**Issue by muthulee** [ballerinalang/ballerina#2919]
import ballerina.lang.system;

struct person {
    string fname;
    string lname;
    int age;
}

struct movie {
    string title;
    string year;
    string released;
    person writer;
}

function main (string[] args) {
    json inceptionJ = {title:"Mr",
                      year:"2010",
                      released:"16 Jul 2010",
                      writer:{fname:"Christopher",
                             lname:"Nolan", age:30}};
    var inception, err = <movie>inceptionJ;
    system:println(err);
    system:println(inception);
}

The output is,
Running help1.bal application.
2010
{title:"Mr",year:"2010",released:"16 Jul 2010",writer:{fname:"Christopher",lname:"Nolan",age:30}}
Execution Ended.

Version: Nightly build of 16th July.

**Comment by maheeka** [comment]
Observed the same and when conversion is success, cannot handle errors because `if (err != null) `check fails.

**Comment by SupunS** [comment]
This is the same issue as in https://github.com/ballerinalang/ballerina/issues/2887. Hence closing this and the issue will be tracked at https://github.com/ballerinalang/ballerina/issues/2887.
