### ISSUE TITLE
IS there a way to get all the Headers from Message ?

### ISSUE THREAD

**Issue by sambaheerathan** [ballerinalang/ballerina#2931]
At the moment we can get only one header by invoking 
`messages:getHeader()`
Do we have any other function which returns all the headers in the incoming request?

**Comment by chamil321** [comment]
Using headers map of req/resp, all headers can be retrieved. Hence please close the issue.

**Comment by shafreenAnfar** [comment]
As per the above comment. I am closing this issue.
