### ISSUE TITLE
Checkstyle execution error during the build - result in build failure

### ISSUE THREAD

**Issue by chintana** [ballerinalang/ballerina#2970]
master build is throwing up following checkstyle error when building,

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project ballerina-native: Failed during checkstyle execution: There are 8 errors reported by Checkstyle 6.11.2 with https://raw.githubusercontent.com/wso2/code-quality-tools/master/checkstyle/checkstyle.xml ruleset. -> [Help 1]

Easy to skip using -Dcheckstyle.skip though and build is successful

**Comment by SupunS** [comment]
Fixed in master branch
