### ISSUE TITLE
Unclear error message when number of arguments for functions are different

### ISSUE THREAD

**Issue by Shan1024** [ballerinalang/ballerina#3006]
```
messages:getStringPayload(response, "Hello World !!!");
```

The above line returns the below message which makes understanding the real issue harder since there is a **getStringPayload** function in the **messages** package. The actual error is the difference in number of arguments.

```
service.bal:11: undefined function 'messages:getStringPayload'
```

**Comment by SupunS** [comment]
This is fixed in v0.93.1-SNAPHOT.
```
string payload = req.getStringPayload("hello");
```

Above will give the following error:
```
error: testSample.bal:15:26: too many arguments in call to 'getStringPayload()'
compilation contains errors
```
