### ISSUE TITLE
mysql connector gives an Error about a driver

### ISSUE THREAD

**Issue by shalithasuranga** [ballerinalang/ballerina#3007]
Following code block gives an error message

ballerina.lang.errors:Error, message: error in sql connector configuration: No suitable driver
        at ballerina.data.sql:ClientConnector.<init>(<native>:0)

Code block

```
      map props = {"jdbcUrl":"jdbc:mysql://localhost:3306/socialboxlite",
                  "username":"root", "password":""};
  sql:ClientConnector testDB = create
                               sql:ClientConnector(props);
```

**Comment by anupama-pathirage** [comment]
You need to copy the MySQL jdbc driver to the lib folder. Can you please follow the steps below and check whether this solve your problem?

1) Download the mysql-connector-java-*.zip from [1].
2) Extract the zip and copy the mysql-connector-java-*-bin.jar file to BALLEIRNA_HOME/bre/lib directory.n.


[1] https://dev.mysql.com/downloads/connector/j/
