### ISSUE TITLE
No building mechanism in Ballerina 0.90

### ISSUE THREAD

**Issue by myasas** [ballerinalang/ballerina#3008]
When tried to run : 
`ballerina build main hello-world-parellel.bal`
it returns following error,

> ballerina: unknown command 'build'
> Run 'ballerina help' for usage.

when ran `ballerina help `

> Available Commands:
>   run        compile and run Ballerina program
>   docker     create docker images for Ballerina program archives
>   doc        generate Ballerina API documentation
>   swagger    Generate connector/service using swagger definition
>   test       test Ballerina program
>   version    print Ballerina version

In ballerina version 0.89 it was like following

> Usage:
>   ballerina [command] [options]
> 
> Available Commands:
>   run        run Ballerina main/service programs
>   build      create Ballerina program archives
>   docker     create docker images for Ballerina program archives
>   doc        generate Ballerina API documentation
>   swagger    Generate connector/service using swagger definition
>   test       test Ballerina program
>   version    print Ballerina version

Hope this will get fixed so that we can build archives and deploy in places such as wso2 integration cloud.
Thanks !

**Comment by SupunS** [comment]
Available in 0.91 onwards

**Comment by ydesilva** [comment]
Sure. Thank you !
Was about to close the issue.
