### ISSUE TITLE
Ballerina by example - could use a topic on "HTTP Client Connector"

### ISSUE THREAD

**Issue by jonathan-marsh** [ballerinalang/ballerina#3009]
There are examples embedded within other topics, but a simple top-level topic and an example of how to do GET/POST would be helpful.  First real example everyone will want to try is pinging some web site/service or other...

**Comment by anupama-pathirage** [comment]
Added the sample in [1] 

[1] https://ballerinalang.org/docs/by-example/http-client-connector
