### ISSUE TITLE
Getting net_write_timeout but mysql server is working properly

### ISSUE THREAD

**Issue by shalithasuranga** [ballerinalang/ballerina#3018]
I got this error while working with mysql connector

ballerina.lang.errors:Error, message: error occurred during writing the message to the output stream: Application was streaming results when the connection failed. Consider raising value of 'net_write_timeout' on the server.

insert type queries are working but select queries give this error

**Comment by shalithasuranga** [comment]
When I remove  messages:setJsonPayload (response, jsonRes); this line There are no errors.

**Comment by anupama-pathirage** [comment]
Hi, 
Can you please share the ballerina code sample which gives the mentioned error.

**Comment by shalithasuranga** [comment]
```
	resource loadTwitterSettings (message m) {
      map props = {"jdbcUrl":"jdbc:mysql://localhost:3306/socialboxlite?autoReconnect=false&useSSL=false", "username":"root", "password":""};
      sql:ClientConnector testDB = create sql:ClientConnector(props);
      sql:Parameter para = {sqlType:"varchar", value:"twittersettings"};
      sql:Parameter[]  params = [];
      params =[para];
      datatable dt = sql:ClientConnector.select(testDB,"SELECT * FROM sl_settings WHERE set_key=?",params);
      var jsonRes, err = <json>dt;
      sql:ClientConnector.close(testDB);
      message response = {};

      messages:setJsonPayload (response, jsonRes);

        messages:setHeader (response, "Content-Type","application/json");
        reply response;

    }

```

I am also getting json string from mysql database

**Comment by anupama-pathirage** [comment]
Can you please check after removing  sql:ClientConnector.close(testDB); here. SQL connection should be open at the time of json payload being read at the client side since we are using streamed json here

**Comment by shalithasuranga** [comment]
Further I was unable to define variable for database inside service tag. please check attached bal file

[ballerina.zip](https://github.com/ballerinalang/ballerina/files/1167315/ballerina.zip)
