### ISSUE TITLE
[Team VCoDes] Java Error : java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by DhanuKuma** [ballerinalang/ballerina#3019]
In FTP Server Connector, When moving file into another directory it throws below exception after function is done. 

> import ballerina.net.ftp;
import ballerina.lang.messages;
import ballerina.lang.files;
import ballerina.lang.blobs;
import ballerina.lang.strings;
import ballerina.lang.system;

@ftp:configuration {
    dirURI:"ftp://dhanu:123@127.0.0.1:11/Upload",
    pollingInterval:"20000",
    actionAfterProcess:"MOVE",
    moveAfterProcess:"ftp://dhanu:123@127.0.0.1:11/Upload",
    parallel:"false",
    createMoveDir:"true"
}
service<ftp> ftpServerConnector {
    resource fileResource (message m) {
        files:File fileDelete = {path:"ftp://dhanu:123@127.0.0.1:11/Upload/Test.txt"};
        //files:File fileDelete = {path:"E:\\BallerinaPath\\Upload\\Test.txt"};
        ftp:ClientConnector c = create ftp:ClientConnector();

        string url = messages:getStringPayload(m);
        files:File file = {path:url};
        blob txt = ftp:ClientConnector.read(c, file);
        string content = blobs:toString(txt, "UTF-8");
        system:println("Content of the file at: " + url);
        system:println(content);
        content = content;
        blob output = strings:toBlob(content, "UTF-8");
        files:File target = {path:
                             "ftp://dhanu:123@127.0.0.1:11/Download/Test.txt"};
        ftp:ClientConnector.write(c, output, target);

        //delete file in the upload folder
        ftp:ClientConnector.delete(c, fileDelete);
        system:println("file deleted");

        reply m;
    }
}

![javaerror](https://user-images.githubusercontent.com/15075191/28490018-3e6116b8-6eee-11e7-81ee-3ac978738770.PNG)

**Comment by anupama-pathirage** [comment]
Created https://github.com/ballerinalang/connector-file/issues/10 to track this
