### ISSUE TITLE
HTTP Service Invocation fails

### ISSUE THREAD

**Issue by Lasanda** [ballerinalang/ballerina#3020]
package src;

import ballerina.net.http;
import ballerina.lang.messages;
import ballerina.data.sql;
import ballerina.lang.system;

@http:configuration {basePath:"/Ads"}
service<http> syncAdService {
map props = {"jdbcUrl":"jdbc:mysql://localhost:3306/push_ads",
                "username":"root", "password":"lrllmlrp"};

sql:ClientConnector sqlConnector=create sql:ClientConnector(props);

    @http:GET {}
    @http:Path {value:"/sync"}
    resource sayHello (message m,string lat,string lng) {
        http:ClientConnector googleMapsCon= create http:ClientConnector("http://maps.googleapis.com");
        message response = {};
        message tempMessage = {};
        message holdMsg = {};
        system:println("go 1");
        holdMsg = http:ClientConnector.get(googleMapsCon,"/maps/api/geocode/json?latlng="+lat+","+lng+"&sensor=false",tempMessage);
        system:println("go 2");
        json mapLocationList= messages:getJsonPayload(response);
        json adImg ={};
        messages:setJsonPayload(response, mapLocationList);
        reply response;
    }
}

Throws :-
ballerina: deploying service(s) in 'src'
ballerina: internal error occurred

**Comment by chanakaudaya** [comment]
Issue you are facing is due to missing jdbc driver when using the SQL connector. Please download the driver and put that under bre/lib directory. We will address the error message in a future release.
