### ISSUE TITLE
[Improvement] Using struct for SQL queries to achieve simplicity

### ISSUE THREAD

**Issue by saadsahibjan** [ballerinalang/ballerina#3021]
Below is a sample code for SQL insert operation

```
json payload = messages:getJsonPayload(m);
int mobile = jsons:getInt(payload, "$.mobileNo");
string categoryId = jsons:getString(payload, "$.catId");
float time = jsons:getFloat(payload, "$.timeFrequency");
sql:Parameter mobileNo = {sqlType:"integer",value:mobile};
sql:Parameter catId = {sqlType:"varchar",value:categoryId};
sql:Parameter timeFrequency = {sqlType:"float",value:time};
sql:Parameter[] params = [mobileNo, catId, timeFrequency];
string query = "Insert into frequency values (?,?,?)";
map dbProperties = {"jdbcUrl":"jdbc:mysql://localhost:3306/oxygeon","username":"root","password":""};
sql:ClientConnector dbConnector = create sql:ClientConnector(dbProperties);
try {
    sql:ClientConnector.update(dbConnector, query, params);
} catch(errors:Error er) {
	throw er;
}
sql:ClientConnector.close(dbConnector);
```

As per the above code each of the field is assigned to a variable of its type and then assigned to sql:Paramter individually, afterwards its been assigned to a Parameter array and then it is been used to insert.
But this same thing can be achieved through the use of struct which will act as model. Once the json payload comes in, it can be mapped to the struct and then that relevant struct can be used for insertion directly. It also can be used for update and delete as well. And the needed objective can be achieved with less number of lines of code.

**Comment by anupama-pathirage** [comment]
duplicate on #4436
