### ISSUE TITLE
[Blocker] JMS receiver is not working

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#3023]
Release 0.9
Run the JMS receiver with WSO2 MB

**Steps**
1. Copy the client libs
2. Configure the jndi properties
3. Start the MB
4. Run the sample

![jms](https://user-images.githubusercontent.com/1845370/28490169-c04b69d8-6ef0-11e7-800b-171be7657d9c.png)

**Comment by SupunS** [comment]
created issue https://github.com/ballerinalang/connector-jms/issues/15 in the jms-connector repo.
