### ISSUE TITLE
[VCoDeS] - Windows: File System Server Connector

### ISSUE THREAD

**Issue by virani89** [ballerinalang/ballerina#3024]
actionAfterProcess:"NONE" works fine for windows but MOVE and DELETE doesn't work properly. May be because of the path, not as in the LINUX environment.

![capture](https://user-images.githubusercontent.com/16720748/28490276-aaaa8840-6ef3-11e7-83a3-34f3630a001f.PNG)

**Comment by anupama-pathirage** [comment]
Created https://github.com/ballerinalang/connector-file/issues/8 to track this
