### ISSUE TITLE
[VCoDeS] Windows: file system server connector 

### ISSUE THREAD

**Issue by cpachamila87** [ballerinalang/ballerina#3025]
![2017-07-22](https://user-images.githubusercontent.com/29550919/28490275-9bc5bc78-6ef3-11e7-9a8f-863642132963.png)

additional backslash added in to the file path when retrieving the file path using messages:getStringPayload(m) in file api

**Comment by anupama-pathirage** [comment]
Created https://github.com/ballerinalang/connector-file/issues/7 to track this
