### ISSUE TITLE
SQL Error in runtime

### ISSUE THREAD

**Issue by Lasanda** [ballerinalang/ballerina#3031]
package src;

import ballerina.net.http;
import ballerina.lang.messages;
import ballerina.data.sql;
import ballerina.lang.jsons;

@http:configuration {basePath:"/Ads"}
service<http> syncAdService {
map props = {"jdbcUrl":"jdbc:mysql://localhost:3306/push_ads",
                "username":"root", "password":"lrllmlrp"};

sql:ClientConnector sqlConnector=create sql:ClientConnector(props);

    @http:GET {}
    @http:Path {value:"/sync"}
    resource sayHello (message m,string lat,string lng) {
        http:ClientConnector googleMapsCon= create http:ClientConnector("http://maps.googleapis.com");
        message response = {};
        message tempMessage = {};
        message holdMsg = {};
        holdMsg = http:ClientConnector.get(googleMapsCon,"/maps/api/geocode/json?latlng="+lat+","+lng+"&sensor=false",tempMessage);
        json mapLocationList= messages:getJsonPayload(holdMsg);

        json area=mapLocationList.results[0].address_components[2].long_name;
        string theArea= jsons:toString(area);

        json adImg ={};
        sql:Parameter[] params={};
        datatable dt=sql:ClientConnector.select(sqlConnector,"select * from users",params);
        adImg,_= <json>dt;

        messages:setJsonPayload(response, adImg);
        reply response;
    }

}

Log : 
ballerina: deploying service(s) in 'src'
ballerina: started server connector http-9090
ballerina.lang.errors:Error, message: org.ballerinalang.model.values.BJSON cannot be cast to org.ballerinalang.model.values.BRefValueArray
	at ballerina.data.sql:ClientConnector.select(<native>:0)
	at src:syncAdService.sayHello(src\syncAds.bal:31)

**Comment by lankavitharana** [comment]
sql:Parameter[] params={};

This is invalid initialization, but I think it would be better if we can validate this at semantic phase

**Comment by hasithaa** [comment]
correct syntax is  sql:Parameter[] params = [];
