### ISSUE TITLE
Can not set a relative file path in the File API

### ISSUE THREAD

**Issue by Anjeyster** [ballerinalang/ballerina#3035]
https://ballerinalang.org/docs/by-example/file-api

Unable to set a relative file path. 

I wanted to read a html file in my views directory and send its contents as a response.

Unable to give a relative path of the file

-Team ZentiNext at Ballerina Hackathon

**Comment by SupunS** [comment]
Tested with v0.91 and the relatives paths works. The path should be relative to the location you are executing the 'run' command.
