### ISSUE TITLE
Cannot pass a function that returns values as an input parameter for a function. 

### ISSUE THREAD

**Issue by NilakshaPerera** [ballerinalang/ballerina#3043]
![untitled](https://user-images.githubusercontent.com/23151040/28491164-c409095e-6f09-11e7-84b5-5331aa1084f1.png)

Upper scenario does not show any syntax errors in the composer. The  code wont run and it wont show any compilation errors as well.

**Comment by SupunS** [comment]
Fixed in v0.93.1-SNAPSHOT
