### ISSUE TITLE
Restricting an annotation definition to be used as an annotation attribute value only.

### ISSUE THREAD

**Issue by hemikak** [ballerinalang/ballerina#3046]
Hi All,

As of now, an annotation definition can be restricted to be attached to either of the following as per the grammer file, 

     : 'service'
     | 'resource'
     | 'connector'
     | 'action'
     | 'function'
     | 'typemapper'
     | 'struct'
     | 'const'
     | 'parameter'
     | 'annotation'

But taking the swagger definition .bal file[1] as an example, we can see that the 'Contact' annotation can be attached to any of the above definitions as the 'attach' keyword is not being used.

But the requirement is that the 'Contact' annotation should only be allowed to used as an annotation attribute in the 'ServiceInfo' annotation definition : 

annotation ServiceInfo attach service {
	...
	Contact contact;
	...
}

[1] - https://github.com/ballerinalang/ballerina/blob/master/modules/ballerina-native/src/main/ballerina/ballerina/net/http/swagger/annotation.bal

**Comment by lafernando** [comment]
This scenario will not be that practical, thus, closing the issue.
