### ISSUE TITLE
"redeclared symbol error" occurs when same function name, but different parameters in same package

### ISSUE THREAD

**Issue by hjchanna** [ballerinalang/ballerina#3056]
When creating functions with same name and different parameters in same package breaks ballerina run with error "redeclared symbol error". Look at following example.

**Test1.bal**

```
package my_package;

function myFunction(boolean b){
      //relevant code goes here
}
```

**Test2.bal**

```
package my_package;

function myFunction(string b){
      //relevant code goes here
}
```
this will break run with error "_redeclared symbol 'myFunction'_"

**Comment by SupunS** [comment]
Function overloading is not supported in ballerina. Therefore this is the expected behaviour.
