### ISSUE TITLE
[Suggestion] - sql:Parameter sqlType is prone to typos

### ISSUE THREAD

**Issue by Ruchiram4** [ballerinalang/ballerina#3058]
If you consider the sample code [here](https://ballerinalang.org/docs/by-example/sql-connector), you see that the end user would have to manually type in the **sqlType** value when using a sqlParameter.

My suggestion is to use some level of public string constants so that there is lesser probability for a user to incorrectly type in a value. If so, the code will not compile until you're using a correct value.

**Comment by lafernando** [comment]
Related to https://github.com/ballerinalang/ballerina/issues/4100.
