### ISSUE TITLE
struct to json conversion should not be unsafe

### ISSUE THREAD

**Issue by hjchanna** [ballerinalang/ballerina#3061]
According to the ballerina documentation it says struct to json conversion is always safe, and it should be. (see documentation: https://ballerinalang.org/docs/by-example/json-struct-map-conversion). But it fails to run without multi-return conversion expression. Please go through following example.

```
import ballerina.lang.system;

struct Strings {
    string[] strings;
}

function main (string[] args) {
    Strings strings = {
                          strings:["String 1", "String 2"]
                      };

    var stringsJson = <json>strings;

    system:println(stringsJson);
}
```
The output as follows.
```
Test.bal:12: unsafe conversion from 'Strings' to 'json', use multi-return conversion expression
```

**Comment by SupunS** [comment]
Structs can contain types that are not supported in JSON such as connectors, 'message' type fields, etc. Hence struct to JSON is an unsafe conversion. 

We need to update the doc.

**Comment by SupunS** [comment]
Docs are updated with PR https://github.com/ballerinalang/ballerina/pull/3070.
Hence closing the issue.
