### ISSUE TITLE
Internal error occurred when sql connector was created inside service in 0.91

### ISSUE THREAD

**Issue by arunans23** [ballerinalang/ballerina#3065]
I developed a system in ballerina 0.89 where I instantiate the SQL connector inside the ballerina service. Recently I migrated my sdk to ballerina 0.91. After that my code broke and now there is an error like below.

> ballerina: deploying service(s) in '/home/arunans23/Documents/ballerina-tools-0.91/samples/myWorks/databaseAccess/databaseAccess.bal'
ballerina: internal error occurred

I found out that the error goes away when I create the SQL connector inside the resource and not inside the service.

Note : The code successfully builds. The error occurs only when I try to run it.

**Comment by anupama-pathirage** [comment]
Here is a sample SQL connector code where SQL connector is defined in Service level (Tested in balerina 0.91)

```java 
import ballerina.net.http;
import ballerina.data.sql;
import ballerina.lang.messages;

@http:configuration{basePath:"/getIndexNo"}
service<http> getIndexNoService {

        map dbProperties = {"jdbcUrl":"jdbc:mysql://localhost:3306/testdb","username":"root","password":"root"};
        sql:ClientConnector dbConnector = create sql:ClientConnector(dbProperties);

        @http:GET{}
        @http:Path {value:"/getData"}
        resource insertFrequency(message m) {

                sql:Parameter[] parameters = [];
                datatable dt = sql:ClientConnector.select (dbConnector, "SELECT  name from Customers", parameters);
                var jsonRes, _ = <json> dt;
                message response = {};
                messages:setJsonPayload (response, jsonRes);
                reply response;
        }
}
```
It is deployed successfully and working fine for http GET requests as follows 

```ruby
anupama@anupama:~/Release/0.91/ballerina-tools-0.91/bin$ ./ballerina run ../samples/databaseAccess.bal 
ballerina: deploying service(s) in '../samples/databaseAccess.bal'
ballerina: started server connector http-9090
```
Can you please check the given sample and see what is the difference with your code. 
Please make sure you have followed the below steps before running the code.

1) Download the mysql-connector-java-*.zip from [1].
2) Extract the zip and copy the mysql-connector-java-*-bin.jar file to BALLEIRNA_HOME/bre/lib directory.

If the error still occurs please share your sample code which gives the error. 

[1] https://dev.mysql.com/downloads/connector/j/

**Comment by arunans23** [comment]
I understand my mistake now. I did not install the sql connector inside the ballerina 0.91 folder. In earlier versions it used to show as "no driver found". But now it shows as Internal Error. So couldn't figure it out earlier.

Thanks for pointing it out. 

I hope this issues serves as a lesson for anyone looking for an answer.
