### ISSUE TITLE
Worker Message Parsing Not Working With Conditional Operations

### ISSUE THREAD

**Issue by lafernando** [ballerinalang/ballerina#3111]
Ballerina 0.91.

The following Ballerina program fails:-

```
import ballerina.lang.system;

function main(string[] args) {
    int x = 5;

    x -> w1;
    x <- w1;

    system:println(x);

    worker w1 {
        int x;
        x <- default;
        x = x + 1;
        if (x == 1) {
            x -> default;
        } else {
            x -> default;
        }
    }
}
```

**Comment by hasithaa** [comment]
@lafernando . Following line doesn't work with graphically. So worker send and receive should be defined as top-level statements of the worker.  

if (x == 1) {
            x -> default;
        } else {
            x -> default;
        }
