### ISSUE TITLE
Include Charset in the response Content-Type header

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#3116]
Currently Ballerina returns the Content-Type without the charset defined. Ideally the Content-Type header should contain the charset to meet the standards

**Ballerina response**
`content-type →application/json`

**ESB response**
`content-type →application/json; charset=UTF-8`

**Comment by shafreenAnfar** [comment]
Closing this issue as it has been captured using the below issue.

https://github.com/ballerinalang/ballerina/issues/3750
