### ISSUE TITLE
Automatic redirection happens at 301, 302, 303 and 307 when Ballerina is acting as the server

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#3118]
When a Ballerina service is the server, any resource move should be indicated by 3xx codes. 

As an example with 301, when the location header is present, automatic redirection to specified url happens which is wrong is when ballerina itself is the server (without any other backends)

**Expected behaviour: quoted from [1]** 
The server SHOULD generate a Location header field in the response
   containing a preferred URI reference for the new permanent URI.  The
   user agent MAY use the Location field value for automatic
   redirection

[1] https://tools.ietf.org/html/rfc7231#section-7.2

**Comment by arukshani** [comment]
Can I please know how this was tested. It is the client who does the redirection. So if the ballerina server returns 307 with a redirect URL in the Location header as the response, and if the client who calls the ballerina server does the automatic redirection, then that is not an error. For example, if you call the ballerina server through a browser or postman, when they get the 3XX response they do the automatic redirection. To test this you have to use curl. Automatic redirect is off by default in curl.

**Comment by erandidesilva** [comment]
@arukshani 
This was tested with a resource as following.
```
  @http:resourceConfig {
        methods:["POST", "GET", "HEAD", "PUT", "DELETE"],
        path:"/call/batch/{code}"
    }
    resource batchProcessingRedirectionResource(http:Request req, http:Response res, string code){
        int statusCode;

        if(strings:equalsIgnoreCase(code, "300")){
            statusCode = 300;
        }
        else if (strings:equalsIgnoreCase(code, "301")){
            system:println(code);
            statusCode = 301;
        }
        else if (strings:equalsIgnoreCase(code, "302")){
            statusCode = 302;
        }
        else if (strings:equalsIgnoreCase(code, "303")){
            statusCode = 303;
        }
        else if (strings:equalsIgnoreCase(code, "305")){
            statusCode = 305;
        }
        else if (strings:equalsIgnoreCase(code, "307")){
            statusCode = 307;
        }

        res.setStatusCode(statusCode);
        res.setHeader("Location", "https://jsonplaceholder.typicode.com/users");
        res.send();
    }
```
The client expected to receive 3xx status code, but did not receive so.

**Comment by erandidesilva** [comment]
Tested with the lasted master. Couldn't reproduce. Hence closing
