### ISSUE TITLE
Type Casting error returns a value instead null

### ISSUE THREAD

**Issue by dakshika** [ballerinalang/ballerina#3149]
import ballerina.lang.system;
1) sample code
function main (string[] args) {
    any a = "Jungle cat";
    var s, castErr = (string)a;
     system:println(castErr);
    if(castErr != null) {
        system:println("error: " + castErr.msg);
    }
    system:println(s);
}

Error: 
ballerina.lang.errors:Error, message: org.ballerinalang.model.values.BString cannot be cast to org.ballerinalang.model.values.StructureType
	at .:maincastErr 

cause: castErr returns the casted value, in this case, string "Jungle cat"

**Comment by lankavitharana** [comment]
fixed with PR https://github.com/ballerinalang/ballerina/pull/3154
