### ISSUE TITLE
SetJsonPayload sends a string literal

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#3194]
**Sample code**
`messages:setJsonPayload(response, "test");`

This sends a string out as "test". This is wrong as this should fail because this is not a valid json.
setJsonPayload should validate whether the set value is a actual json or not.

**Comment by SupunS** [comment]
A JSON can be one of: object, array, string, number, boolean or null (as per json spec). Therefore "test" is a valid JSON. So this is the correct behavior.

further if you try the following, it will also work:
```
json j = "test";
messages:setJsonPayload(response, "test");
```
