### ISSUE TITLE
Error message -- Ballerina : 0 

### ISSUE THREAD

**Issue by irsd62** [ballerinalang/ballerina#3198]
If a user mistakenly tries to get more than returned number of values from a function. 

The error message is not clear.  

```
function main (string[] args) {

    var a,b,c = getVal();
}

function getVal()(string val ){
    val = "a";
    return;
}
```
Error : ballerina: 1 

That's the only error message.

**Comment by SupunS** [comment]
Fixed in v0.93.1
Noe folowing error is thrown:
```
error: mainFunction.bal:3:17: assignment count mismatch: 3 != 1
```
