### ISSUE TITLE
Program with default -> worker 1 -> worker 2 interactions doesn't compile

### ISSUE THREAD

**Issue by afkham** [ballerinalang/ballerina#3217]
The following program which contains 2 workers doesn't compile

import ballerina.lang.system;
import ballerina.lang.jsons;

function main (string[] args) {
    int i = 100;
    float k = 2.34;
    system:println("[default -> w1] i: " + i + " k: " + k);
    //    Send a messages to worker ‘w1’. This message contains two values of type int and float.
    i, k -> w1;
    //Receive a message from worker w1. This message contains a json typed value.
    json j = {};
    j <- w1;
    system:println("[default <- w1] j: " + jsons:toString(j));

    worker w1 {
        //Receive a message from default worker.
        int iw1;
        float kw1;
        iw1, kw1 <- default;
        iw1, kw1 -> w2;
        json jw1;
        jw1 <- w2;
        jw1 -> default;
    }

    worker w2 {
        int iw2;
        float kw2;
        iw2, kw2 <- w1;
        float f = iw2 + kw2;
        json j = {foo:"Hello", bar: f};
        j -> w1;
    }

}

However, the composer properly generates the diagram.
<img width="864" alt="screen shot 2017-08-17 at 9 49 38 pm" src="https://user-images.githubusercontent.com/2654645/29424934-1635e54a-839f-11e7-9579-61e3f0ea2487.png">

**Comment by lafernando** [comment]
This now works properly. Now, we don't have a "default" worker concept, so all the workers need to be explicitly mentioned (if there are multiple workers in the function). The above written in the following manner works.

import ballerina.lang.system;
import ballerina.lang.jsons;

function main (string[] args) {
worker default {
int i = 100;
float k = 2.34;
system:println("[default -> w1] i: " + i + " k: " + k);
// Send a messages to worker ‘w1’. This message contains two values of type int and float.
i, k -> w1;
//Receive a message from worker w1. This message contains a json typed value.
json j = {};
j <- w1;
system:println("[default <- w1] j: " + jsons:toString(j));
}

worker w1 {
    //Receive a message from default worker.
    int iw1;
    float kw1;
    iw1, kw1 <- default;
    iw1, kw1 -> w2;
    json jw1;
    jw1 <- w2;
    jw1 -> default;
}

worker w2 {
    int iw2;
    float kw2;
    iw2, kw2 <- w1;
    float f = iw2 + kw2;
    json j = {foo:"Hello", bar: f};
    j -> w1;
}
}
