### ISSUE TITLE
Variable scoping issue with fork-joins

### ISSUE THREAD

**Issue by afkham** [ballerinalang/ballerina#3226]
Run the following program, and you will note that resW1 seems to be out of scope even though it is clearly in-scope.

import ballerina.lang.system;
function main (string[] args) {
    fork {
        worker w1 {
            int i = 23;
            string s = "Colombo";
            system:println("[w1] i: " + i + " s: " + s);
            i, s -> fork;
        }
        worker w2 {
            float f = 10.344;
            system:println("[w2] f: " + f);
            f -> fork;
        }
    } join (all) (map results) {

        var resW1, _ = (any[])results["w1"];
        system:println(typeof resW1);
        if ((lengthof resW1) > 0) {
            var iW1, _ = (int)resW1[0];
            var sW1, _ = (string)resW1[1];
            system:println("[join-block] iW1: " + iW1 + " sW1: " + sW1);
        }
        var resW2, _ = (any[])results["w2"];
        var fW2, _ = (float)resW2[0];
        system:println("[join-block] fW2: " + fW2);
    }
}

**Comment by lafernando** [comment]
Fixed in Ballerina v0.94.

The above works fine now.
