### ISSUE TITLE
Typelattice contains repeated edges

### ISSUE THREAD

**Issue by maheeka** [ballerinalang/ballerina#3235]
Example : 
String to JSON is listed in both implicit and explicit lattices.

https://github.com/ballerinalang/ballerina/blob/master/modules/ballerina-core/src/main/java/org/ballerinalang/model/types/TypeLattice.java#L78
`implicitCastLattice.addEdge(stringV, jsonV, SAFE, InstructionCodes.S2JSON);`

https://github.com/ballerinalang/ballerina/blob/master/modules/ballerina-core/src/main/java/org/ballerinalang/model/types/TypeLattice.java#L127
`explicitCastLattice.addEdge(stringV, jsonV, SAFE, InstructionCodes.S2JSON);`

In composer we consider the priority of lattices as implicit > explicit > conversion to avoid the issue with duplicated edges. We need to clean up such duplications if they exist.

**Comment by maheeka** [comment]
Also, type lattice marks any to any as an explicit safe cast. Is this correct?
`explicitCastLattice.addEdge(anyV, anyV, SAFE, InstructionCodes.NOP);`

**Comment by SupunS** [comment]
Type lattice has been rewritten, and the above errors no longer exist.
Please feel free to reopen, if you encounter the issue again.
