### ISSUE TITLE
String escape character (Backslash - "\") is dropped in XML literals after parsing

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerinalang/ballerina#3254]
**Issue:** 
The xml literal which has escape character (backslash - "\\") dropped the backslash after parsing. 

**Sample ballerina code:**

Before parsing: 
```xml
xml mx = xml \` \<!--foo \\{{ {{a}} \\}}bar--\> \`; 
```
After Parsing:   
```xml
xml mx = xml \`\<!--foo {{ {{a}} }}bar--\>\`;
```
**Suspect:**

https://github.com/ballerinalang/ballerina/blob/master/modules/ballerina-core/src/main/java/org/ballerinalang/model/builder/BLangModelBuilder.java#L2538

**Comment by SupunS** [comment]
This is the expected behaviour. The backslash is the escape character and it needs to be dropped when evaluating
