### ISSUE TITLE
while not work with the condition

### ISSUE THREAD

**Issue by dakshika** [ballerinalang/ballerina#3268]
Sample: 
```
import ballerina.lang.system;

int i = 0;
function main (string[] args) {
    while (i < 5   ) {
        int i = i + 1;
    }
  
    system:println("Hello World #m");
    
}
```

While is never ending

**Comment by SupunS** [comment]
This is the correct behavior. Here inside the while-loop-condition, it checks the global variable 'i', but inside the while loop, a new variable 'i' is defined and increments it. So the while condition never becomes to false, as the global variable 'i' is never incremented.
