### ISSUE TITLE
[HTTP Connector] If the endpoint fails it's not propagated to the client

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/ballerina#3271]
***Steps to Reproduce***

1. Create the following Bal service

```
import ballerina.net.http;

@http:configuration {
    basePath:"/pass"
}
service <http> PassThroughService {
    string connection = "http://localhost:8688";

     @http:resourceConfig {
        methods:["POST", "GET", "HEAD", "PUT", "DELETE"],
        path:"/call"
    }
    resource passThroughSmallPayloadResource (message m) {
        string headerValue;
        message response;
        string path = "/echo";

        string method = http:getMethod(m);
        http:ClientConnector httpCheck = create http:ClientConnector(connection);
        response = httpCheck.execute(method, path, m);

        reply response;
    }
}
```
2. Make sure you don't have a service running on defined port above.
3. Invoke the service.

**Issue:** Ballerina doesn't generate an error and sends it to the client.

**Comment by shafreenAnfar** [comment]
Tried with the below and it works. Hence, closing the issue. 

import ballerina.net.http;

@http:configuration {basePath:"/hello"}
service<http> helloWorld {

    @http:resourceConfig {
        methods:["GET"],
        path:"/"
    }
    resource sayHello (http:Request request, http:Response response) {
        endpoint<http:HttpClient> httpConnector {
            create http:HttpClient("https://yyyyy", {});
        }
        http:Response resp = {};
        http:HttpConnectorError err;
        resp, err = httpConnector.get("/get?test=123", request);
        if (err == null) {
            response.forward(resp);
        } else {
            response.setStatusCode(500);
            response.setStringPayload(err.msg);
            response.send();
        }
    }
}
