### ISSUE TITLE
Error not descriptive enough when argument list contains both named returns and non named returns

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#3279]
Currently when the method signature consist of both named returns and non named returns, following error message is given.

`resources/services/DBStoredProcedureTest.bal:351:82: unwanted token ','`

This is descriptive enough for a user as it does not give a informative enough description of what the issue is.

**Comment by hasithaa** [comment]
Tested following sample 

```
function main (string[] args) {
   _, _ = test();
}

function test()(string x, int){
    x = "abc";
    int i = 10;
    return x,i;
}
```
And following error is reported by the new compler.
error: pkg.bal:6:30: mismatched input ')'. expecting {'[', Identifier}

Hence closing this issue.
