### ISSUE TITLE
Support for query that selects into a variable in mysql

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#3296]
**Query**
`SELECT CustomerID INTO @CustID FROM Customers where CustomerID = 1;`

According to [1] this should work for a single row if any data is available. But in Ballerina by this query cannot be executed using both "select" and "update" actions. 

**Select**
```
ballerina.lang.errors:Error, message: error occurred during writing the message to the output stream: ResultSet is from UPDATE. No Data.
```

**Update**
`execute update failed: Can not issue executeUpdate() for SELECTs`

[1] https://dev.mysql.com/doc/refman/5.7/en/select-into.html

**Comment by anupama-pathirage** [comment]
In MySQL user defined variables are defined in the session scope. They are loosely typed variables that may be initialized somewhere in a session and keep their value until the session ends. [1] So to access that variable we need to use the same DB connection and it can be done using local transactions as follows.

```java
transaction {
	testDB.select("select firstName into @tt1 From Customers where registrationID =100", null);
	datatable dt = testDB.select("select @tt1", null);
	message response = {};
	var result, _ = <json>dt;
	messages:setJsonPayload(response, result);
	reply response;
} 
```
The output is 
`[{"@tt1":"John"}]`
