### ISSUE TITLE
Fix the possibility of getting dirty values for errors in type cast and conversion expressions

### ISSUE THREAD

**Issue by sameera-jayasoma** [ballerinalang/ballerina#3317]
import ballerina.lang.system;

function main (string[] args) {
    json j = 4;
    json k = 6;
    int kk = foo(j, k);
    var a, e = (any)5;

    system:println(a);
    system:println(e);
}

function foo (json j, json k) (int) {
    return 5;
}

-------
Output
5
4

**Comment by SupunS** [comment]
Fixed in 0.94.0
