### ISSUE TITLE
[Core] Error thrown as undefined type ''

### ISSUE THREAD

**Issue by pamod** [ballerinalang/ballerina#3325]
The error mentioned in the $subject occurs, when a struct is returned from a native function impl and the structType is not being specified. 

During the semantic analysis phase given the type is empty, the error is throw in [1]

 a) could we make the structType mandatory field in @ReturnType
 b) a more descriptive error message would help. i.e undefined struct type in native function <functionName>  

[1] https://github.com/ballerinalang/ballerina/blob/master/modules/ballerina-core/src/main/java/org/ballerinalang/model/types/BTypes.java#L216

**Comment by hasithaa** [comment]
@pamod can you please verify above issue still exist in the master. ? Or could you please provide a sample?

**Comment by hasithaa** [comment]
Verified. This issue is fixed in 0.94 release.
