### ISSUE TITLE
[Documentation] How to configure logging in ballerina

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#3409]
Currently there is no documentation that explains the configuration of logs in ballerina. This is very important as logging is a main component in finding information on the state of ballerina specially when started as a server.

This documentation should cover
1. How to configure logs
2. Different levels applicable and their exact syntax
3. Sample logs in each level

**Comment by samgnaniah** [comment]
Assign to Anupama.

**Comment by anupama-pathirage** [comment]
Example can be found in [1] 

[1] https://ballerinalang.org/docs/by-example/log-api
