### ISSUE TITLE
[Documentation] A quick start guide on Ballerina

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#3411]
Currently as documentation we have the [1]. If a user who is new to Ballerina comes and wants to find an entry point to get his/her use case implemented, he/she will look for a quick start that carries the following information

1. How to write you first ballerina program / service
    a. Using composer
    b. <Maybe> using Idea plugin
2. How run your first ballerina program / service

[1] https://ballerinalang.org/docs/by-example/

**Comment by samgnaniah** [comment]
Please assign to me.

**Comment by anupama-pathirage** [comment]
Added to the ballerinalang website with the 0.95.0 release.
[1] https://ballerinalang.org/docs/quick-tour/quick-tour/
