### ISSUE TITLE
[Documentation] No example available for JMS

### ISSUE THREAD

**Issue by dilini-muthumala** [ballerinalang/ballerina#3424]
Assume a user wants to integrate a message broker with Ballerina. If this user is not much familiar with Ballerina, he would search for a sample for that case in [1]. While samples available for similar things such as File, no sample seems available for JMS.

[1] https://ballerinalang.org/docs/by-example/

**Comment by anupama-pathirage** [comment]
Created https://github.com/ballerinalang/connector-jms/issues/21 to track this
