### ISSUE TITLE
[Documentation] No information on the parameters that need to be passed in the SQL connector

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#3439]
Following is available on the ballerina by example site. But no details on what the parameters are.

```
 sql:ClientConnector empDB = create sql:ClientConnector(sql:MYSQL, "localhost", 3306, "db", "sa", "root", properties);
```

**Comment by anupama-pathirage** [comment]
These details can be found in API doc [1]

[1] https://ballerinalang.org/docs/api/0.93/ballerina.data.sql.html#ClientConnector
