### ISSUE TITLE
Code runs even when it has a backslash in between statements

### ISSUE THREAD

**Issue by shazni** [ballerinalang/ballerina#3440]
Take the following program as an example.

import ballerina.lang.system;

function main (string[] args) {
    json j1 = [1, false, null, "foo",
            {first:"John", last:"Pala"}];
    system:println(j1);
\
    json j2 = j1[4];
    system:println(j2.first);

}

Note there's a '\' (backslash) character after the first system:println statement, 

When the run the program it gives the following out.

line 7:0 token recognition error at: '\'
[1,false,null,"foo",{"first":"John","last":"Pala"}]
John

It recognizes the error and then run the code. If the backslash is replaced with forward slash or any other charecter it detects the error and terminates. For example with / the error is as shown below.

testSlash.bal:6:22: unwanted token ';'

This is tested in version 0.93

**Comment by hasithaa** [comment]
PR https://github.com/ballerinalang/ballerina/pull/3665
