### ISSUE TITLE
[Documentation] No samples on how to get primitive types in datatables

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#3443]
No samples on how to get primitive types in datatables.

eg:
```
struct ResultPrimitive {
    int INT_TYPE;
    int LONG_TYPE;
    float FLOAT_TYPE;
    float DOUBLE_TYPE;
    boolean BOOLEAN_TYPE;
    string STRING_TYPE;
}

...
while (datatables:hasNext(dt)) {
        any dataStruct = datatables:next(dt);
        rs, _ = (ResultPrimitive)dataStruct;
        i = rs.INT_TYPE;
        l = rs.LONG_TYPE;
        f = rs.FLOAT_TYPE;
        d = rs.DOUBLE_TYPE;
        b = rs.BOOLEAN_TYPE;
        s = rs.STRING_TYPE;
    }
```

**Comment by anupama-pathirage** [comment]
Access to the primitive types (int, float, boolean, string)  using all the possible ways are given in the datatables sample [[1](https://ballerinalang.org/docs/by-example/datatables)]
Accessing can be done using
- struct
- xml conversion
- json conversion 

[1] https://ballerinalang.org/docs/by-example/datatables
