### ISSUE TITLE
[Documentation] No example available for Twitter Connector

### ISSUE THREAD

**Issue by dilini-muthumala** [ballerinalang/ballerina#3445]
For a new user who wants to send a Tweet using Ballerina, there's no example available in [1]. The only available information is the API docs [2], which is not much useful for a new user.

[1] https://ballerinalang.org/docs/by-example/
[2] https://ballerinalang.org/docs/api/0.8/org.wso2.ballerina.connectors.twitter.html

**Comment by keerthu** [comment]
As per the current implementation sample will be added to the README file of each connector in the relevant connector repo itself.

**Comment by anupama-pathirage** [comment]
Created https://github.com/ballerinalang/connector-twitter/issues/2 for track this
