### ISSUE TITLE
Unnecessary transform statement in the constrained JSON sample

### ISSUE THREAD

**Issue by shazni** [ballerinalang/ballerina#3471]
In the following sample 

https://ballerinalang.org/docs/by-example/constrained-json

transform statements are unnecessary. That is, even if you remove the transform and the respective open and closing parenthesis it works fine. Having 'transform' keyword confuses its usage.

**Comment by SupunS** [comment]
Fixed with https://github.com/ballerinalang/ballerina/pull/3642

**Comment by anupama-pathirage** [comment]
Fixed in master with #3642
