### ISSUE TITLE
plus (+) symbol doesn't work in the value string within doc annotation

### ISSUE THREAD

**Issue by shazni** [ballerinalang/ballerina#3473]
In the following sample, + symbol doesn't work in the value string within doc annotation.

https://ballerinalang.org/docs/by-example/constrained-json

In addition you need the following package import to make it work, which is reported in below [1].

import ballerina.doc;

[1] https://github.com/ballerinalang/ballerina/issues/3470

**Comment by lankavitharana** [comment]
This is fixed in latest code, git commit - https://github.com/ballerinalang/ballerina/commit/dcc1e453baa68b46f1d20a11aee905381c37025d
