### ISSUE TITLE
Multi return low level error msg 

### ISSUE THREAD

**Issue by chamil321** [ballerinalang/ballerina#3481]
Following semantic error msg is given when multi return values are expected. 
`assignment count mismatch: 2 != 1`
But idealy it should be -  `not enough return values`

```
function testNotEnoughArgsToReturn(string s) (string, string){
    return split(s);
}

function split(string s) (string) {
    return s;
}
```

**Comment by anupama-pathirage** [comment]
Checked with 0.95.0 release. It has below improved error message, hence closing the issue.

`assignment count mismatch: expected 2 values, but found 1`
