### ISSUE TITLE
[Documentation] Pre-requisites to run the Datatables sample should be mentioned separately 

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#3486]
Pre-requisites to run the Datatables sample should be mentioned separately. 
Having the description and the pre-requisites all together is not very clear and user friendly

![pre](https://user-images.githubusercontent.com/1845370/31277323-017cab48-aabe-11e7-8159-a86fabd99337.png)

**Comment by anupama-pathirage** [comment]
Fixed with #3537
