### ISSUE TITLE
Adding @Context annotation by default for a message in a resource.

### ISSUE THREAD

**Issue by hasithaa** [ballerinalang/ballerina#35]
Consider following service
```
@path("/echo")
service echo {
...
@GET 
@Path("/string/{value}")
resource echoString(message m, @PathParam("value") string echoString)
// stuff
reply m;
}
...
}
```

Is it required to add "@Context" annotation for "message m".  (i.e. @Context message m) ?.

**Comment by SupunS** [comment]
Annotations spec are finalized and can be found here: https://github.com/ballerinalang/ballerina/blob/master/docs/specification/annotations.md

Hence closing the issue. Please reopen if theres any concern regarding the specs.
