### ISSUE TITLE
[Doc] Why do we need a HTTP BasePath to use websockets

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/ballerina#3514]
Following example, https://ballerinalang.org/docs/by-example/websocket-basic-endpoint has the below description.

`WebSocket endpoint is defined as a composition of BasePath + WebSocketUpgradePath.`

Why do we need to have an HTTP basepath for WebSockets? Can we explain this?

**Comment by irunika** [comment]
Yes. We have to support Http + WebSocket since WebSocket is an upgrade of WebSocket.
But this API design is changing from 0.94 release onwards.
