### ISSUE TITLE
[Documentation] Add details on ftp connection configuration

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#3525]
Please add comprehensive details on what the configuration parametera of ftp [1] , what they do,  the applicable values for a particular parameter with the behaviour when parameters take different values

E.g. createMoveDir 
1. What is createMoveDir and what does that parameter do?
2. What are the applicable values for createMoveDir parameter
3. What are the behaviour of each and every value that can be assigned to the parameter

[1] https://github.com/ballerinalang/composer/issues/3439

**Comment by SupunS** [comment]
This is tracked at: https://github.com/ballerinalang/connector-file/issues/3
