### ISSUE TITLE
Why do we need do read file uri from message context to read a file

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#3526]
Version: 0.93

According to [1] a file location is read after obtaining it from the message context. Why do we need to do that when we have a configuration called "dirURI" that specifies the read location?

[1] https://ballerinalang.org/docs/by-example/ftp-server-connector

**Comment by SupunS** [comment]
This is tracked at: https://github.com/ballerinalang/connector-file/issues/2
