### ISSUE TITLE
[Documentation] No documentation available on receiving Object type messages via JMS

### ISSUE THREAD

**Issue by dilini-muthumala** [ballerinalang/ballerina#3532]
When receiving Object type messages, the receiving serializable class has to be on ballerina classpath (in <Ballerina_home>/bre/lib)

In addition to this, each supported broker type may require additional configurations. For example, ActiveMQ versions 5.12.2 and 5.13.0 (probably upper versions too) [1] require some additional configurations. 

These have to be figured out, tested and documented.

[1] http://activemq.apache.org/objectmessage.html

**Comment by SupunS** [comment]
This is tracked at: https://github.com/ballerinalang/connector-jms/issues/6
