### ISSUE TITLE
[Documentation] Syntax highlight issues for @ sign in XML Attributes sample

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#3541]
![atmark](https://user-images.githubusercontent.com/1845370/31381202-7da6cc42-add1-11e7-82e6-9246026321a8.png)

**Comment by Shan1024** [comment]
Hi @dilinisg,

What is the IDE you are using?

**Comment by dilinisg** [comment]
Hi @Shan1024 
This was noticed in the ballerina by example site. Not in IDEA

**Comment by anupama-pathirage** [comment]
This is fixed with 0.94.0 update 
https://ballerinalang.org/docs/by-example/xml-attributes
