### ISSUE TITLE
Cannot declare a variable inline when function has multi returns

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/ballerina#3545]
I have a function which returns a struct and a boolean. The Following code doesn't work,

`boolean status, pl = generateRequestStruct(payload);`

But both following codes seems to work,
 
```
boolean status; 
status, pl = generateRequestStruct(payload);
```

`var status, pl = generateRequestStruct(payload);`

**Comment by hasithaa** [comment]
@yasassri . yes, that is the expected behavior. 
`boolean status, pl = generateRequestStruct(payload);` is invalid, because you can't define multiple variables in a single line. Use var for this. 

https://ballerinalang.org/docs/by-example/var
