### ISSUE TITLE
Unclear explanation in the xml to json sample

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#3547]
The following text does not clearly say what are the attributes of the struct. It is better if we show the code of the struct along with a clearer explanation.

`XML to JSON conversion can be done using xmls:toJSON function. This function takes the XML to be converted and struct of options as arguments. The options struct has two fields, attributePrefix which is the prefix to add to the key, to identify a xml attribute and namespaces where default value is ‘@’. And preserveNamespaces to indicate whether to preserve namespace prefixes when converting or not.`

Also the sample does not show how to add options as well. Show a sample with options. Currently it is as below.
`xmls:Options options1 = {};`

**Comment by anupama-pathirage** [comment]
Sample with the options is already there in the [sample](https://ballerinalang.org/docs/by-example/xml-to-json-conversion). 

xmls:Options options2 = {attributePrefix : "#", preserveNamespaces : false};
    json j2 = xmls:toJSON(x, options2);
    system:println(j2);
