### ISSUE TITLE
[Documentation] How to install Ballerina plugin for IntelliJ idea? 

### ISSUE THREAD

**Issue by dilini-muthumala** [ballerinalang/ballerina#3551]
Could not find any documentation on this. Found this information on a blog instead [1]

This will be  a subtask of #3549 

[1] https://medium.com/@eranda.sooriyabandara/ballerina-language-setting-up-your-local-environment-intellij-idea-387c4d05e03f

**Comment by SupunS** [comment]
Created an issue in the relevant repo: https://github.com/ballerinalang/plugin-intellij/issues/655
