### ISSUE TITLE
[Documentation] How to create a new Ballerina project in IntelliJ idea

### ISSUE THREAD

**Issue by dilini-muthumala** [ballerinalang/ballerina#3552]
Could not find any guidance on this in the docs. Found this blog [1] which has this information. IMO this should be in the docs.

This should be a subtask of #3549 

[1] https://medium.com/@eranda.sooriyabandara/ballerina-language-setting-up-your-local-environment-intellij-idea-387c4d05e03f

**Comment by SupunS** [comment]
Created an issue in the relevant repo: https://github.com/ballerinalang/plugin-intellij/issues/654
