### ISSUE TITLE
[Documentation] Creating a hello world program and running it on IntelliJ Idea

### ISSUE THREAD

**Issue by dilini-muthumala** [ballerinalang/ballerina#3553]
Could not find any information on this in the docs. Found a blog instead with some basic instructions [1]. There should be a doc, guiding a user through writing a 'hello world' program and running it.

This is a subtask of #3549 

[1] https://medium.com/@eranda.sooriyabandara/ballerina-language-setting-up-your-local-environment-intellij-idea-387c4d05e03f

**Comment by SupunS** [comment]
Created an issue in the relevant repo: https://github.com/ballerinalang/plugin-intellij/issues/656
