### ISSUE TITLE
Cannot set array type payloads to message type variables

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#3558]
In my scenario, I am calling a DB and retrieve results for n number of times and store that in a xml type array. Then I want to send that you a client. This cannot be easily done as there is no direct function to set array types to a message.

```
...
var data, _ = <xml> dt;
xml[] payload = [];
payload[i] = (xml) data;
messages:setXmlPayload(result, payload);
reply result;
```

**Comment by shafreenAnfar** [comment]
But setting array types to a http request or a response doesn't make sense IMO. If you look at the standard http mime types, none of them requires an array to be set.
