### ISSUE TITLE
Is it possible to read fields of an ObjectMessage got via a JMS service?

### ISSUE THREAD

**Issue by dilini-muthumala** [ballerinalang/ballerina#3560]
Could not find a sample or any documentation on this. Is this even possible or is it just passing the object message through is supported? I was able to get the message from JMS service (of type ObjectMessage) but could not find a way to read the fields of this object and do some processing using Ballerina.

**Comment by SupunS** [comment]
This is tracked at: https://github.com/ballerinalang/connector-jms/issues/5
