### ISSUE TITLE
Can we let the user send a request without a resource path.

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/ballerina#3569]
Note the following example scenario,

   ```
 http:ClientConnector httpConnector = create http:ClientConnector("https://localhost:8080/rh01/verify");
    messages:setJsonPayload(m, jsonMsg);
    message response = httpConnector.post("",m);
```
Is it possible to let the user execute the verb like  `httpConnector.post(m);` ?

**Comment by irunika** [comment]
Since we do not have method overloading in ballerina we cannot have two post actions.

In fact IMO the better approach is to separate address from the URI as in the equivalent to this in v0.94 as in the following example
```
http:ClientConnector httpConnector = create http:ClientConnector("https://localhost:8080", {});
http:Request 
request.setJsonPayload(jsonMsg);
http:Response response = httpConnector.post("/rh01/verify", request);
```

**Comment by shafreenAnfar** [comment]
As per above comment I am closing the issue.
