### ISSUE TITLE
[Documentation] Grammar mistake in SQL Connector example page

### ISSUE THREAD

**Issue by dilini-muthumala** [ballerinalang/ballerina#3577]
In [1], 'Before run the sample copy the JDBC driver to the BALLERINA_HOME/bre/lib folder' should be 'Before running the sample copy the JDBC driver to the BALLERINA_HOME/bre/lib folder.'

[1] https://ballerinalang.org/docs/by-example/sql-connector

**Comment by anupama-pathirage** [comment]
Fixed with #3625
