### ISSUE TITLE
Error produced not clear when assigning a void return from a function to a variable

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/ballerina#3581]
I have the following code,

`VerifyResponsePayload t = callRH02();`

Here callRH02 doesn't return anything, When compiling ballerina gives the following error. We can put a better error IMO.

> balfiles/RemittanceGWService.bal:60: assignment count mismatch: 1 != 0

**Comment by hasithaa** [comment]
Can you suggest a better Error message? 

This is a common error message we provide for assignment and the current error message indicates what is wrong.

**Comment by yasassri** [comment]
@hasithaa I think we can elaborate 1 != 0 part.

Assignment count mismatch: Expected count is 1, but found 0

**Comment by hasithaa** [comment]
@yasassri. agree with you. 1 != 0 is to mathematical, even it explains the issue.
