### ISSUE TITLE
No support for XML transformation

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#3588]
I have a scenario where I have to concat the first name, middle name and last name elements of a xml payload and send the response as a xml payload to the user. This scenario cannot be achieved using Transform directly as xml to xml or other types is not supported.

**Comment by SupunS** [comment]
With the new implementation of transformer, we can create and use XML inside transformer.

@maheeka Do you have any idea of what more we need from language side to support above in composer?

**Comment by maheeka** [comment]
@SupunS , We need a mechanism to define the structure of the XML in order to render the transformer diagram. It could be a XML schema or a struct similar to what we have done for json.

**Comment by SupunS** [comment]
So the requirement is to support schema for XML. This is same as https://github.com/ballerinalang/ballerina/issues/72. 
Thus closing this issue.
