### ISSUE TITLE
[Documentation] No example on adding values to a Map

### ISSUE THREAD

**Issue by dilini-muthumala** [ballerinalang/ballerina#3592]
Ballerina examples or the API docs has no example on how to add a value in to a Map.

Better to enrich the existing example on Maps [1] with a code snippet that pushes a value in to the map. I would suggest, after "Here’s how you create a map with initial values;" section, we insert a snippet, pushing a value into the empty map (`m`) as below:

```
    m["foo"] = "bar";
    system:println(m["foo"]);
```

[1] https://ballerinalang.org/docs/by-example/maps

**Comment by SupunS** [comment]
Above sample actually do have such a section. Following snippet is available nex to `Here’s how you can add or update the value of a key.` section.
```
addrMap["postalCode"] = "00300";     
addrMap.postalCode = "00301";    
system:println(addrMap);
```

**Comment by dilini-muthumala** [comment]
Oh ok...I was under the impression that the key "postalCode" was already there in the map. Sorry for the noise.
