### ISSUE TITLE
Add support for JSON to Constraint JSON casting

### ISSUE THREAD

**Issue by SupunS** [ballerinalang/ballerina#3600]
Currently, it supports only Constraint JSON to JSON (unconstraint) casting. It needs to support the other way around as well.

**Comment by SupunS** [comment]
Sub Task: https://github.com/ballerinalang/ballerina/issues/3084

**Comment by sameera-jayasoma** [comment]
Is this really urgent? Can we live without this?

**Comment by SupunS** [comment]
@sameera-jayasoma, In the transformer use case, the mapping (in composer) can only works with constrained JSONs, because to map, the filed names needs to be known beforehand (similar to structs). To assign a JSON coming from outside (say from network) to a constrained JSON, we need this feature.

I have already done the implementation, only need to update to align with the new JSON implementation (https://github.com/ballerinalang/ballerina/issues/4080), which should be a trivial change.
