### ISSUE TITLE
Cannot access default values of a nested struct 

### ISSUE THREAD

**Issue by chamil321** [ballerinalang/ballerina#3635]
```
struct Ssl {
    string trustStoreFile;
    string trustStorePassword;
    string keyStoreFile;
    string keyStorePassword;
    string sslEnabledProtocols;
    string ciphers;
    string sslProtocol;
}

struct FollowRedirects {
    boolean enabled = false;
    int maxCount = 5;
}

public struct Options {
    int port;
    FollowRedirects followRedirects;
    Ssl ssl;
}
```
If a user creates an Options struct without a struct, then that particular struct won't be initialized. Therefore default values of particular struct fields cannot be accessed. This should be fixed after introducing anonymous structs.
eg:
```
http:Options options = {
    ssl: { trustStoreFile: "${ballerina.home}/bre/security/client-truststore.jks"
    }                 
};
```

**Comment by SupunS** [comment]
This is the intended behaviour for structs. Only value-typed fields can have default values. 
Setting default values for re-typed fields will be supported once the struct-init function is introduced  (refer #4340)
