### ISSUE TITLE
Client connector has to be defined in the top most position

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#3654]
**Sample code**
```
import ballerina.net.http;
function main (string[] args) {
     http:Request req = {};
    http:ClientConnector conn = create http:ClientConnector("/abc",{});
 }
```
The above code generates the below error, which is not informative enough at all.
`error: ConnectorOne.bal:4:29: extraneous input 'create'`

Furthermore, having a order to be preserved in a case of a client connector is confusing for the user.

**Comment by lankavitharana** [comment]
This was a design decision to allow connection creation only at the top, rational being, connector is represented as a line in the composer(not a statement on a line) so if we allow connector creation everywhere, it's difficult to represent that in composer, and there is another reason as well.

within a invocation unit, we can have workers, so if there are workers in a invocation unit, then we can't have statements outside those workers, reason is, there is no worker to execute them, so if we treat connector creation as a statement, then again it can be inside a worker and hence come the problem how to draw it in composer. So current design is, connector creation is a different statement can be only defined at top level. 
as you said it is confusing just looking at the ballerina code(without composer view) so some arguments are there to change that. 

And for the error msg, it is a grammer error, and it is bit hard to give a clear error msg for a grammer error, (will be kind of a separate project) hence created a separate issue to track that at https://github.com/ballerinalang/ballerina/issues/3673
