### ISSUE TITLE
Error when invoking the restful service sample

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#3664]
1. Run the sample.
bin$ ./ballerina run ../samples/restfulService/ecommerceService.balx
2. Invoke the service 
curl -X GET "http://localhost:9090/ecommerceservice/products/123000"

The following error is logged
```
error, message: failed to send httpRequestMsg to the backend
	at ballerina.net.http:ClientConnector.get(<native>:0)
	at restfulservice.samples:Ecommerce.productsInfo(ecommerceService.bal:15)
```

**Comment by anupama-pathirage** [comment]
Verified with 0.95.0 release and found no issue now.
