### ISSUE TITLE
Cannot run services in a package with a backward path 

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/ballerina#3677]
When I try to run the srevice with `./../../../0.94Release/shafreen/ballerina-0.93.1-SNAPSHOT/bin/ballerina run l1/l2/l3/longRunning` It executes without an issue.

But when I try .`/../../../0.94Release/shafreen/ballerina-0.93.1-SNAPSHOT/bin/ballerina run ../artifacts/l1/l2/l3/longRunning` It goves me following error.

`ballerina: internal error occurred`

**Comment by SupunS** [comment]
To run a package, the current location should be the package root. i.e: Packages should be run from the root of the package. We need to include this in the documentation. Theres a separate issue (https://github.com/ballerinalang/ballerina/issues/3214) for that.

Hence closing this issue.
