### ISSUE TITLE
Test for adjacent response methods failing intermittently

### ISSUE THREAD

**Issue by chamil321** [ballerinalang/ballerina#3738]
```BALLERINA CODE
resource echo (http:Request req, http:Response res) {
        ////
        resp.setStringPayload("Ballerina");
        res.send();
        res.forward(resp);
    }
```
Usual behavior of above code segment is that res.send() sends the response back to the client. When the next line(res.forward(resp);) executes, an illegalStateException should be thrown of saying "illegal function invocation"
The test is written to assert the response. But if the error reaches the handleResponse() before the response, then test assert with the error.

**Comment by chamil321** [comment]
The ideal solution is to execute "forward" function after the completion of "send". Currently, this blocking behavior is not included. Therefore concurrently the two response will get mixed up. So "send" should notify the engine once the execution is done(future success), till then "forward" should wait with the operation.

**Comment by chamil321** [comment]
PR https://github.com/ballerinalang/ballerina/pull/4101 has introduced the sync execution for I/O operations.  Therefore adjacent send(), forward() are synchronized and it notifies ballerina once the execution is done(future success), Hence we can close the issue as it has addressed.

**Comment by shafreenAnfar** [comment]
As per the above comment, I am closing this issue.
