### ISSUE TITLE
Stop returning from the main method

### ISSUE THREAD

**Issue by Shakila** [ballerinalang/ballerina#3744]
When the ballerina task is scheduled, it has to prevent from returning from the main method.

**Comment by hasithaa** [comment]
@Shakila, IMO, we can consider, task scheduling as a spawning a new worker. Then you can call context.startTrackWorker() when scheduling the task ( from the native code). This will stop returning the main worker.

Once the task is done ( for a non-recurring task ) you can call context.endTrackWorker() method to release the main worker. 

Please let me know whether this is working for you.

**Comment by hasithaa** [comment]
As per discussion had with Shakila, This is working for her. Hence Closing issue.
