### ISSUE TITLE
Function pointer which returns error

### ISSUE THREAD

**Issue by Shakila** [ballerinalang/ballerina#3745]
Supporting the function pointer to return error.
e.g:
function () returns (any) scheduleAppointmentOnTriggerFunction;
    scheduleAppointmentOnTriggerFunction = cleanup;

function cleanup () returns (error) {
        error err = {msg:"Unable to clean up the tmp directory"};
        return err;
}

**Comment by hasithaa** [comment]
@Shakila. This issue is misleading. IIRC, what you need is to handle the returned error (or just log), when the function pointer is called by the task scheduler. Isn't it?

**Comment by hasithaa** [comment]
After discussing with Shakila, what we need is a way to invoker ballerina function using native code. This will fix with 
https://github.com/ballerinalang/ballerina/pull/3762
