### ISSUE TITLE
[Debugger] For connectors, complex values should be renamed to a proper indicator.

### ISSUE THREAD

**Issue by pahans** [ballerinalang/ballerina#3760]
more information here https://github.com/ballerinalang/composer/issues/2984

**Comment by lafernando** [comment]
Can you please elaborate on this issue please. An example would be great.

**Comment by pahans** [comment]
In the given sample `req` and `res` are empty structs (earlier it was listed as `complex_value`). 

We could include some information in `req` to ease debugging process.
![selection_086](https://user-images.githubusercontent.com/1552869/33265811-0cd6a422-d399-11e7-8a1e-7fb329ca7657.png)

**Comment by pahans** [comment]
@lafernando closing this since this is a exact duplicate of https://github.com/ballerinalang/ballerina/issues/4124
