### ISSUE TITLE
Question: How-to create connector (RabbitMQ)

### ISSUE THREAD

**Issue by allustin** [ballerinalang/ballerina#3773]
* we need an rabbimq connector for balerina
* we deside to create it
* we need an example for that it in docs

**Comment by artbear** [comment]
+1

**Comment by lankavitharana** [comment]
Hi Allustin/Artbear,

If you are interested, I have written two blog posts about client connectors and native client connectors in Ballerina, below are the links, hope that may help you :)

1)  - https://medium.com/@lanka.vitharana/ballerina-connectors-endpoints-and-what-how-why-a04d414657f0
2) - https://medium.com/@lanka.vitharana/ballerina-native-client-connectors-and-all-you-need-to-know-e76957ca05dd

Thanks,

**Comment by anupama-pathirage** [comment]
Closing the issue as the above comment give details on how to write a connector. Please raise any questions if you have any
