### ISSUE TITLE
[HTTP] Need a function to get multiple values for single header

### ISSUE THREAD

**Issue by irunika** [ballerinalang/ballerina#3918]
In HTTP a single header can have multiple values. In current HTTP API getHeader() function only return a single value. In case of need, we need to add a method to return an array of header values for a single header key.

**Comment by yasassri** [comment]
Also, the order is important when returning multiple headers.

**Comment by chamil321** [comment]
Using headers map of req/resp, all headers can be retrieved. Hence please close the issue.

**Comment by shafreenAnfar** [comment]
As per the above comment I am closing this issue.
