### ISSUE TITLE
Inconsistency when initializing HTTP Response and Error

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/ballerina#3919]
Consider the following code segment,

```
http:Response clientResponse = {};
http:HttpConnectorError err = {};
println(err);
println(clientResponse);
```
Above gives following output.

```
{msg:"", cause:null, stackTrace:null, statusCode:0}
{}
```

**Comment by chamil321** [comment]
Currently, there is a discussion going on "Enrich Request Response structs". We can address this issue with a proper conclusion.

**Comment by shafreenAnfar** [comment]
This is as per the current design. As a new feature we are planning to improve this behaviour. Hence, closing the issue which is reported as a bug.
