### ISSUE TITLE
[Debugger] Client Response struct is not shown in debug mode

### ISSUE THREAD

**Issue by pahans** [ballerinalang/ballerina#3923]
please refer https://github.com/ballerinalang/composer/issues/4474 for more details

**Comment by lankavitharana** [comment]
At the moment, these Response and Request structs are empty structs(no Ballerina level data in them). So  it's not possible to show anything in them in debug mode

**Comment by shafreenAnfar** [comment]
I am closing this as I have created another issue to track requirement. 

https://github.com/ballerinalang/ballerina/issues/4124
