### ISSUE TITLE
cannot run programs when extracted to a path with spaces

### ISSUE THREAD

**Issue by kaviththiranga** [ballerinalang/ballerina#3927]
Related temporary fix for windows 
https://github.com/ballerinalang/ballerina/pull/3925

When the pack is extracted
to a path which contains spaces, it throws
Exceptions when try to run a program.

**Comment by anupama-pathirage** [comment]
duplicated issue #3005

**Comment by SupunS** [comment]
Closing the issue since this is a duplicate.
