### ISSUE TITLE
getting error when trying out endpoint in ballerina by example page

### ISSUE THREAD

**Issue by arunans23** [ballerinalang/ballerina#3934]
```

function getSQLconfigData(json configData){
    
    //endpoint
    endpoint<sql:ClientConnector> testDB {
        create sql:ClientConnector(
        sql:MYSQL, "localhost", 3306, "testdb", "root", "root", {maximumPoolSize:5});
    }
}
```

I tried the above example. Compilation fails with below error.

> error: org.wso2.internalapps.pqd/GithubService.bal:35:5: extraneous input 'endpoint'
compilation contains errors

I tried removing the comment above endpoint and tried compiling. It compiles fine.

Same happens whenever I try to have something above the endpoint.

**Comment by anupama-pathirage** [comment]
According to the current ballerina language spec, endpoint  statement should be the first statement due to visual sequence diagram aspects. So we can't have any statement (even a comment statement) before that by design.
