### ISSUE TITLE
Hello World Sample is outdate in Quick Tour

### ISSUE THREAD

**Issue by hasithaa** [ballerinalang/ballerina#3943]
https://ballerinalang.org/docs/quick-tour/quick-tour/#run-helloworld

The correct sample is.
```
function main (string[] args) {
  println("Hello, World!");
}
```

**Comment by samgnaniah** [comment]
This is fixed.

https://ballerinalang.org/docs/quick-tour/quick-tour/#run-helloworld

**Comment by anupama-pathirage** [comment]
@samgnaniah The `import ballerina.lang.system;` is no longer required. Please remove that as well.

**Comment by anupama-pathirage** [comment]
This is fixed now
