### ISSUE TITLE
[HTTP] Server connector actions need to pause BVM

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerinalang/ballerina#3949]
If you take client connectors they all halt the BVM execution till they complete their I/O operation, but when it comes to server connector actions this is not the case. 

As soon as BVM hand it over to the server connector, it continues the execution. Ideally it should do what client connectors are doing.

**Comment by chamil321** [comment]
#4101 synchronizes the server connector response execution and returns server connector error to ballerina level if exists. Ballerina execution halts until the response is completely written back to the caller. Hence the above issue is resolved

**Comment by shafreenAnfar** [comment]
As per the above comment, I am closing this issue.
