### ISSUE TITLE
[Documentation] Provide accepted data types and their syntax for sql connector

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#3978]
$subject please as it will be useful for a developer

**Comment by anupama-pathirage** [comment]
This will be fixed with https://github.com/ballerinalang/docerina/pull/136

**Comment by anupama-pathirage** [comment]
Supported data types are documented in API docs.
https://ballerinalang.org/docs/api/0.95.3/ballerina.data.sql.html#Type
