### ISSUE TITLE
Error when the database type is set to sql:MYSQL in SQL Connector

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#3979]
When the database type of the sql connector is set as below as shown [1], the following error is thrown.
```
endpoint<sql:ClientConnector> testDB {
          create sql:ClientConnector(
            sql:MYSQL, "localhost", 3306, "testdb", "xxx", "xxx", {maximumPoolSize:5});
    }
```
`error, message: error in sql connector configuration: cannot generate url for unknown database type : SQL:MYSQL`

[1] https://ballerinalang.org/docs/by-example/sql-connector

**Comment by anupama-pathirage** [comment]
Can you please share the full example which gives the mention error? Couldn't reproduce with the given information.

**Comment by dilinisg** [comment]
[1] is the full solution. This was working fine when only `MYSQL` is used instead of `sql:MYSQL`
[1] https://github.com/yasassri/ballerina-banking-solution

**Comment by anupama-pathirage** [comment]
Found the issue is using "sql:MYSQL" (i.e. with quotes) which is wrong for package string constant.
