### ISSUE TITLE
Cannot Define a default Enum value inside a struct

### ISSUE THREAD

**Issue by chanikag** [ballerinalang/ballerina#3980]
I was trying the following scenario,

enum Version {
   SOAP11, SOAP12
}

public struct  Request {
SoapVersion version1 = SoapVersion.SOAP12;
}

But this gives the following error,

error: ballerina.net.soap[]/natives.bal:11:27: mismatched input 'SoapVersion'. expecting {'-', IntegerLiteral, FloatingPointLiteral, BooleanLiteral, QuotedStringLiteral, 'null'}
error: ballerina.net.soap[]/natives.bal:11:38: extraneous input '.'
error: ballerina.net.soap[]/natives.bal:28:28: mismatched input 'SoapVersion'. expecting {'-', IntegerLiteral, FloatingPointLiteral, BooleanLiteral, QuotedStringLiteral, 'null'}
error: ballerina.net.soap[]/natives.bal:28:39: extraneous input '.'

**Comment by sameera-jayasoma** [comment]
Hi Chanika,

You cannot assign a default value to enum variable within a struct at the moment. This is by design. We allow value typed values here.  e.g. following is allowed.

struct person {
    string name = "sss";
    int age = 23;
}
