### ISSUE TITLE
Doc annotation support for enum

### ISSUE THREAD

**Issue by chanikag** [ballerinalang/ballerina#3985]
I defined the doc annotations for the fields inside enum as below,

@Description { value: "Enum to represent SOAP versions"}
@Field {value:"SOAP11: Represents the SOAP 1.1 version"}
@Field {value:"SOAP12: Represents the SOAP 1.2 version"}
enum Version {
   SOAP11, SOAP12
}

But it gives the following issue,
error: ballerina.net.soap[]/natives.bal:6:1: annotation 'ballerina.builtin:Field' is not allowed in enum
error: ballerina.net.soap[]/natives.bal:7:1: annotation 'ballerina.builtin:Field' is not allowed in enum

**Comment by hasithaa** [comment]
This is already fixed in master with https://github.com/ballerinalang/ballerina/pull/3939/files
