### ISSUE TITLE
Incorrect values when retrieving values of JSON fields using `|field|`

### ISSUE THREAD

**Issue by Shan1024** [ballerinalang/ballerina#4045]
```Ballerina
public function main (string[] args) {
    json tempJson = {"product": {"name" : "ballerina", "type" : "language", "version": "0.95.0"}};
    println(tempJson.product.|type|);
    println(tempJson.product.|version|);
}
```

Output for both values are `null`.

**Comment by SupunS** [comment]
The actual issue is a variable having an identifier (i.e: `x`) is treated differently to a variable with identifier-literal (i.e: `|x|`).

eg:
```ballerina
string |x| = "foo";
println(|x|);
println(x);
```
In the above snippet, using `x` without pipe, throws an error saying undecalred variable, since its treated as a separate variable.
