### ISSUE TITLE
DiagnosticPosition API change required

### ISSUE THREAD

**Issue by nadeeshaan** [ballerinalang/ballerina#4052]
in the current DiagnosticPosition API, following methods are available to retrieve the line and columns.

```
int getStartLine();
int getEndLine();
int startColumn();
int endColumn();
```

It would be better if we stick to one convention, preferably as following,

```
int getStartLine();
int getEndLine();
int getStartColumn();
int getEndColumn();
```

**Comment by sameera-jayasoma** [comment]
I prefer following method names

`
int startLine();
int endLine();
int startColumn();
int endColumn();
`

There are no setter methods in the interface. So let's use these methods.
