### ISSUE TITLE
Cannot read the output of conditional query

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/ballerina#4054]
I used the following query, which returns a value.

`select if(TIMESTAMPDIFF(HOUR,(SELECT created_date FROM OTP_Info WHERE otp_id=?), now()) < ?, (select user_id from OTP_Info where otp_id = ?), 0);`

When I print the data struct it gives the following output.

`{if(TIMESTAMPDIFF(HOUR,(SELECT created_date FROM OTP_Info WHERE otp_id='1455c47260384f99a868d97dc99c17ee1034567890'), now()) < 48, (select user_id from OTP_Info where otp_id = '1455c47260384f99a868d97dc99c17ee1034567890'), 0):1034567890}`

So I'm unable to read the value from this. This can be solved if I modify the query as follows.

`select if(TIMESTAMPDIFF(HOUR,(SELECT created_date FROM OTP_Info W HERE otp_id=?), now()) < ?, (select user_id from OTP_Info where otp_id = ?), 0) AS user_id;"`

**Comment by anupama-pathirage** [comment]
This is fixed with https://github.com/ballerinalang/ballerina/pull/4227
