### ISSUE TITLE
Safe navigation operator for null

### ISSUE THREAD

**Issue by sameera-jayasoma** [ballerinalang/ballerina#4076]
Consider following example. 

person p = getPerson();
validate(p.addr.city);

If p is null, then this code throws a null reference error. One solution is to use if-else to avoid null references. 

Can we come up with an operator to write this style statements without adding if-else for everything?

**Comment by SupunS** [comment]
This has been requested in the https://github.com/ballerinalang/ballerina/issues/2914.
Hence closing this issue. Progress can be tracked via #2914.
