### ISSUE TITLE
Safe navigation operator for error

### ISSUE THREAD

**Issue by sameera-jayasoma** [ballerinalang/ballerina#4077]
Refer https://github.com/ballerinalang/ballerina/issues/4076

**Comment by hasithaa** [comment]
Proposal for Safe Navigation. https://docs.google.com/document/d/1VC4K9In5ELkFXZN_J9GegWK01Z6YwO8HQ9qZ2tGGSyI/edit

**Comment by SupunS** [comment]
This has been requested in the https://github.com/ballerinalang/ballerina/issues/2914.
Hence closing this issue. Progress can be tracked via #2914.
