### ISSUE TITLE
Handle SetBinaryPayload/GetBinaryPayload properly with MIME type support

### ISSUE THREAD

**Issue by chamil321** [ballerinalang/ballerina#4092]
Currently, Ballerina supports GetBinaryPayload which returns a Blob as the output. BinaryPayload should be processed properly after introducing MIME type support to ballerina

**Comment by pubudu91** [comment]
This issue was fixed with PR #4274

**Comment by shafreenAnfar** [comment]
As per the above comment, I am closing this issue.
