### ISSUE TITLE
[HTTP] Image is corrupted when writing as a new file after obtaining the content through HTTP request

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#4127]
Payload -> .jpeg as an attachment
Header -> Content-Type, image/jpeg

**Sample code**
```
import ballerina.net.http;
import ballerina.file;
import ballerina.io;

@http:configuration {
    basePath:"/file"
}
service<http> FileService {
    
    @http:resourceConfig {
        methods:["POST"],
        path:"/createFile"
    }
    resource createFileResource (http:Request req,http:Response res) {
       blob content = req.getBinaryPayload();
       file:File newFile = {path:"/home/erandi/Documents/Ballerina/connector-file/filelocation/file.jpeg"};
       var result, eA, eIO = newFile.createNewFile();
       io:ByteChannel channel = newFile.openChannel("w");
       int numberOfBytesWritten = channel.writeBytes(content, 0);
       println(numberOfBytesWritten);
    }
}
```
The file created cannot be opened. This works fine when the file is read using the io apis and the read content is written again using the io channel.

**Comment by erandidesilva** [comment]
Same exist for a .doc extension as well

**Comment by erandidesilva** [comment]
Reproduce
1. Attach the image as form data
2. Add the content-type header separately. e.g. image.jpeg
3. Send the message

**Comment by SupunS** [comment]
@erandidesilva, Handling multipart/form-data is not supported in ballerina yet.
This is still in design phase, and the discussion can be found at [1].

`req.getBinaryPayload();` supports only for data sent as binary data.

[1] https://groups.google.com/d/msg/ballerina-dev/Xk9YErqUVmc/MAicF1D8CQAJ

**Comment by shafreenAnfar** [comment]
I am closing this issue as per the above comment. At the moment we are working on multi-part stuff and it is not implemented yet. As mentioned, requirement is captured with #3752.
