### ISSUE TITLE
[Query] Read multi-part form data request

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#4141]
There is a need to read a request with multi-part form data that carries an attachment. Since no documentation is available, it would be much appreciated if it can be explained how to achieve it using ballerina

**Comment by shafreenAnfar** [comment]
At the moment multipart support is not there. Requirement is captured at [1]. Discussion can be found in ballerina-dev "Handling MIME Types". Hence, I am closing this issue. 

[1] https://github.com/ballerinalang/ballerina/issues/3752
