### ISSUE TITLE
Make "typeof j" work correctly where j is of type json

### ISSUE THREAD

**Issue by SupunS** [ballerinalang/ballerina#4142]

**Comment by sanjiva** [comment]
Example code:

json j1 = 5;
// now typeof j1 should be int
json j2 = "hello";
// now typeof j2 should be string
json j3 = { foo : "bar" };
// now typeof j3 should be json (i.e., we're using json to mean json object)
json j4 = [1,2,3, 4];
// now typeof j4 should be int[]
