### ISSUE TITLE
Type of operator works for endpoint

### ISSUE THREAD

**Issue by lankavitharana** [ballerinalang/ballerina#4168]
Below code works

```ballerina
import ballerina.net.http;

public function main (string[] args) {
    endpoint<http:HttpClient> ep {

    }

    println(typeof ep);
}
```
prints below line 

ballerina.net.http:HttpClient

**Comment by sanjiva** [comment]
This is not a widely used scenario.

Conceptually proposed design is fine - ep is not the endpoint but rather an identifier for the connection. And if the connection was bound to a filter / wrapper connector then it should return the the wrapped type.

Same question can arise for workers: typeof w1.

We can add this later if there's a need.
