### ISSUE TITLE
Extraneous input error as some integer values are treated as octal values

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#4171]
**Steps**
1. Run the following code
```
function main (string[] args) {
    int bill = 008;
    println("Bill num " +bill);
}

```
**Issue**
This gives a compilation error : `extraneous input '8'`. 

This error does not throw for values between 001 to 007. But will be thrown for values like, 009, 018, 0776625198

**Comment by lafernando** [comment]
This is by design. Where, a number which start with 0 is considered an octal value.
