### ISSUE TITLE
Composer not setting default service in Try It

### ISSUE THREAD

**Issue by edgars** [ballerinalang/ballerina#4173]
Hi People,

I had been using the composer from release 0.95 and when I executed the service, it had put the default service already in the Try It UI, now in the 0.95.1, it does not get the default service when I run it, like this: 

![image](https://user-images.githubusercontent.com/25833/33275039-e9c9c15a-d378-11e7-82e7-c6c37c0c4baa.png)

Is there any configuration that I need to add into my service?

**Comment by anupama-pathirage** [comment]
Created https://github.com/ballerinalang/composer/issues/4765 in composer repo to track this. Hence closing this issue
