### ISSUE TITLE
Composer out of sync

### ISSUE THREAD

**Issue by eptx** [ballerinalang/ballerina#4230]
Writing sample program in composer on osx/chrome. Change code to create then fix syntax errors or vice versa and we're out of sync. Compiles, but shows errors. Or shows no errors, but does not compile.

![image](https://user-images.githubusercontent.com/133013/33651211-3e1e6422-da22-11e7-80f5-dd6f5d0a77f1.png)

**Comment by anupama-pathirage** [comment]
Created https://github.com/ballerinalang/composer/issues/4809 in composer project to track this. Hence closing this issue.

**Comment by nadeeshaan** [comment]
@eptx Tested this particular scenario in the latest master, and could not see the issue. Can you confirm by trying the same in the latest release and we will keep open issue untill
