### ISSUE TITLE
'typeof' operator gives incorrect results for arrays

### ISSUE THREAD

**Issue by pranavan15** [ballerinalang/ballerina#4272]
`function main (string[] args) {
    println((typeof int[]));
    println(typeof string[]);
}
`

The above code produces the below outputs,
int
string

Where the expected outputs should be,
int [ ]
string [ ]

**Comment by SupunS** [comment]
Also, type of a struct type array gives syntax errors
eg:
```ballerina
public function main (string[] args) {
    println(typeof Person[]);
}

struct Person {
}
```
Gives below syntax error during compilation:
```
error: mainFunction.bal:2:27: invalid token ']'
error: mainFunction.bal:2:28: extraneous input ')'
compilation contains errors
```
