### ISSUE TITLE
Fix Transport Level Stream Close in Code

### ISSUE THREAD

**Issue by lafernando** [ballerinalang/ballerina#4291]
Currently, in the BJSON class, the stream is closed in its "serializeData" method, other than also doing a "flush()". This should only be a flush, but due to the transport not closing the connection from its side, the response will not be reaching the client in the streaming case. This should be properly fixed by closing the stream from the transport code and removing the close from places like BJSON#serializeData.

**Comment by shafreenAnfar** [comment]
Fix with the below PR

https://github.com/ballerinalang/ballerina/pull/4298
