### ISSUE TITLE
passing multiple any[] arrays to Fork join 

### ISSUE THREAD

**Issue by lasinducharith** [ballerinalang/ballerina#4319]
public function main (string[] args) {
    fork {
        worker w1 {
            any[] a = [];
            a -> fork;
        }

        worker w2 {
            any[] b = [];
            b -> fork;
        }

    } join (all) (map results) {
        println(results);
    }
}

Above code gives following error.

[1] error: fail to compile file: index: 32, Size: 32 error: fail to compile file: index: 32, Size: 32

More details in ballerina-dev:
https://groups.google.com/forum/#!topic/ballerina-dev/16o38cH1bjo

**Comment by hasithaa** [comment]
Fixed with https://github.com/ballerinalang/ballerina/pull/4326
