### ISSUE TITLE
Composer (0.95.7) home page crashing on Chome (Version 63.0.3239.84)

### ISSUE THREAD

**Issue by sumedharubasinghe** [ballerinalang/ballerina#4455]
Downloaded ballerina-tools-0.95.7 (latest available)
I am on Chrome Version 63.0.3239.84 (Official Build) (64-bit) 

Home page is crashing with following.
<img width="1349" alt="screen shot 2018-01-18 at 12 32 56 pm" src="https://user-images.githubusercontent.com/6261293/35085186-7d9929d2-fc4d-11e7-8b0f-938bfaaea6ad.png">

works fine on Firefox (57.0.3 (64-bit)).

**Comment by SupunS** [comment]
Closing this and created a separate issue in composer repo: https://github.com/ballerinalang/composer/issues/4993
