### ISSUE TITLE
server stop accessing requests during load testing and print error log

### ISSUE THREAD

**Issue by chanakaudaya** [ballerinalang/ballerina#610]
Following log entry is observed when doing a load test with 100 concurrent users. Test waits for some time and then continued and finished (with errors)

```
[2017-01-05 22:52:30,601] Error while executing ballerina program. No Service found to handle incoming request recieved to : /bad-request
```

**Comment by SupunS** [comment]
Above issue is not reproducible since v0.8.0 release.
