### ISSUE TITLE
Writing a framework to write server connectors for ballerina

### ISSUE THREAD

**Issue by chanakaudaya** [ballerinalang/ballerina#649]
Ballerina only supports HTTP as a server side transport. But we need to bring in more and server side transports going forward (e.g. Websocket, JMS, File, HTTP2, etc.). Existing HTTP server side transport is implemented as a listener transport. We should implement a proper framework to write server side connectors to the ballerina.

**Comment by sameera-jayasoma** [comment]
We've now has server connector framework.
