### ISSUE TITLE
Add Websocket client connector to ballerina

### ISSUE THREAD

**Issue by chanakaudaya** [ballerinalang/ballerina#651]
Websocket protocol is one of the most popular protocols used in the web. It has great strengths which were not there in standard HTTP protocol. Some of them are mentioned below.

Before WebSocket, all communication between web clients and servers relied only on HTTP. Now, dynamic data can flow freely over WebSocket connections that are persistent (always on), full duplex (simultaneously bi-directional) and blazingly fast.

https://en.wikipedia.org/wiki/WebSocket

https://tools.ietf.org/html/rfc6455

**Comment by SupunS** [comment]
Added with PR: https://github.com/ballerinalang/ballerina/pull/1901
