### ISSUE TITLE
Join Behavior Clarification

### ISSUE THREAD

**Issue by FrankLeymann** [ballerinalang/ballerina#660]
The grammar allows to specify both, a join clause as well as a timeout clause:
````
forkJoinStatement
    :   'fork' '(' typeName Identifier ')' '{' workerDeclaration+ '}' joinClause? timeoutClause?
    ;
````
If both is specified and the timeout limit is reached, I assume waiting for the number of workers specified by the join clause stops and the messages responded by the workers until then are used to construct the result of the fork - correct?

**Comment by chanakaudaya** [comment]
@FrankLeymann That's exactly what happens.
