### ISSUE TITLE
How to set properties of exceptions?

### ISSUE THREAD

**Issue by FrankLeymann** [ballerinalang/ballerina#661]
Don't we need a function to set properties

````
native function setProperties()
````
in the `ballerina.lang.exception` [package](https://github.com/wso2/ballerina/blob/master/libsrc/ballerina/lang/exception/exception.bal)?

**Comment by hasithaa** [comment]
Hi Frank, Since we have removed ballerina.lang.exception package and moved to error, this issue no longer exists. 

Thanks, 
Hasitha.
