### ISSUE TITLE
Treat connector and variable declarations as just declarations and allow initializations in declarations

### ISSUE THREAD

**Issue by sameera-jayasoma** [ballerinalang/ballerina#766]
Consider the following list of declarations. It contains both connector declarations as well as variable declarations. This is not possible in M2, but due to limitations in the previous approach we've decided to remove this distinction and treat both types of declarations as just declarations. Now you can mix connector and variable declarations and even you can initialize your variables with constant values.

// Declarations
json jsonPayload;
test:TestConnector resourceScopeConnector = new test:TestConnector("dd");
TestConnector conn2 = new TestConnector("dd");
test:TestConnector conn;
test:Person p1 = new Persion;
Employee e1; 
int i = 4;
string param1 = "";
string param2;

// Statements
conn = new test:TestConnector(param1);

This task can be broken down to following subtasks.

- [ ] Change the grammar to support this.
- [ ] Support initialization of connectors and variables
- [ ] Allow connectors to be initialized later. This wasn't possible earlier

**Comment by SupunS** [comment]
Grammar change is added with commit https://github.com/ballerinalang/ballerina/pull/1645/commits/db4a7911bce4823d9de437511b83e15acdef4583

Functionality support is added in PR: https://github.com/ballerinalang/ballerina/pull/1645
