### ISSUE TITLE
Remove mandatory package name from the connector declarations

### ISSUE THREAD

**Issue by sameera-jayasoma** [ballerinalang/ballerina#768]
At the moment, you need to specify the package name when you declare a connector. 

e.g. 
test:TestConnector resourceScopeConnector = new test:TestConnector("dd");

Make the package name optional. We need to support the following as well. E.g. if you declaring connector defined in the same package, you don't need to use the package name.
TestConnector resourceScopeConnector = new TestConnector("dd");

**Comment by SupunS** [comment]
This is supported in v0.8.0
