### ISSUE TITLE
Ballerina module support. 

### ISSUE THREAD

**Issue by hasithaa** [ballerinalang/ballerina#807]
The structure of a Ballerina module. 

**tweet.zip**
```
    com
        example
            tweet
                github
                    tweetGitHubService.bal   <- BasePath /github
                medium
                    tweetMediumService.bal   <- BasePath /medium
    org
        example
            utils
                tweetFunctions.bal
                githubUtils.bal
                mediumFunctions.bal
```

Each module:
- can have multiple packages. 
- has independent SymScope inherited from BALLERINAPATH SymScope. ( No siblings package sharing)
- filename considers as the context and will be added as a prefix to the basebase.  Service path: schema://host:port/**ModuleName**/BasePath
Eg: 
http://localhost:9090/tweet/github
http://localhost:9090/tweet/medium

**Comment by SupunS** [comment]
This feature is added since v0.8.0-RC1
