### ISSUE TITLE
HTTP Connector - Support for timeout, error handling and retrying

### ISSUE THREAD

**Issue by kasun04** [ballerinalang/ballerina#837]
This feature should primarily cover all the error handling requirements, timeout handling, and retrying mechanisms.

**Comment by shafreenAnfar** [comment]
Hi Kasun,

We have implemented timeout and retrying. 

For error handling, we have created specific tasks,

https://github.com/ballerinalang/ballerina/issues/3951
https://github.com/ballerinalang/ballerina/issues/4025

Hence, closing this issue.
