### ISSUE TITLE
Add HTTP Protocol related functions 

### ISSUE THREAD

**Issue by kasun04** [ballerinalang/ballerina#846]
HTTP protocol related utilities has to be added as functions (e.g: Set status code, disable chunking, enforce http 1.0 etc.).

**Comment by pubudu91** [comment]
Since this issue is not specific about what should be included, created a new issue (#4267) to track the missing feature (enforcing HTTP 1.0) out of the features mentioned.

**Comment by anupama-pathirage** [comment]
Closing the original issue since set status code and disable chunking are already supported and a new issue #4267 is created to track the missing feature.
