### ISSUE TITLE
Unable to declare the connector

### ISSUE THREAD

**Issue by keerthu** [ballerinalang/ballerina#848]
Getting "unsupported type 'HTTPConnector'" error when declare the connector at first and then initialize as,
    http:HTTPConnector SalesforceRestEP;
    string srEndpoint = "https://" + instanceName;
    SalesforceRestEP = new http:HTTPConnector(srEndpoint);

**Comment by SupunS** [comment]
Closing the issue as this is fixed. Please reopen if the issue still exists.
