### ISSUE TITLE
Allow variable declarations anywhere :-) and improve declaration & initialization syntax

### ISSUE THREAD

**Issue by sanjiva** [ballerinalang/ballerina#870]
Follow up from James review. Proposed syntax:

var VariableName : TypeName; // like current declaration
var VariableName = Value; // type is inferred from the value
var VariableName : TypeName = Value; // type is explicitly defined and value must match.

Note that with this change variable initialization can also refer to any other vars in scope.

Second, var declarations are now just another type of statement and hence can go anyway. Normal lexical scoping rules will apply.

**Comment by SupunS** [comment]
Grammar change is added with commit db4a791

Functionality support is added in PR: #1645
