### ISSUE TITLE
 Improving SemanticAnalyzer approach of validating ballerina file and error message with hint

### ISSUE THREAD

**Issue by dushansachinda** [ballerinalang/ballerina#909]
Let's take following sample

_import org.wso2.connectors.twitter;
function main (string[] args) {
    twitter:Twitter twitterConnector;
    message res;
    json jsonRes;
    twitterConnector = new twitter:Twitter(args[0], args[1], args[2], args[3]);
    res = twitter:Twitter.tweet(twitterConnector, args[4]);
    jsonRes = message:getJsonPayload(res);
    system:println(json:toString(jsonRes));
}_

Unless, if there aren't any visible default packages, the Semantic analyzer should throw the complete error stack while going through whole *.bal file rather throwing single error at once.

Then, if there is any error, its better if we can see what actions developer may have to take "with Hint"

Please refer mail "shall we improve error messages bit more descriptive (error hint)"

**Comment by sameera-jayasoma** [comment]
We've fixed the compiler to throw multiple errors now.
