### ISSUE TITLE
Versioning strategy for Connectors.

### ISSUE THREAD

**Issue by hasithaa** [ballerinalang/ballerina#95]
What is the recommended way of versioning of a connector? 

* Different package name. (e.g:  ballerina.file.v1,  ballerina.file.v2,  ballerina.filev1,  ballerina.filev2)
* Different connector names (e.g:  FileConnectorV1, FileConnectorV2 etc.)

We can use an annotation to indicate current version of a connector, But this is only for meta information and will not sufficient to distinct a particular version of a connector when creating a connection. 

e.g
```
package ballerina.file;

@version(1.0.0)
connector fileConnector(...){
...
}
```

**Comment by sameera-jayasoma** [comment]
We don't need to version connectors. We will support versioning packages and that way you will get versioned connectors.
